#! /usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
INFRA_DIR=$(dirname -- "${SCRIPT_DIR}")
REPO_DIR=$(dirname -- "${INFRA_DIR}")

obase=${REPO_DIR}/bazel_output_base

chipfile="${INFRA_DIR}/chip"
revfile="${INFRA_DIR}/rev"

if [[ -f "${chipfile}" ]] && [[ -f "${revfile}" ]]; then

    chip=$(cat ${chipfile})
    rev=$(cat ${revfile})

    short=${chip:0:3}

    pwd=$(pwd)

    if [[ $pwd = /proj_risc/user_dev/* ]]; then

        subdir=${REPO_DIR#/proj_risc/user_dev/}

        reg_base="/proj_risc_regr/${short}/${rev}/user_regr"
        if [[ -d "$reg_base" ]]; then
            obase="$reg_base/$subdir/bazel_output_base"
        fi
    fi

fi

if [[ $(uname -n) == "sc39pd01"  ]]; then
    subdir=${REPO_DIR#/proj/ttrentz1/tt}
    reg_base="/scratch/bazel"
    obase="$reg_base${subdir}/bazel_output_base"
fi

echo $obase
