include:
  - local: 'infra/container/gitlab-container.yml'
  - project: 'riscv/dv/gitlab-definitions'
    ref: main
    file: 'common-definitions.yml'

stages:
    - submodule_update
    - build
    - notify

lint:
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    stage: build
    script:
        - (! git grep DECLARE_ -- '**.c' '**.cpp') || (echo "Error - DECLARE statements must be in header files"; exit 1)
        - python3 plusarg_lint.py
        - ${BZSIM} build sw_2c_tb:dpi  --lsf-opt=-mfast --lsf-opt=-qsmoke ${BZSIM_BUILD_OPTS} --config=clang-tidy
    timeout: 1h

smoke:
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    stage: build
    tags:
        - jacamar-lsf
    script:
        - ${BZSIM} test --lsf-opt=-mfast --lsf-opt=-qsmoke ${BZSIM_OPTS} smoke
    timeout: 1h

notify_riscv_cluster:
    stage: notify
    rules:
        # https://tenstorrent.atlassian.net/wiki/spaces/RVRTLDV/pages/1421574263/Ascalon+-+Dependency+Freeze+Plan
        - if: '$CI_COMMIT_BRANCH =~ /^ascalon\/ea\/a0/ && $CI_PIPELINE_SOURCE == "push"'
    extends:
        - .notify-template
    trigger:
        project: riscv/riscv_cluster
        branch: ascalon/work/core
    variables:
        UPDATE_DIRECTORY: rv-common
        UPDATE_TARGET_BRANCH: ascalon/work/core


asan+ubsan:
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    stage: build
    tags:
        - jacamar-lsf
    script:
        - ${BZSIM} test --lsf-opt=-mfast --lsf-opt=-qsmoke  smoke ${BZSIM_OPTS} --config asan+ubsan
    timeout: 1h

tsan:
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    stage: build
    tags:
        - jacamar-lsf
    script:
        - ${BZSIM} test  --lsf-opt=-mfast --lsf-opt=-qsmoke smoke ${BZSIM_OPTS} --config tsan
    timeout: 1h

valgrind:
    extends:
        - .bzsim-template
        - .smoke-rules-all-branches-template
    stage: build
    tags:
        - jacamar-lsf
    script:
        # TODO(mboisvert): Clean this by adding native +valgrind support to runtime.
        - ${BZSIM} test  --lsf-opt=-mfast --lsf-opt=-qsmoke smoke ${BZSIM_OPTS} --bazel-test-opt=--test_tag_filters=-no-valgrind --bazel-test-opt=--test_arg=--run-args=+sim_wrap=/opt/rh/gcc-toolset-11/root/bin/valgrind --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--trace-children=yes --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--tool=memcheck --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--leak-check=full --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--show-reachable=yes --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--track-origins=yes --bazel-test-opt=--test_arg=--run-args=+sim_wrap=--error-exitcode=1
    timeout: 1h


submodule_update:
    stage: submodule_update
    extends:
        - .submodule-update-template

infra_update:
    stage: submodule_update
    extends:
        - .infra-update-template

container_update:
    stage: submodule_update
    extends:
        - .container-update-template
