#include <cstdlib>
#include <string_view>
#include <chrono>

#include "cvm/plusargs.hpp"
#include "cvm/registry.hpp"
#include "cvm/callbacks.hpp"
#include "cvm/logger.hpp"
#include "cvm/random.hpp"
#include "memmap.h"
#include "rv_tester_transactions.hpp"
#include "rv_tester/rv_tester_structs.h"
#include "sysmod/sysmod_plusargs.h"
#include <fmt/format.h>
#include "cosim/utils/eot/eot_plusargs.h"
#include "preload_axi_llc/preload_axi_llc.hpp"
#include "pmu/pmu_plusargs.h"


static bool validate_ge0(const char* flagname, const int value) {
    if (value < 0) {
        cvm::log(cvm::NONE, "Invalid value for +{}={}, must be >= 0\n", flagname, value);
        return false;
    }
    return true;
}
static bool validate_debug_cycle_off(const char* flagname, const uint64_t value);

DEFINE_int32(perf_period, 0, "cycles to wait to report clock performance");
DEFINE_int32(quiesce_timeout, 500, "cycles to wait after eot condition before calling $finish");
DEFINE_int32(flush_timeout, 25000, "cycles to wait after flush is initiated before calling $finish");
DEFINE_bool(terminate_call_finish, true, "Call $finish on sim termination");
DEFINE_bool(rv_tester_enable_llc, false, "Bypass xbar+cache switch");
DEFINE_bool(rv_tester_mem_bypass_cache, false, "Bypass cache switch");
DEFINE_int32(rv_tester_mem_delay, 20, "cycles to delay read responses from xbar");
DEFINE_int32(num_reruns, 0, "Rerun the same test this many times, to test test chaining for emulation. The test is run for a total of N+1 times.");
DEFINE_bool(trace_en, false, "Set this while running trace test");
DEFINE_bool(overlay_mmr_en, false, "Set this while running overlay test");
DEFINE_bool(jtag_en, false, "Set this while running jtag test");
DEFINE_bool(smc_sweep_test ,false, "Set this while running small core sram sweep test");
DEFINE_int32(dmi_poll_timeout, 50000, "Debug poll timeout after to host end call");
DEFINE_int32(disable_dmi_responce_ready, 0, "Disable DMI responce ready for no. of DMI commands");
DEFINE_int32(ndmreset_ack_delay, 0, "Delay after which ndmreset ack is asserted");
DEFINE_int32(trace_timeout, 50000, "trace test end timeout after to host end call");
DEFINE_int32(freq_switch_ncycles, 5000, "Switch clk frequencies after freq_switch_ncycles");
DEFINE_int32(clk_profile, 0, "Clk profile to drive various clocks");
DEFINE_bool(dyn_clk_switch, false, "Enable dynamic clk switching");
DEFINE_validator(num_reruns, &validate_ge0);
DEFINE_string(gen_clocks_verbosity, "HIGH", "verbosity at which to generate clocks with cvm::logger prints");
DEFINE_string(gen_timestamp_verbosity, "HIGH", "verbosity at which to generate timestamps with cvm::logger prints");

DEFINE_string(cvm_debug_verbosity, "DEBUG", "Change the verbosity during the test for certain cycles during the test");
DEFINE_uint64(cvm_debug_cycle_on, 0, "TB cycle on which to change the verbosity to cvm_debug_verbosity");
DEFINE_uint64(cvm_debug_cycle_off, 0, "TB cycle off which to change the verbosity back to cvm_verbosity");
DEFINE_validator(cvm_debug_cycle_off, &validate_debug_cycle_off);
DEFINE_int32(assertion_test_cycle, 0, "If non-zero, assert false on this cycle. Used for testing assertion infrastructure.");
DEFINE_int32(rand_dmi_driver_dly, 0, "Random delay cycles, to be used while driving DMI transactions");
DEFINE_int32(dm_single_step_count, 0, "No of times core to single step, to be used while driving DMI transactions");
DEFINE_int32(sdtrig_multitrigger, 0, "No of trigger condigurations for sdtrig multitrigger test");
DEFINE_int32(trigger_config, 0, "No of store addr configurations for sdtrig test");
DEFINE_bool(priority_singlestep, false, "Prioritize single step over sdtrig in cross feature verification test");
DEFINE_bool(offline_dpi_replay, false, "Set to true to run captured offline DPI function calls while running a zdpireport replay");
DEFINE_bool(disable_haltpoll, false, "Disable poll for halting core, provide resumereq while halting");
DEFINE_string(rv_tester_mem_preload_file, "", "Preload file for AXI LLC. The file must be a CSV generated by Whisper with --initstate");
DEFINE_bool(disable_abscmdpoll, false, "Disable poll for abscmd read, Ndm/Dm Reset while performing debug op");
DEFINE_bool(disable_triggerpoll, false, "Disable poll for trigger in Debug mode");
DEFINE_bool(monitor, true, "Enable monitoring in different checkers - useful for no_rvfi runs");
DEFINE_bool(offline_dpi, false, "Enable OFFLINE DPI capture for emulation");
DEFINE_bool(offline_dpi_test, false, "Enable OFFLINE DPI capture for test mode for simulation");
DEFINE_string(test_start_label, "", "Actual test starts from here(after kernel and initial setup), in case of MP, provide comma separated labels for each hart"); // used in SOT
DEFINE_bool(sdtrig_display, false, "Enable displays for sdtrig constraint-random test");
DEFINE_bool(nonexistent_hart, false, "Core0 to be halted for nonexistent haltreq");
DEFINE_int32(abscmd_hang_counter, 0, "delay value for abscmd hang");

static bool validate_debug_cycle_off(const char* flagname, const uint64_t value) {
  if ((value==0) && (FLAGS_cvm_debug_cycle_on > 0))
    FLAGS_cvm_debug_cycle_off = -1;
  if ((value > 0) && (FLAGS_cvm_debug_cycle_on >= value )) {
    cvm::log(cvm::NONE, "Invalid value for +{}={}, must be greater than cvm_debug_cycle_on={}\n", flagname, value, FLAGS_cvm_debug_cycle_on);
    return false;
  }
  return true;
}

extern "C" void rv_tester_terminate();
extern "C" void rv_tester_set_address_map(std::uint32_t i, std::uint64_t start_addr, std::uint64_t end_addr, std::uint32_t device);
extern "C" void set_preload_data_file(std::uint32_t way, const char* file);
extern "C" void set_preload_tag_file(std::uint32_t way, const char* file);

static bool check_called;
class logger_instrument {

    public:
        logger_instrument(cvm::topology::loc_t loc, unsigned) : loc(loc) {};

        void configure() {
            clock = 0;
            timestamp = 0;

            cvm::set_logger_prefix([]() -> std::string_view {
                prefix = (timestamp)? "[" + std::to_string(timestamp) + "ps]" : "";
                prefix += (clock)? "[" + std::to_string(clock) + "] " : "";
                return prefix;
            });

            cvm::registry::messenger.connect<rv_tester_transactions::logger::cycle<>>(loc, [] (const auto& c) { clock = c.clock; });
            cvm::registry::messenger.connect<rv_tester_transactions::logger::timestamp<>>(loc, [] (const auto& t) { timestamp = t.timeval; });

        }

        void check() {
            // we want this to be low prio and async so it goes behind existing rvfi transactions in the queue
            // because of QoS this could have been seen before all rvfi transactions up to this instruction were processed
            cvm::registry::messenger.signal_async<rv_tester::terminate_called>(loc, rv_tester::terminate_called{}, cvm::messenger::lowest_priority);
            if (!FLAGS_offline_dpi_replay) {
                cvm::registry::messenger.signal_async<rv_tester::terminate_called>(loc, rv_tester::terminate_called{}, cvm::messenger::lowest_priority);
                cvm::registry::callbacks.push(
                    scope,
                    []() {
                        return rv_tester_terminate();
                    });
            }
        }

        static void set_scope(svScope s) { scope = s; };

    private:

        static svScope scope;
        static std::string prefix;
        static uint64_t clock;
        static uint64_t timestamp;
        cvm::topology::loc_t loc;
};

static std::string process_preload_file(int num_ways, int num_sets, int num_blocks, int addr_width, int data_width) {
    std::string preloadStr = FLAGS_rv_tester_mem_preload_file;
    if (!preloadStr.empty() && preloadStr.substr(preloadStr.size() - 4) == ".csv") {
        preload_axi_llc::PreloadFiles pf = preload_axi_llc::convert_csv_to_preload_files_per_way(preloadStr, num_sets, num_blocks, num_ways, addr_width, data_width);
        if (pf.dataFiles.empty() || pf.tagFiles.empty()) {
            cvm::log(cvm::ERROR, "Error: CSV conversion failed; no preload files generated.");
            return "";
        }
        for (int w = 0; w < num_ways; w++) {
            set_preload_data_file(w, pf.dataFiles[w].c_str());
            set_preload_tag_file(w, pf.tagFiles[w].c_str());
        }
        preloadStr = pf.dataFiles[0];
    }
    return preloadStr;
}

extern "C" {

    int rv_tester_perf_calc(int init, int reset_done, int terminate, std::uint64_t clocks) {
        //cvm::log(cvm::NONE, "rv_tester_perf_calc(init={} terminate={}  clocks={})\n", init,terminate,clocks);
        static std::chrono::time_point<std::chrono::high_resolution_clock> zero_time;
        static std::chrono::time_point<std::chrono::high_resolution_clock> start_time;
        static std::chrono::time_point<std::chrono::high_resolution_clock> end_time;
        static std::chrono::time_point<std::chrono::high_resolution_clock> rstdone_time;
        int pcps,tcps,period;
        static std::uint64_t first_clk, rdone_clk;
        static std::uint64_t last_clk;

        end_time = std::chrono::high_resolution_clock::now();

        if (init==1) {
            first_clk = clocks;
            last_clk  = clocks;
            zero_time = end_time; 
            start_time = end_time;
            return(1);
        }


        if (reset_done==1) {
           auto rduration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - zero_time).count();
           pcps = 0;
           period = clocks - first_clk;
           rstdone_time = end_time;
           rdone_clk  = clocks;
           if (rduration > 0) {
              pcps = (int)(period/rduration);
           }
           cvm::log(cvm::NONE, "time={}  reset_performance_khz\": {}\n", clocks,pcps);
           start_time = end_time; 
           last_clk = clocks;
           return(1);
        }

        if (terminate==1) {
           auto tduration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - rstdone_time).count();
           period = clocks - rdone_clk;
           if (tduration > 0) {
              tcps = (int)(clocks/tduration);
           }
           cvm::log(cvm::NONE, "INFO_PASS_METRIC:{{\"exec_performance_khz\": {}}}\n", tcps);

           tduration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - zero_time).count();
           tcps = 0;
           period = clocks - first_clk;
           if (tduration > 0) {
              tcps = (int)(clocks/tduration);
           }
           cvm::log(cvm::NONE, "INFO_PASS_METRIC:{{\"test_performance_khz\": {}}}\n", tcps);
           last_clk = clocks;
           start_time = end_time; 
           return(1);
        }

        auto pduration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count();
        pcps = 0;
        if (pduration > 0) { 
           period = clocks - last_clk;
           pcps = (int)(period/pduration);
        }
        cvm::log(cvm::NONE, "time:{}  period_performance_khz\": {}\n", clocks,pcps);
        start_time = end_time; 
        last_clk = clocks;
        return(1);

    }

    int rv_tester_parse_flags() {
        cvm::log(cvm::NONE, "[plusargs] Parsing...\n");
        cvm::plusargs::parse();
        return 0;
    }

    void rv_tester_set_seed() {
        cvm::log(cvm::NONE, "[random] +seed={}\n", FLAGS_seed);
        cvm::rand::seed(FLAGS_seed);
    }

    void rv_tester_parse_memmap(std::uint32_t no_addr_rules, int num_ways, int num_sets, int num_blocks, int addr_width, int data_width) {

        std::map<std::string, memmap_entry_t> m;
        if (!cvm::registry::messenger.call<memmap::getRPC>(cvm::topology::get_from_hierarchy("TOP.PLATFORM.MEMMAP", 0), m))
            return;
        if (m.size() > no_addr_rules) {
            cvm::log(cvm::ERROR, "Error: Test specifying more address rules ({}) than in sv ({})", m.size(), no_addr_rules);
            return;
        }
        std::string preloadStr = process_preload_file(num_ways, num_sets, num_blocks, addr_width, data_width);

        std::uint32_t i = 0;
        for (const auto& it : m) {
            const auto& e = it.second;
            rv_tester_set_address_map(i, e.base, e.end, e.type != "memory");
            i++;
        }
        for(; i < no_addr_rules; i++) {
            rv_tester_set_address_map(i, 1, 1, 1);
        }
    }

    void rv_tester_build_registry() {
        check_called = false;
        cvm::registry::build();
        cvm::registry::configure();
    }
   
    void rv_tester_no_dm_build_registry() {
        auto dm_loc = cvm::topology::get_from_hierarchy("TOP.PLATFORM.DM_MODEL", 0);
        check_called = false;
        cvm::registry::build_all_except(dm_loc);
        cvm::registry::configure();
    } 
    void rv_tester_dm_build_registry() {
        auto dm_loc = cvm::topology::get_from_hierarchy("TOP.PLATFORM.DM_MODEL", 0);
        cvm::log(cvm::NONE, "[registry] build dm components ...\n");
        cvm::registry::build(dm_loc);//pass dm location
        //cvm::registry::configure();//pass dm location
    }

    uint8_t rv_tester_shutdown_registry() {
        auto dm_loc = cvm::topology::get_from_hierarchy("TOP.PLATFORM.DM_MODEL", 0);
        if (!check_called) {
            cvm::log(cvm::NONE, "[registry] check...\n");
            cvm::registry::check();
            check_called = true;
        }

        cvm::log(cvm::NONE, "[registry] shutdown...\n");
        //return cvm::registry::shutdown();
        return cvm::registry::shutdown_all_except(dm_loc);
    }
    
    uint8_t rv_tester_dm_shutdown_registry() {
        auto dm_loc = cvm::topology::get_from_hierarchy("TOP.PLATFORM.DM_MODEL", 0);
        cvm::log(cvm::NONE, "[registry] dm shutdown check...\n");
 

        cvm::log(cvm::NONE, "[registry] dm shutdown...\n");
        return cvm::registry::shutdown(dm_loc);//dm location
    }

    uint8_t rv_tester_flush_callbacks() {
        cvm::registry::callbacks.flush();
        // force verilator to serialize
        return true;
    }

    void rv_tester_cvm_error() {
        if (!check_called) {
            cvm::registry::check();
        }
    }

    void rv_tester_cvm_error_handler() {
        logger_instrument::set_scope(svGetScope());
        cvm::set_logger_handler(cvm::ERROR, rv_tester_cvm_error);
    }

    void rv_tester_streaming_dpi_init_domain_1() {
        cvm::log(cvm::MEDIUM, "Streaming DPI init\n");
        char *env_var = std::getenv("ZEBU_OFFLINE_DPI");
        if ((env_var != nullptr && std::string(env_var) == "1")) {
            cvm::log(cvm::NONE, "[streaming_dpi] initializing offline dpi\n");
            rv_tester_parse_flags();

            // override flags in offline mode
            FLAGS_offline_dpi_replay = true;
            FLAGS_sysmod_terminate = false;
            FLAGS_signal_async = false;
            FLAGS_perf = false;
            FLAGS_offline_dpi = false;

            rv_tester_cvm_error_handler();
            rv_tester_build_registry();
        }
    }

    void rv_tester_streaming_dpi_shutdown() {
        cvm::log(cvm::HIGH, "Streaming DPI shutdown\n");
        if (!FLAGS_offline_dpi_replay) {
            return;
        }
        cvm::log(cvm::NONE, "[streaming_dpi] shutting down registry\n");
        if (!rv_tester_shutdown_registry()) {
            cvm::log(cvm::ERROR, "Error: [streaming_dpi] failed to shutdown registry\n");
        }
        rv_tester_dm_shutdown_registry();
    }
}

svScope logger_instrument::scope;
std::string logger_instrument::prefix;
uint64_t logger_instrument::clock;
uint64_t logger_instrument::timestamp;

REGISTRY_register(logger_instrument, TOP.PLATFORM, 0);
