package rv_tester_pkg;

    parameter SC_COUNTER_HI = 32;

    //AUTOGENERATED -- NOTOUCH
    typedef enum {
        SC_CACHE_ACCESS,
        SC_CACHE_RD,
        SC_CACHE_MISS,
        SC_CACHE_MISS_RD,
        SC_CACHE_REFILL,
        SC_CACHE_ALLOCATE,
        SC_CACHE_WB_DIRTY,
        SC_CACHE_WB_CLEAN,
        SC_CACHE_INVAL,
        SC_SNOOP,
        SC_SCRATCHPAD_RD,
        SC_SCRATCHPAD_WR,
        F2SC_RD,
        F2SC_WR,
        MSHR_LIFETIME,
        MSHR_ALLOCATIONS,
        SC2F_RD_U,
        SC2F_RD_C,
        SC2F_RD_O,
        SC2F_WR,
        C2SC_RD_I,
        C2SC_RD_D,
        C2SC_WB_FULL,
        C2SC_EVICT,
        C2SC_SNP_WB_FULL,
        C2SC_WRNOSNPPTL,
        C2SC_SNP,
        C2SC_REQ_STALL,
        C2SC_WDAT_STALL,
        C2SC_SRSP_STALL,
        C2SC_RDAT_STALL,
        C2SC_SNP_STALL,
        C2SC_CRSP_STALL,
        SC2F_EVICT,
        SC2F_WRBACKFULL,
        SC2F_WDAT,
        SC2F_SNOOP,
        SC2F_RDAT,
        SC2F_REQ_STALL,
        SC2F_WDAT_STALL,
        SC2F_SRSP_STALL,
        SC2F_RDAT_STALL,
        SC2F_SNOOP_STALL,
        SC2F_CRSP_STALL,
        F2SC_WDAT,
        F2SC_RDAT,
        F2SC_WRNOSNPPTL,
        F2SC_REQ_STALL,
        F2SC_WDAT_STALL,
        F2SC_RDAT_STALL,
        F2SC_CRSP_STALL,
        SC_TAG_LOOKUP,
        SC_TAG_WRITE,
        SC_STATE_WRITE,
        SC_REPL_WRITE,
        SC_TAG_HIT,
        SC_DATA_READ,
        SC_DATA_WRITE,
        SC_STATE_I2E,
        SC_STATE_I2M,
        SC_STATE_I2S,
        SC_STATE_S2I,
        SC_STATE_S2M,
        SC_STATE_S2E,
        SC_STATE_M2I,
        SC_STATE_M2S,
        SC_STATE_M2E,
        SC_STATE_E2I,
        SC_STATE_E2S,
        SC_STATE_E2M,
        SFT_LOOKUP,
        SFT_HIT,
        SFT_WRITE,
        SFT_EVICTION,
        SFT_SNP_SINGLE_ICACHE,
        SFT_SNP_SINGLE_DCACHE,
        SFT_SNP_MULTI_CORES,
        SFT_EVICTION_REPLAY,
        MSHR_OCCUPANCY,
        MSHR_FULL,
        MSHR_SAQ_ALLOC,
        MSHR_SAQ_FULL,
        NO_ALLOC_NO_MSHR,
        NO_ALLOC_HINT_NOT_SET,
        SC_REPLAY_ECC,
        SC_CANCEL_PIPERESULT,
        SC_VICTIM,
        NO_ALLOC_SRRIP,
        SC_EVENT_COUNT
    } sc_pmc_event_t;

    typedef logic [SC_COUNTER_HI:0] sc_pmc_counter_t;
    typedef sc_pmc_counter_t [SC_EVENT_COUNT-1:0] sc_pmci_t;

    typedef struct packed {
        logic derr;
        logic lcofi;
        logic sgei;
        logic mei;
        logic vsei;
        logic sei;
        logic mti;
        logic vsti;
        logic sti;
        logic msi;
        logic ssi;
        logic [63:0] mtime;
    } interrupt_t;

    typedef struct packed {
        logic nmi;
        logic clai;
    } nmi_t;

    typedef enum logic [1:0] {
        EXCP   = 2'h0,
        INTR   = 2'h1,
        NMI    = 2'h2
    } trap_e;

    typedef enum logic [1:0] {
        DTM_NOP   = 2'h0,
        DTM_READ  = 2'h1,
        DTM_WRITE = 2'h2
    } dtm_op_e;

    typedef struct packed {
        logic        dm_wvalid;
        logic [63:0] dm_wdata;
    } dm_write_t;

    typedef struct packed {
        logic [6:0]  addr;
        dtm_op_e     op;
        logic [31:0] data;
    } dmi_req_t;

    typedef struct packed {
        logic tms;
        logic tdi;
    } jtag_if_t;

    typedef struct packed {
        logic tdo;
        logic tdo_en;
    } jtag_if_out;

    typedef struct packed {
        logic tck;
        logic trst;
    } jtag_if_tck;

    typedef struct packed  {
        logic [31:0] data;
        logic [1:0]  resp;
    } dmi_resp_t;

    typedef struct packed {
        logic terminate;
    } terminate_t;

    typedef longint unsigned c_handle;
    parameter c_handle nil = '0;

endpackage
