#include "axi_sw.h"

DEFINE_int32(axi_sw_read_latency_max, 0, "Maximum latency of axi reads");
DEFINE_int32(axi_sw_read_latency_timeout_threshold, 1, "How many cycles under axi_sw_read_latency_max before stopping the clock on zebu. This should usually be more than zero to prevent race conditions on the zebu");
DEFINE_int32(axi_sw_read_latency_fifo_threshold, 1, "How many remaining fifo entries in the read request history fifo before stopping the clock on zebu.");
DEFINE_int32(axi_sw_read_latency_fixed, 0, "Fixed latency of axi reads");
DEFINE_bool(axi_sw_read_no_callbacks, false, "Plusarg to test synchronous read flushes are working by turning off asynchronous callbacks. Must use with +axi_sw_read_latenxy_*");
DEFINE_int32(axi_sw_read_consecutive_spurious_calls_allowed, -1, "Ignore N spurious call after a non-spurious call. Set to -1 to ignore all spurious calls. Spurious calls should not break function but slow down emulation.");

DEFINE_uint32(axi_sw_reorder_window, 0, "If reorder window > 1, will randomly attempt to reorder ar/aw requests within the window. Otherwise, transactions are handled in-order.");
DEFINE_uint32(axi_sw_reorder_timeout, 100, "If reorder window > 1, will attempt to flush transaction every N cycles while window is not drained (prevent stalls).");

DEFINE_bool(axi_sw_fast_write_response, false, "If fast write response, SV will immediately return write response without going through DPI.");

DEFINE_uint32(axi_sw_lfsr_seed_aw_rdy, 0, "LFSR seed for aw ready toggling.");
DEFINE_uint32(axi_sw_lfsr_mask_aw_rdy, 0, "LFSR mask for aw ready toggling. When the LFSR value AND-ed with the mask is 0, we toggle ready high.");
DEFINE_uint32(axi_sw_lfsr_seed_ar_rdy, 0, "LFSR seed for ar ready toggling.");
DEFINE_uint32(axi_sw_lfsr_mask_ar_rdy, 0, "LFSR mask for ar ready toggling. When the LFSR value AND-ed with the mask is 0, we toggle ready high.");
DEFINE_uint32(axi_sw_lfsr_seed_w_rdy, 0, "LFSR seed for w ready toggling.");
DEFINE_uint32(axi_sw_lfsr_mask_w_rdy, 0, "LFSR mask for w ready toggling. When the LFSR value AND-ed with the mask is 0, we toggle ready high.");

static bool validate_add_response_latency_range([[maybe_unused]] const char* flagname, const std::string& value) {
  auto [ok, _, _2] = _axi_sw::get_uint64_pair(value);
  return ok;
}

DEFINE_string(axi_sw_add_response_latency_range, "0:1", "Range of random response latency added [min, max).");
DEFINE_validator(axi_sw_add_response_latency_range, &validate_add_response_latency_range);

extern "C" {

// SV DPI exports generated by the AXI_SW_DPI_FIFO macro (axi_sw_r/axi_sw_b).
void axi_sw_r_reset();
void axi_sw_b_reset();

std::uint8_t axi_sw_reset_ptrs(cvm::topology::loc_t loc) {
  // Zero the SV FIFO write pointers from the C/DPI domain. wptr_nxt must NOT be
  // reset from RTL (e.g. inside the AXI_SW_DPI_FIFO macro) -- on ZeBu that makes
  // wptr_nxt a dual-driver (RTL + DPI) and the DPI push increment is silently
  // dropped. Calling these exports from within this DPI *import* is ZeBu-legal.
  axi_sw_r_reset();
  axi_sw_b_reset();
  cvm::registry::messenger.signal<axi_sw_reset_t>(loc, {});
  return 0;
}

std::uint8_t axi_sw_flush(cvm::topology::loc_t loc, std::uint64_t clock, axi_sw_defs::r_q_ptr_t ptr) {
  if (_axi_sw::axi_sw_destroyed)
    return true;
  bool successful = false;
  std::atomic<bool> done(false);
  cvm::registry::messenger.signal_async<axi_sw_defs::r_q_ptr_blocking_update_t>(loc, axi_sw_defs::r_q_ptr_blocking_update_t{clock, ptr, &successful, &done}, cvm::messenger::highest_priority);
  done.wait(false);
  return successful;
}

void axi_sw_reorder_flush(cvm::topology::loc_t loc) {
  cvm::registry::messenger.signal<axi_sw_defs::reorder_q_flush_t>(loc, axi_sw_defs::reorder_q_flush_t{});
  return;
}
}
