#! /usr/bin/env bash

set -e
set -o pipefail

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
container_dir="$script_dir/podman-scripts"

git_getter="$script_dir/git_getter.py"
if [ ! -f "$git_getter" ]; then
    echo "No git getter script found at expected '${git_getter}'" 1>&2
    exit 1
fi
/usr/bin/python3 "${git_getter}"

if [[ -z "${SINGULARITY_CONTAINER}" ]]; then
    if ! "$container_dir/cannot-run-container" ; then
        exec "$container_dir/container-run-tt" "${BASH_SOURCE[0]}" "$@"
    fi
fi

# Source environment
if [[ -z "${RISC_P_CORES_ENV_SOURCED+x}" ]]; then
    . "${script_dir}/env.sh"
fi


exec $script_dir/bzsim_clone/bazel-wrap "$@"
