#! /usr/bin/env python3

import os, sys
from pathlib import Path
from git_getter import GitGetter

''' bzsim bootstrap script; gets repos specified in sha.json and launches bzsim'''

script_path = Path(__file__).resolve()
infra_dir = script_path.parent

# Get git repos, import container
getter = GitGetter(script_path)
getter.get_repos()
os.execvp(infra_dir / "bzsim_clone" / "bzsim", sys.argv)

