#! /usr/bin/env bash

set -e
set -o pipefail


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONTAINER_DIR=$SCRIPT_DIR/podman-scripts

if [ ! -d "$CONTAINER_DIR" ]; then
  echo "No container dir found"
  GIT_GETTER=$SCRIPT_DIR/git_getter.py
  if [ ! -f $GIT_GETTER ]; then
    echo "No git getter script found at expected ${GIT_GETTER}" 
    exit 1
  fi
  /usr/bin/python3 ${GIT_GETTER}
  CANNOT_RUN_CONTAINER=$(! command -v "podman" > /dev/null)
  if $CANNOT_RUN_CONTAINER ; then 
    exec $SCRIPT_DIR/checkin.py "$@"
  fi
fi


if $CONTAINER_DIR/cannot-run-container ; then
    echo cant run container
    exec $SCRIPT_DIR/checkin.py "$@"
fi

exec $CONTAINER_DIR/container-run-tt $SCRIPT_DIR/checkin.py --user $USER "$@"
