#! /usr/bin/env bash

# this is a wrapper to find a tool in the infra/ subdir when in the repo
# install it somewhere on your path and then create a symlink to it with the
# names of any tools, eg
# cp git-infra-tool /home/risc/tools/common && ln -sT git-infra-tool /home/risc/tools/common/bzsim

set -e
set -o pipefail

REPO=$(git rev-parse --show-toplevel)
SCRIPT=$(basename $0)
exec ${REPO}/infra/${SCRIPT} "$@"
