#!/usr/bin/env python3

import logging
import os
import pathlib
import re
import subprocess
import sys

class BazelTest():
    def __init__( self, name, *args, **kwargs ):
        self.bazel_wrap         = None
        self.container_run_tt   = None
        self.workspace_name     = None
        self.script             = None
        self.runfiles           = None
        self.name               = name

    def __check_file( self, file_check ):
        logger = logging.getLogger()
        logger.info( 'Checking {0} file at path {1}'.format( file_check.name, file_check.parent ) )

        if not file_check.is_file():
            raise Exception( '{0} file not found at {1}'.format( file_check.name, file_check.parent ) )

    def __check_dir( self, dir_check ):
        logger = logging.getLogger()
        logger.info( 'Checking dir path {0}'.format( str( dir_check ) ) )

        if not dir_check.is_dir():
            raise Exception( 'dir {0} not found'.format( str( dir_check ) ) )

    def check_bazel_wrap( self ):
        self.bazel_wrap = pathlib.Path( os.path.realpath( __file__ ) ).parent / 'bazel-wrap'
        self.__check_file( self.bazel_wrap )

    def check_container_run_tt( self ):
        self.container_run_tt = pathlib.Path( os.path.realpath( __file__ ) ).parent / 'podman-scripts' / 'container-run-tt'
        self.__check_file( self.container_run_tt )

    def get_workspace_name( self ):
        logger = logging.getLogger()

        cmd = [ str( self.bazel_wrap ), 'info', 'execution_root' ]
        logger.info( 'Running command: ' + ' '.join( cmd ) )

        info_process = subprocess.run( cmd,
            stdout = subprocess.PIPE,
            stderr = subprocess.STDOUT
        )
        if info_process.returncode != 0:
            raise Exception( 'bazel info resulted with non-zero exit code.' )

        info_stdout = info_process.stdout.decode( 'utf-8' )
        info_stdout = info_stdout.split( '\n' )
        info_stdout = info_stdout[1].rstrip()

        self.workspace_name = os.path.basename( info_stdout )
        logger.info( 'Workspace name: ' + self.workspace_name )

        return

    def get_script_and_runfiles( self ):
        logger = logging.getLogger()

        cmd = [ str( self.bazel_wrap ), 'aquery', 'tests("{bazel_test}")'.format( bazel_test = self.name ) ]
        logger.info( 'Running command: ' + ' '.join( cmd ) )
        aquery_process = subprocess.run( cmd,
            stdout = subprocess.PIPE,
            stderr = subprocess.STDOUT
        )
        if aquery_process.returncode != 0:
            raise Exception( 'bazel aquery resulted with non-zero exit code. Please make sure target name is correct' )

        aquery_stdout = aquery_process.stdout.decode( 'utf-8' )

        script, runfiles                            = None, None
        script_info_started, runfiles_info_started  = False, False

        for line in aquery_stdout.split( '\n' ):
            if re.search( "action 'Writing script .*", line ):
                script_info_started = True
                continue

            if re.search( "action 'Creating runfiles .*", line ):
                runfiles_info_started = True
                continue

            output_re = re.search( 'Outputs: \[([^]]*)\]', line )
            if bool( output_re ):
                if script_info_started:
                    script = output_re.group(1)
                    script_info_started = False
                elif runfiles_info_started:
                    runfiles = output_re.group(1)
                    runfiles = os.path.dirname( runfiles )
                    runfiles_info_started = False

            if script is not None and runfiles is not None:
                break

        if script is None:
            raise Exception( 'test script cannot be located' )

        if runfiles is None:
            raise Exception( 'runfiles directory cannot be located' )

        script      = pathlib.Path( os.path.realpath( script ) )
        runfiles    = pathlib.Path( os.path.realpath( runfiles ) ) / self.workspace_name

        logger.info( f'Script path for test: {script}' )
        logger.info( f'Run files path for test: {runfiles}' )

        self.script     = script
        self.runfiles   = runfiles
        self.__check_file( self.script )
        self.__check_dir( self.runfiles )

    def run( self ):
        logger = logging.getLogger()

        self.check_bazel_wrap()
        self.check_container_run_tt()
        self.get_workspace_name()
        self.get_script_and_runfiles()

        logger.info( f'Creating a bash script named test.sh in cwd to run {self.script} from {self.runfiles} path' )
        with open( 'test.sh', 'w' ) as fp:
            fp.write( f'''#!/usr/bin/bash
cd {self.runfiles}
{self.script}
''')
        os.chmod( 'test.sh', 0o755 )
    
        container_run = subprocess.run( [ self.container_run_tt, os.path.realpath( 'test.sh' ) ] )
    
        return container_run.returncode

# ----------------------------------------------------
# script execution starts
# ----------------------------------------------------

if len( sys.argv ) != 2:
    raise Exception( os.path.basename( __file__ ) + ' expects one and only one bazel test name to run' )

logging.basicConfig(
    format  = '[%(levelname)s] %(asctime)s - %(message)s',
    level   = logging.INFO,
    stream  = sys.stdout,
)
bazel_test = BazelTest( sys.argv[1] )
sys.exit( bazel_test.run() )
