#! /usr/bin/env bash

set -e
set -o pipefail

# 1. updates bzsim / containers
# 2. Launches container, calling rvcom.py

echo ${BASH_SOURCE[0]}
ARGS="$@"
if [[ ${BASH_SOURCE[0]} != *"rvcom"* ]] ; then
  ARGS="$(basename ${BASH_SOURCE[0]}) $@"
fi


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
GIT_GETTER=$SCRIPT_DIR/git_getter.py
if [ ! -f $GIT_GETTER ]; then
    echo "No git getter script found at expected ${GIT_GETTER}" 
    exit 1
fi

# Clone bootstrap repos
PYTHON3=/usr/bin/python3
$PYTHON3 ${GIT_GETTER}

RVCOM=$SCRIPT_DIR/rvcom.py
if [ ! -f $RVCOM ]; then 
    echo "No rvcom.py script found at expected ${RVCOM}" 
    exit 1
fi

# gen_scr_script unique, located in infra
if [[ ${BASH_SOURCE[0]} == *"gen_csr_script"* ]] ; then
    PODMAN_RUN_OPTS="-v /tools_risc:/tools_risc" exec $SCRIPT_DIR/podman-scripts/container-run-tt python3 $SCRIPT_DIR/gen_csr/gen_csr.py "$@"
fi



if [[ -z "${SINGULARITY_CONTAINER}" ]]; then
    if ! $SCRIPT_DIR/podman-scripts/cannot-run-container ; then
        exec $SCRIPT_DIR/podman-scripts/container-run-tt  $RVCOM $ARGS
    fi
fi
