module pmu
import rv_tester_params::*;
#(
  parameter int NUM = -1,
  parameter int NRET = 1,
  `TOPOLOGY,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PARAMS
)(
  input tb_clk,
  input clk,
  input reset,
  input longint unsigned clocks,
  input pmci_t pmci,
  input sc_pmci_t sc_pmci,
  input rvfi_t [NRET-1:0] rvfi,
  input bit terminate,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PORTS
);

    int unsigned location = cvm_topology::nil;
    longint unsigned period = 0;
    longint unsigned instructions = 0;
    bit cycle_sync_en, instruction_sync_en;
    assign cycle_sync_en = (period != '0);
    assign instruction_sync_en = (instructions != '0);
    bit perf_enabled = '0;
    bit perf_start = '0;
    bit perf_end = '0;

    always @(posedge tb_clk) begin
        if (reset) begin
            /* verilator lint_off BLKSEQ */
            location = cvm_topology::get_location(topology.TOP.PLATFORM.PMCI.ID, NUM);
            perf_enabled = (cvm_plusargs::get_bool("perf") != '0) & (location != cvm_topology::nil);
            period = cvm_plusargs::get_ulongint("sync_pmcounters_period");
            instructions = cvm_plusargs::get_ulongint("sync_pmcounters_instructions");
            /* verilator lint_on BLKSEQ */
        end
    end

    longint unsigned cpu_cycles = 0;
    longint unsigned sync_cycles = 0;
    longint unsigned sync_instructions = 0;
    longint unsigned prev_sync_instructions = 0;
    longint unsigned nret = {32'h0, NRET};
    longint unsigned pmcounter [EVENT_COUNT] = '{default:0};
    longint unsigned sc_pmcounter [SC_EVENT_COUNT] = '{default:0};

    always @(posedge clk) begin
      if (reset) begin
        pmcounter[0] <= 0;
        sc_pmcounter[0] <= 0;
        cpu_cycles <= 0;
        sync_cycles <= 0;
        sync_instructions <= 1;
      end else begin
        if (perf_start) begin
          sync_cycles <= 1;
          sync_instructions <= nret;
        end else if (perf_end) begin
          sync_cycles <= cpu_cycles;
          sync_instructions <= pmcounter[INSTRUCTIONS];
        end else begin
          sync_cycles <= sync_cycles + 1;
          sync_instructions <= sync_instructions + {60'h0, pmci[INSTRUCTIONS]};
        end
        cpu_cycles <= cpu_cycles + 1;
      end
      prev_sync_instructions <= sync_instructions;
    end

    generate
      for (genvar i=1; i < EVENT_COUNT; i++) begin : pmci_regs
        always @(posedge clk) begin
            if (reset) begin
                pmcounter[i] <= 0;
            end else begin
                pmcounter[i] <= pmcounter[i] + {60'h0, pmci[i]};
            end
        end
      end
      for (genvar i=1; i < SC_EVENT_COUNT; i++) begin : sc_pmci_regs
        always @(posedge clk) begin
            if (reset) begin
                sc_pmcounter[i] <= 0;
            end else begin
                sc_pmcounter[i] <= sc_pmcounter[i] + {58'h0, sc_pmci[i]};
            end
        end
      end
    endgenerate

    bit [NRET-1:0] perf_match_array_start;
    bit [NRET-1:0] perf_match_array_end;
    always @(*) begin
      for (integer n = 0; n < NRET; n++) begin
        perf_match_array_start[n] = (rvfi[n].insn == 32'h00058013) && rvfi[n].valid;
        perf_match_array_end[n] = (rvfi[n].insn == 32'h00060013) && rvfi[n].valid;
      end

      perf_start = | perf_match_array_start;
      perf_end = | perf_match_array_end;
    end

   logic [EVENT_COUNT-1:0][3:0]  evt_avg;

   generate
      for(genvar i=0; i<EVENT_COUNT; i++) begin : evt_logic
         logic [3:0] mod_pmci;

         assign mod_pmci = (pmci[i][0]===1'bx) ? 4'b0 : pmci[i];

         // 128-cycle moving average
         logic       ema_busy;
         logic       ema_en;

         assign ema_en   = |mod_pmci | ema_busy;

         pmu_ema #(.WIDTH(4), .DECAY(7))
         u_evt (.i_clk(clk), .i_reset_n(!reset), .i_en(ema_en),
                .i_activity(mod_pmci), .i_decayadj('0),
                .o_activity(evt_avg[i]), .o_busy(ema_busy));
      end
   endgenerate

    
    //AUTOGENERATED -- NO TOUCH
    assign pmcounterss[0].valid = !reset && perf_enabled && (terminate || (cycle_sync_en & (sync_cycles % period) == 0) || (instruction_sync_en && (((prev_sync_instructions % instructions) > nret) && ((sync_instructions % instructions) < nret))) || perf_start || perf_end);
    assign pmcounterss[0].data.location = location;
    assign pmcounterss[0].data.cpu_cycles = cpu_cycles;
    assign pmcounterss[0].data.instructions = pmcounter[INSTRUCTIONS];
    assign pmcounterss[0].data.perf_start = perf_start;
    assign pmcounterss[0].data.perf_end = perf_end;
    assign pmcounterss[0].data.terminate = terminate;
    assign pmcounterss[0].data.sync = (cycle_sync_en && (sync_cycles % period) == 0) || (instruction_sync_en && (((prev_sync_instructions % instructions) > nret) && ((sync_instructions % instructions) < nret)));
    assign pmcounterss[0].data.m_mode_cycles = pmcounter[M_MODE_CYCLES];
    assign pmcounterss[0].data.m_mode_instret = pmcounter[M_MODE_INSTRET];
    assign pmcounterss[0].data.s_mode_cycles = pmcounter[S_MODE_CYCLES];
    assign pmcounterss[0].data.s_mode_instret = pmcounter[S_MODE_INSTRET];
    assign pmcounterss[0].data.u_mode_cycles = pmcounter[U_MODE_CYCLES];
    assign pmcounterss[0].data.u_mode_instret = pmcounter[U_MODE_INSTRET];
    assign pmcounterss[0].data.ref_cpu_cycles = pmcounter[REF_CPU_CYCLES];
    assign pmcounterss[0].data.stalls_bst_full = pmcounter[STALLS_BST_FULL];
    assign pmcounterss[0].data.stalls_pfx_full = pmcounter[STALLS_PFX_FULL];
    assign pmcounterss[0].data.stalls_indirect_miss = pmcounter[STALLS_INDIRECT_MISS];
    assign pmcounterss[0].data.stalls_icache_miss = pmcounter[STALLS_ICACHE_MISS];
    assign pmcounterss[0].data.stalls_itlb_miss = pmcounter[STALLS_ITLB_MISS];
    assign pmcounterss[0].data.stalls_irb_full = pmcounter[STALLS_IRB_FULL];
    assign pmcounterss[0].data.stalls_ifbuf_full = pmcounter[STALLS_IFBUF_FULL];
    assign pmcounterss[0].data.stalls_exception = pmcounter[STALLS_EXCEPTION];
    assign pmcounterss[0].data.page_crossing_fetchblocks = pmcounter[PAGE_CROSSING_FETCHBLOCKS];
    assign pmcounterss[0].data.nfp_early_redirect = pmcounter[NFP_EARLY_REDIRECT];
    assign pmcounterss[0].data.nfp_late_redirect = pmcounter[NFP_LATE_REDIRECT];
    assign pmcounterss[0].data.ifbuf_full_redirect = pmcounter[IFBUF_FULL_REDIRECT];
    assign pmcounterss[0].data.nonspec_resync = pmcounter[NONSPEC_RESYNC];
    assign pmcounterss[0].data.fault_resync = pmcounter[FAULT_RESYNC];
    assign pmcounterss[0].data.fault_refetch = pmcounter[FAULT_REFETCH];
    assign pmcounterss[0].data.cmode_entry = pmcounter[CMODE_ENTRY];
    assign pmcounterss[0].data.branch_misses = pmcounter[BRANCH_MISSES];
    assign pmcounterss[0].data.br_ret_misses = pmcounter[BR_RET_MISSES];
    assign pmcounterss[0].data.ind_br_misses = pmcounter[IND_BR_MISSES];
    assign pmcounterss[0].data.rel_br_misses = pmcounter[REL_BR_MISSES];
    assign pmcounterss[0].data.spec_branch_redirect = pmcounter[SPEC_BRANCH_REDIRECT];
    assign pmcounterss[0].data.spec_lsu_resyncs = pmcounter[SPEC_LSU_RESYNCS];
    assign pmcounterss[0].data.total_flushes = pmcounter[TOTAL_FLUSHES];
    assign pmcounterss[0].data.uops_decoded = pmcounter[UOPS_DECODED];
    assign pmcounterss[0].data.l1i_read_access = pmcounter[L1I_READ_ACCESS];
    assign pmcounterss[0].data.l1i_read_miss = pmcounter[L1I_READ_MISS];
    assign pmcounterss[0].data.l1i_prefetch_access = pmcounter[L1I_PREFETCH_ACCESS];
    assign pmcounterss[0].data.l1i_prefetch_miss = pmcounter[L1I_PREFETCH_MISS];
    assign pmcounterss[0].data.itlb_read_access = pmcounter[ITLB_READ_ACCESS];
    assign pmcounterss[0].data.itlb_read_miss = pmcounter[ITLB_READ_MISS];
    assign pmcounterss[0].data.itlb_prefetch_access = pmcounter[ITLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.itlb_prefetch_miss = pmcounter[ITLB_PREFETCH_MISS];
    assign pmcounterss[0].data.ic_way_mispred = pmcounter[IC_WAY_MISPRED];
    assign pmcounterss[0].data.ras_underflow = pmcounter[RAS_UNDERFLOW];
    assign pmcounterss[0].data.ras_overflow = pmcounter[RAS_OVERFLOW];
    assign pmcounterss[0].data.num_fetchgroups = pmcounter[NUM_FETCHGROUPS];
    assign pmcounterss[0].data.bdp_bank_conflicts = pmcounter[BDP_BANK_CONFLICTS];
    assign pmcounterss[0].data.btp_bank_conflicts = pmcounter[BTP_BANK_CONFLICTS];
    assign pmcounterss[0].data.bpu_writes = pmcounter[BPU_WRITES];
    assign pmcounterss[0].data.stalled_cycles_frontend = pmcounter[STALLED_CYCLES_FRONTEND];
    assign pmcounterss[0].data.stalled_cycles_backend = pmcounter[STALLED_CYCLES_BACKEND];
    assign pmcounterss[0].data.cycles_no_int_prn = pmcounter[CYCLES_NO_INT_PRN];
    assign pmcounterss[0].data.cycles_no_fp_prn = pmcounter[CYCLES_NO_FP_PRN];
    assign pmcounterss[0].data.cycles_no_vec_prn = pmcounter[CYCLES_NO_VEC_PRN];
    assign pmcounterss[0].data.cycles_no_vl_prn = pmcounter[CYCLES_NO_VL_PRN];
    assign pmcounterss[0].data.cycles_no_vm_prn = pmcounter[CYCLES_NO_VM_PRN];
    assign pmcounterss[0].data.cycles_no_rob = pmcounter[CYCLES_NO_ROB];
    assign pmcounterss[0].data.op_retired_direct_branch = pmcounter[OP_RETIRED_DIRECT_BRANCH];
    assign pmcounterss[0].data.op_retired_ret_branch = pmcounter[OP_RETIRED_RET_BRANCH];
    assign pmcounterss[0].data.op_retired_indirect_branch = pmcounter[OP_RETIRED_INDIRECT_BRANCH];
    assign pmcounterss[0].data.op_retired_cond_branch = pmcounter[OP_RETIRED_COND_BRANCH];
    assign pmcounterss[0].data.op_retired_ld = pmcounter[OP_RETIRED_LD];
    assign pmcounterss[0].data.op_retired_st = pmcounter[OP_RETIRED_ST];
    assign pmcounterss[0].data.op_retired_int = pmcounter[OP_RETIRED_INT];
    assign pmcounterss[0].data.op_retired_csr = pmcounter[OP_RETIRED_CSR];
    assign pmcounterss[0].data.op_retired_fp = pmcounter[OP_RETIRED_FP];
    assign pmcounterss[0].data.op_retired_vec = pmcounter[OP_RETIRED_VEC];
    assign pmcounterss[0].data.op_complete_ld = pmcounter[OP_COMPLETE_LD];
    assign pmcounterss[0].data.op_complete_st = pmcounter[OP_COMPLETE_ST];
    assign pmcounterss[0].data.op_complete_int = pmcounter[OP_COMPLETE_INT];
    assign pmcounterss[0].data.op_complete_fp = pmcounter[OP_COMPLETE_FP];
    assign pmcounterss[0].data.op_complete_vec = pmcounter[OP_COMPLETE_VEC];
    assign pmcounterss[0].data.op_issued_pipe0 = pmcounter[OP_ISSUED_PIPE0];
    assign pmcounterss[0].data.op_issued_pipe1 = pmcounter[OP_ISSUED_PIPE1];
    assign pmcounterss[0].data.op_issued_pipe2 = pmcounter[OP_ISSUED_PIPE2];
    assign pmcounterss[0].data.op_issued_pipe3 = pmcounter[OP_ISSUED_PIPE3];
    assign pmcounterss[0].data.op_issued_pipe4 = pmcounter[OP_ISSUED_PIPE4];
    assign pmcounterss[0].data.op_issued_pipe5 = pmcounter[OP_ISSUED_PIPE5];
    assign pmcounterss[0].data.op_issued_pipe6 = pmcounter[OP_ISSUED_PIPE6];
    assign pmcounterss[0].data.op_issued_pipe7 = pmcounter[OP_ISSUED_PIPE7];
    assign pmcounterss[0].data.op_issued_pipe8 = pmcounter[OP_ISSUED_PIPE8];
    assign pmcounterss[0].data.op_issued_pipe9 = pmcounter[OP_ISSUED_PIPE9];
    assign pmcounterss[0].data.op_issued_pipe10 = pmcounter[OP_ISSUED_PIPE10];
    assign pmcounterss[0].data.op_issued_pipe11 = pmcounter[OP_ISSUED_PIPE11];
    assign pmcounterss[0].data.op_issued_pipe12 = pmcounter[OP_ISSUED_PIPE12];
    assign pmcounterss[0].data.op_issued_pipe13 = pmcounter[OP_ISSUED_PIPE13];
    assign pmcounterss[0].data.op_issued_pipe14 = pmcounter[OP_ISSUED_PIPE14];
    assign pmcounterss[0].data.op_issued_pipe15 = pmcounter[OP_ISSUED_PIPE15];
    assign pmcounterss[0].data.cache_references = pmcounter[CACHE_REFERENCES];
    assign pmcounterss[0].data.cache_misses = pmcounter[CACHE_MISSES];
    assign pmcounterss[0].data.tlb_invalidates = pmcounter[TLB_INVALIDATES];
    assign pmcounterss[0].data.l1d_read_access_aligned = pmcounter[L1D_READ_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_read_access_clc = pmcounter[L1D_READ_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_read_access_4kx = pmcounter[L1D_READ_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_read_access_all = pmcounter[L1D_READ_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_write_access_aligned = pmcounter[L1D_WRITE_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_write_access_clc = pmcounter[L1D_WRITE_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_write_access_4kx = pmcounter[L1D_WRITE_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_write_access_all = pmcounter[L1D_WRITE_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_prefetch_access_aligned = pmcounter[L1D_PREFETCH_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_prefetch_access_clc = pmcounter[L1D_PREFETCH_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_prefetch_access_4kx = pmcounter[L1D_PREFETCH_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_prefetch_access_all = pmcounter[L1D_PREFETCH_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_mmu_access = pmcounter[L1D_MMU_ACCESS];
    assign pmcounterss[0].data.l1d_snoop_access = pmcounter[L1D_SNOOP_ACCESS];
    assign pmcounterss[0].data.l1d_access_all = pmcounter[L1D_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_read_miss = pmcounter[L1D_READ_MISS];
    assign pmcounterss[0].data.l1d_write_miss = pmcounter[L1D_WRITE_MISS];
    assign pmcounterss[0].data.l1d_prefetch_miss = pmcounter[L1D_PREFETCH_MISS];
    assign pmcounterss[0].data.l1d_mmu_miss = pmcounter[L1D_MMU_MISS];
    assign pmcounterss[0].data.l1d_snoop_miss = pmcounter[L1D_SNOOP_MISS];
    assign pmcounterss[0].data.l1d_miss_all = pmcounter[L1D_MISS_ALL];
    assign pmcounterss[0].data.l1d_cache_invalidate_snoop = pmcounter[L1D_CACHE_INVALIDATE_SNOOP];
    assign pmcounterss[0].data.l1d_cache_invalidate_cmo = pmcounter[L1D_CACHE_INVALIDATE_CMO];
    assign pmcounterss[0].data.l1d_cache_invalidate_load_eviction = pmcounter[L1D_CACHE_INVALIDATE_LOAD_EVICTION];
    assign pmcounterss[0].data.l1d_cache_invalidate_store_eviction = pmcounter[L1D_CACHE_INVALIDATE_STORE_EVICTION];
    assign pmcounterss[0].data.l1d_cache_invalidate_prefetch_eviction = pmcounter[L1D_CACHE_INVALIDATE_PREFETCH_EVICTION];
    assign pmcounterss[0].data.l1d_cache_invalidate_all = pmcounter[L1D_CACHE_INVALIDATE_ALL];
    assign pmcounterss[0].data.utlb_miss = pmcounter[UTLB_MISS];
    assign pmcounterss[0].data.dtlb_read_access = pmcounter[DTLB_READ_ACCESS];
    assign pmcounterss[0].data.dtlb_write_access = pmcounter[DTLB_WRITE_ACCESS];
    assign pmcounterss[0].data.dtlb_prefetch_access = pmcounter[DTLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.dtlb_access_4k = pmcounter[DTLB_ACCESS_4K];
    assign pmcounterss[0].data.dtlb_access_hugepage = pmcounter[DTLB_ACCESS_HUGEPAGE];
    assign pmcounterss[0].data.dtlb_access_cacheable = pmcounter[DTLB_ACCESS_CACHEABLE];
    assign pmcounterss[0].data.dtlb_access_noncacheable = pmcounter[DTLB_ACCESS_NONCACHEABLE];
    assign pmcounterss[0].data.dtlb_access_all = pmcounter[DTLB_ACCESS_ALL];
    assign pmcounterss[0].data.dtlb_read_miss = pmcounter[DTLB_READ_MISS];
    assign pmcounterss[0].data.dtlb_write_miss = pmcounter[DTLB_WRITE_MISS];
    assign pmcounterss[0].data.dtlb_prefetch_miss = pmcounter[DTLB_PREFETCH_MISS];
    assign pmcounterss[0].data.dtlb_miss_4k = pmcounter[DTLB_MISS_4K];
    assign pmcounterss[0].data.dtlb_miss_hugepage = pmcounter[DTLB_MISS_HUGEPAGE];
    assign pmcounterss[0].data.dtlb_miss_all = pmcounter[DTLB_MISS_ALL];
    assign pmcounterss[0].data.leaf_tlb_access_ls = pmcounter[LEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.leaf_tlb_access_fe = pmcounter[LEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.leaf_tlb_access_prefetch = pmcounter[LEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.leaf_tlb_access_all = pmcounter[LEAF_TLB_ACCESS_ALL];
    assign pmcounterss[0].data.leaf_tlb_miss_ls = pmcounter[LEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.leaf_tlb_miss_fe = pmcounter[LEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.leaf_tlb_miss_prefetch = pmcounter[LEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.leaf_tlb_miss_all = pmcounter[LEAF_TLB_MISS_ALL];
    assign pmcounterss[0].data.nonleaf_tlb_access_ls = pmcounter[NONLEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.nonleaf_tlb_access_fe = pmcounter[NONLEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.nonleaf_tlb_access_prefetch = pmcounter[NONLEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.nonleaf_tlb_access_all = pmcounter[NONLEAF_TLB_ACCESS_ALL];
    assign pmcounterss[0].data.nonleaf_tlb_miss_ls = pmcounter[NONLEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.nonleaf_tlb_miss_fe = pmcounter[NONLEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.nonleaf_tlb_miss_prefetch = pmcounter[NONLEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.nonleaf_tlb_miss_all = pmcounter[NONLEAF_TLB_MISS_ALL];
    assign pmcounterss[0].data.page_walks = pmcounter[PAGE_WALKS];
    assign pmcounterss[0].data.stalls_mem_l1d_miss = pmcounter[STALLS_MEM_L1D_MISS];
    assign pmcounterss[0].data.stalls_mem_stores = pmcounter[STALLS_MEM_STORES];
    assign pmcounterss[0].data.stalls_mem_l1dtlb_miss = pmcounter[STALLS_MEM_L1DTLB_MISS];
    assign pmcounterss[0].data.lsu_resyncs_raw = pmcounter[LSU_RESYNCS_RAW];
    assign pmcounterss[0].data.lsu_resyncs_rar = pmcounter[LSU_RESYNCS_RAR];
    assign pmcounterss[0].data.stlf_hits = pmcounter[STLF_HITS];
    assign pmcounterss[0].data.ls_replay_load = pmcounter[LS_REPLAY_LOAD];
    assign pmcounterss[0].data.ls_replay_store = pmcounter[LS_REPLAY_STORE];
    assign pmcounterss[0].data.ls_replay_prefetch = pmcounter[LS_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ls_replay_mmu = pmcounter[LS_REPLAY_MMU];
    assign pmcounterss[0].data.ls_replay_all = pmcounter[LS_REPLAY_ALL];
    assign pmcounterss[0].data.ls_way_predictor_replay_load = pmcounter[LS_WAY_PREDICTOR_REPLAY_LOAD];
    assign pmcounterss[0].data.ls_way_predictor_replay_store = pmcounter[LS_WAY_PREDICTOR_REPLAY_STORE];
    assign pmcounterss[0].data.ls_way_predictor_replay_prefetch = pmcounter[LS_WAY_PREDICTOR_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ls_way_predictor_replay_mmu = pmcounter[LS_WAY_PREDICTOR_REPLAY_MMU];
    assign pmcounterss[0].data.ls_way_predictor_replay_all = pmcounter[LS_WAY_PREDICTOR_REPLAY_ALL];
    assign pmcounterss[0].data.sipt_replay_load = pmcounter[SIPT_REPLAY_LOAD];
    assign pmcounterss[0].data.sipt_replay_store = pmcounter[SIPT_REPLAY_STORE];
    assign pmcounterss[0].data.sipt_replay_prefetch = pmcounter[SIPT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.sipt_replay_mmu = pmcounter[SIPT_REPLAY_MMU];
    assign pmcounterss[0].data.sipt_replay_all = pmcounter[SIPT_REPLAY_ALL];
    assign pmcounterss[0].data.stlf_replay_load = pmcounter[STLF_REPLAY_LOAD];
    assign pmcounterss[0].data.stlf_replay_mmu = pmcounter[STLF_REPLAY_MMU];
    assign pmcounterss[0].data.stlf_replay_all = pmcounter[STLF_REPLAY_ALL];
    assign pmcounterss[0].data.tag_bank_conflict_replay_load = pmcounter[TAG_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.tag_bank_conflict_replay_store = pmcounter[TAG_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.tag_bank_conflict_replay_prefetch = pmcounter[TAG_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.tag_bank_conflict_replay_mmu = pmcounter[TAG_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.tag_bank_conflict_replay_all = pmcounter[TAG_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.data_bank_conflict_replay_load = pmcounter[DATA_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.data_bank_conflict_replay_store = pmcounter[DATA_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.data_bank_conflict_replay_prefetch = pmcounter[DATA_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.data_bank_conflict_replay_mmu = pmcounter[DATA_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.data_bank_conflict_replay_all = pmcounter[DATA_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.fillbuf_hit_replay_load = pmcounter[FILLBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.fillbuf_hit_replay_store = pmcounter[FILLBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.fillbuf_hit_replay_mmu = pmcounter[FILLBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.fillbuf_hit_replay_all = pmcounter[FILLBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.transbuf_hit_replay_load = pmcounter[TRANSBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.transbuf_hit_replay_store = pmcounter[TRANSBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.transbuf_hit_replay_prefetch = pmcounter[TRANSBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.transbuf_hit_replay_mmu = pmcounter[TRANSBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.transbuf_hit_replay_all = pmcounter[TRANSBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.reqbuf_hit_replay_load = pmcounter[REQBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.reqbuf_hit_replay_store = pmcounter[REQBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.reqbuf_hit_replay_mmu = pmcounter[REQBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.reqbuf_hit_replay_all = pmcounter[REQBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.dtlb_replay_load = pmcounter[DTLB_REPLAY_LOAD];
    assign pmcounterss[0].data.dtlb_replay_store = pmcounter[DTLB_REPLAY_STORE];
    assign pmcounterss[0].data.dtlb_replay_prefetch = pmcounter[DTLB_REPLAY_PREFETCH];
    assign pmcounterss[0].data.dtlb_replay_mmu = pmcounter[DTLB_REPLAY_MMU];
    assign pmcounterss[0].data.dtlb_replay_all = pmcounter[DTLB_REPLAY_ALL];
    assign pmcounterss[0].data.rar_cannot_alloc = pmcounter[RAR_CANNOT_ALLOC];
    assign pmcounterss[0].data.raw_cannot_alloc = pmcounter[RAW_CANNOT_ALLOC];
    assign pmcounterss[0].data.ldq_cannot_alloc = pmcounter[LDQ_CANNOT_ALLOC];
    assign pmcounterss[0].data.smb_cannot_alloc = pmcounter[SMB_CANNOT_ALLOC];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_load = pmcounter[REQBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_store = pmcounter[REQBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_prefetch = pmcounter[REQBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_mmu = pmcounter[REQBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_all = pmcounter[REQBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.fillbuf_cannot_alloc = pmcounter[FILLBUF_CANNOT_ALLOC];
    assign pmcounterss[0].data.transbuf_cannot_alloc_load = pmcounter[TRANSBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.transbuf_cannot_alloc_store = pmcounter[TRANSBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.transbuf_cannot_alloc_prefetch = pmcounter[TRANSBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.transbuf_cannot_alloc_mmu = pmcounter[TRANSBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.transbuf_cannot_alloc_all = pmcounter[TRANSBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.pcb_cannot_alloc_load = pmcounter[PCB_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.pcb_cannot_alloc_store = pmcounter[PCB_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.pcb_cannot_alloc_all = pmcounter[PCB_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.udb_cannot_alloc = pmcounter[UDB_CANNOT_ALLOC];
    assign pmcounterss[0].data.udb_data_return = pmcounter[UDB_DATA_RETURN];
    assign pmcounterss[0].data.udb_lost = pmcounter[UDB_LOST];
    assign pmcounterss[0].data.uwp_access = pmcounter[UWP_ACCESS];
    assign pmcounterss[0].data.uwp_miss = pmcounter[UWP_MISS];
    assign pmcounterss[0].data.uwp_true_hit = pmcounter[UWP_TRUE_HIT];
    assign pmcounterss[0].data.wp_access = pmcounter[WP_ACCESS];
    assign pmcounterss[0].data.wp_miss = pmcounter[WP_MISS];
    assign pmcounterss[0].data.wp_true_hit = pmcounter[WP_TRUE_HIT];
    assign pmcounterss[0].data.mdp_correct_prediction = pmcounter[MDP_CORRECT_PREDICTION];
    assign pmcounterss[0].data.mdp_false_hit = pmcounter[MDP_FALSE_HIT];
    assign pmcounterss[0].data.mdp_false_miss = pmcounter[MDP_FALSE_MISS];
    assign pmcounterss[0].data.mdp_total_prediction = pmcounter[MDP_TOTAL_PREDICTION];
    assign pmcounterss[0].data.atomics_retired = pmcounter[ATOMICS_RETIRED];
    assign pmcounterss[0].data.ldst_masked_nano = pmcounter[LDST_MASKED_NANO];
    assign pmcounterss[0].data.ld_executed_nano = pmcounter[LD_EXECUTED_NANO];
    assign pmcounterss[0].data.st_executed_nano = pmcounter[ST_EXECUTED_NANO];
    assign pmcounterss[0].data.pfc_agt_cannot_alloc = pmcounter[PFC_AGT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_agt_evict = pmcounter[PFC_AGT_EVICT];
    assign pmcounterss[0].data.pfc_pht_cannot_alloc = pmcounter[PFC_PHT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_pht_lookup = pmcounter[PFC_PHT_LOOKUP];
    assign pmcounterss[0].data.pfc_pht_hit = pmcounter[PFC_PHT_HIT];
    assign pmcounterss[0].data.pfc_prt_cannot_alloc = pmcounter[PFC_PRT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_no_tlb_credit_stalls = pmcounter[PFC_NO_TLB_CREDIT_STALLS];
    assign pmcounterss[0].data.pfc_no_tag_credit_stalls = pmcounter[PFC_NO_TAG_CREDIT_STALLS];
    assign pmcounterss[0].data.pfc_prefetches_sent = pmcounter[PFC_PREFETCHES_SENT];
    assign pmcounterss[0].data.pfc_prefetches_hit = pmcounter[PFC_PREFETCHES_HIT];
    assign pmcounterss[0].data.pfc_prefetches_late = pmcounter[PFC_PREFETCHES_LATE];
    assign pmcounterss[0].data.pfc_useless_prefetches = pmcounter[PFC_USELESS_PREFETCHES];
    assign pmcounterss[0].data.sc_cache_access = sc_pmcounter[SC_CACHE_ACCESS];
    assign pmcounterss[0].data.sc_cache_rd = sc_pmcounter[SC_CACHE_RD];
    assign pmcounterss[0].data.sc_cache_miss = sc_pmcounter[SC_CACHE_MISS];
    assign pmcounterss[0].data.sc_cache_miss_rd = sc_pmcounter[SC_CACHE_MISS_RD];
    assign pmcounterss[0].data.sc_cache_refill = sc_pmcounter[SC_CACHE_REFILL];
    assign pmcounterss[0].data.sc_cache_allocate = sc_pmcounter[SC_CACHE_ALLOCATE];
    assign pmcounterss[0].data.sc_cache_wb_dirty = sc_pmcounter[SC_CACHE_WB_DIRTY];
    assign pmcounterss[0].data.sc_cache_wb_clean = sc_pmcounter[SC_CACHE_WB_CLEAN];
    assign pmcounterss[0].data.sc_cache_inval = sc_pmcounter[SC_CACHE_INVAL];
    assign pmcounterss[0].data.sc_snoop = sc_pmcounter[SC_SNOOP];
    assign pmcounterss[0].data.sc_scratchpad_rd = sc_pmcounter[SC_SCRATCHPAD_RD];
    assign pmcounterss[0].data.sc_scratchpad_wr = sc_pmcounter[SC_SCRATCHPAD_WR];
    assign pmcounterss[0].data.f2sc_rd = sc_pmcounter[F2SC_RD];
    assign pmcounterss[0].data.f2sc_wr = sc_pmcounter[F2SC_WR];
    assign pmcounterss[0].data.mshr_lifetime = sc_pmcounter[MSHR_LIFETIME];
    assign pmcounterss[0].data.mshr_allocations = sc_pmcounter[MSHR_ALLOCATIONS];
    assign pmcounterss[0].data.sc2f_rd_u = sc_pmcounter[SC2F_RD_U];
    assign pmcounterss[0].data.sc2f_rd_c = sc_pmcounter[SC2F_RD_C];
    assign pmcounterss[0].data.sc2f_rd_o = sc_pmcounter[SC2F_RD_O];
    assign pmcounterss[0].data.sc2f_wr = sc_pmcounter[SC2F_WR];
    assign pmcounterss[0].data.c2sc_rd_i = sc_pmcounter[C2SC_RD_I];
    assign pmcounterss[0].data.c2sc_rd_d = sc_pmcounter[C2SC_RD_D];
    assign pmcounterss[0].data.c2sc_wb_full = sc_pmcounter[C2SC_WB_FULL];
    assign pmcounterss[0].data.c2sc_evict = sc_pmcounter[C2SC_EVICT];
    assign pmcounterss[0].data.c2sc_snp_wb_full = sc_pmcounter[C2SC_SNP_WB_FULL];
    assign pmcounterss[0].data.c2sc_wrnosnpptl = sc_pmcounter[C2SC_WRNOSNPPTL];
    assign pmcounterss[0].data.c2sc_snp = sc_pmcounter[C2SC_SNP];
    assign pmcounterss[0].data.c2sc_req_stall = sc_pmcounter[C2SC_REQ_STALL];
    assign pmcounterss[0].data.c2sc_wdat_stall = sc_pmcounter[C2SC_WDAT_STALL];
    assign pmcounterss[0].data.c2sc_srsp_stall = sc_pmcounter[C2SC_SRSP_STALL];
    assign pmcounterss[0].data.c2sc_rdat_stall = sc_pmcounter[C2SC_RDAT_STALL];
    assign pmcounterss[0].data.c2sc_snp_stall = sc_pmcounter[C2SC_SNP_STALL];
    assign pmcounterss[0].data.c2sc_crsp_stall = sc_pmcounter[C2SC_CRSP_STALL];
    assign pmcounterss[0].data.sc2f_evict = sc_pmcounter[SC2F_EVICT];
    assign pmcounterss[0].data.sc2f_wrbackfull = sc_pmcounter[SC2F_WRBACKFULL];
    assign pmcounterss[0].data.sc2f_wdat = sc_pmcounter[SC2F_WDAT];
    assign pmcounterss[0].data.sc2f_snoop = sc_pmcounter[SC2F_SNOOP];
    assign pmcounterss[0].data.sc2f_rdat = sc_pmcounter[SC2F_RDAT];
    assign pmcounterss[0].data.sc2f_req_stall = sc_pmcounter[SC2F_REQ_STALL];
    assign pmcounterss[0].data.sc2f_wdat_stall = sc_pmcounter[SC2F_WDAT_STALL];
    assign pmcounterss[0].data.sc2f_srsp_stall = sc_pmcounter[SC2F_SRSP_STALL];
    assign pmcounterss[0].data.sc2f_rdat_stall = sc_pmcounter[SC2F_RDAT_STALL];
    assign pmcounterss[0].data.sc2f_snoop_stall = sc_pmcounter[SC2F_SNOOP_STALL];
    assign pmcounterss[0].data.sc2f_crsp_stall = sc_pmcounter[SC2F_CRSP_STALL];
    assign pmcounterss[0].data.f2sc_wdat = sc_pmcounter[F2SC_WDAT];
    assign pmcounterss[0].data.f2sc_rdat = sc_pmcounter[F2SC_RDAT];
    assign pmcounterss[0].data.f2sc_wrnosnpptl = sc_pmcounter[F2SC_WRNOSNPPTL];
    assign pmcounterss[0].data.f2sc_req_stall = sc_pmcounter[F2SC_REQ_STALL];
    assign pmcounterss[0].data.f2sc_wdat_stall = sc_pmcounter[F2SC_WDAT_STALL];
    assign pmcounterss[0].data.f2sc_rdat_stall = sc_pmcounter[F2SC_RDAT_STALL];
    assign pmcounterss[0].data.f2sc_crsp_stall = sc_pmcounter[F2SC_CRSP_STALL];
    assign pmcounterss[0].data.sc_tag_lookup = sc_pmcounter[SC_TAG_LOOKUP];
    assign pmcounterss[0].data.sc_tag_write = sc_pmcounter[SC_TAG_WRITE];
    assign pmcounterss[0].data.sc_state_write = sc_pmcounter[SC_STATE_WRITE];
    assign pmcounterss[0].data.sc_repl_write = sc_pmcounter[SC_REPL_WRITE];
    assign pmcounterss[0].data.sc_tag_hit = sc_pmcounter[SC_TAG_HIT];
    assign pmcounterss[0].data.sc_data_read = sc_pmcounter[SC_DATA_READ];
    assign pmcounterss[0].data.sc_data_write = sc_pmcounter[SC_DATA_WRITE];
    assign pmcounterss[0].data.sc_state_i2e = sc_pmcounter[SC_STATE_I2E];
    assign pmcounterss[0].data.sc_state_i2m = sc_pmcounter[SC_STATE_I2M];
    assign pmcounterss[0].data.sc_state_i2s = sc_pmcounter[SC_STATE_I2S];
    assign pmcounterss[0].data.sc_state_s2i = sc_pmcounter[SC_STATE_S2I];
    assign pmcounterss[0].data.sc_state_s2m = sc_pmcounter[SC_STATE_S2M];
    assign pmcounterss[0].data.sc_state_s2e = sc_pmcounter[SC_STATE_S2E];
    assign pmcounterss[0].data.sc_state_m2i = sc_pmcounter[SC_STATE_M2I];
    assign pmcounterss[0].data.sc_state_m2s = sc_pmcounter[SC_STATE_M2S];
    assign pmcounterss[0].data.sc_state_m2e = sc_pmcounter[SC_STATE_M2E];
    assign pmcounterss[0].data.sc_state_e2i = sc_pmcounter[SC_STATE_E2I];
    assign pmcounterss[0].data.sc_state_e2s = sc_pmcounter[SC_STATE_E2S];
    assign pmcounterss[0].data.sc_state_e2m = sc_pmcounter[SC_STATE_E2M];
    assign pmcounterss[0].data.sft_lookup = sc_pmcounter[SFT_LOOKUP];
    assign pmcounterss[0].data.sft_hit = sc_pmcounter[SFT_HIT];
    assign pmcounterss[0].data.sft_write = sc_pmcounter[SFT_WRITE];
    assign pmcounterss[0].data.sft_eviction = sc_pmcounter[SFT_EVICTION];
    assign pmcounterss[0].data.sft_snp_single_icache = sc_pmcounter[SFT_SNP_SINGLE_ICACHE];
    assign pmcounterss[0].data.sft_snp_single_dcache = sc_pmcounter[SFT_SNP_SINGLE_DCACHE];
    assign pmcounterss[0].data.sft_snp_multi_cores = sc_pmcounter[SFT_SNP_MULTI_CORES];
    assign pmcounterss[0].data.sft_eviction_replay = sc_pmcounter[SFT_EVICTION_REPLAY];
    assign pmcounterss[0].data.mshr_occupancy = sc_pmcounter[MSHR_OCCUPANCY];
    assign pmcounterss[0].data.mshr_full = sc_pmcounter[MSHR_FULL];
    assign pmcounterss[0].data.mshr_saq_alloc = sc_pmcounter[MSHR_SAQ_ALLOC];
    assign pmcounterss[0].data.mshr_saq_full = sc_pmcounter[MSHR_SAQ_FULL];
    assign pmcounterss[0].data.no_alloc_no_mshr = sc_pmcounter[NO_ALLOC_NO_MSHR];
    assign pmcounterss[0].data.no_alloc_hint_not_set = sc_pmcounter[NO_ALLOC_HINT_NOT_SET];
    assign pmcounterss[0].data.sc_replay_ecc = sc_pmcounter[SC_REPLAY_ECC];

endmodule

module pmu_ema #(parameter WIDTH=8, // Width of Reported Value / Activity
                 parameter DECAY=8) // Width of extra decay bits, total size = WIDTH+DECAY
(
  input              i_clk,
  input              i_reset_n,
  input              i_en,
  input [WIDTH-1:0]  i_activity, // new activity to add in
  input [WIDTH-1:0]  i_decayadj, // decay rate adjustment in powers of 2, tie to 0 if unneeded
  output [WIDTH-1:0] o_activity, // Ema Current Value
  output             o_busy // Ema is non-zero
);

   localparam EMA_SIZE = WIDTH+DECAY;
   logic [EMA_SIZE-1:0] NxtEma;
   logic [EMA_SIZE-1:0] Ema;

   // Old Value + New Activity - OldValue Decayed
   assign NxtEma[EMA_SIZE-1:0]
     = Ema[EMA_SIZE-1:0] +
       ({{DECAY{1'b0}},i_activity[WIDTH-1:0]} << i_decayadj[WIDTH-1:0]) -
       ({{DECAY{1'b0}},Ema[WIDTH+DECAY-1:DECAY+1],        // upper bits
         Ema[DECAY] |                                     // bit 0 of upper
         ~(|Ema[WIDTH+DECAY-1:DECAY]) & (|Ema[DECAY-1:0]) // no upper bits, decay lower bits rounded up
         } << i_decayadj[WIDTH-1:0]);

   always_ff @(posedge i_clk)
     if (~i_reset_n)
       Ema[EMA_SIZE-1:0] <= {EMA_SIZE{1'b0}};
     else if (i_en)
       Ema[EMA_SIZE-1:0] <= NxtEma[EMA_SIZE-1:0];

   assign o_activity[WIDTH-1:0] = Ema[WIDTH+DECAY-1:DECAY];
   assign o_busy = |Ema;

endmodule
