module pmu
import rv_tester_params::*;
#(
  parameter int NUM = -1,
  parameter int NRET = 1,
  `TOPOLOGY,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PARAMS
)(
  input tb_clk,
  input clk,
  input reset,
  input longint unsigned clocks,
  input pmci_t pmci,
  input rvfi_t [NRET-1:0] rvfi,
  input bit terminate,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PORTS
);

    int unsigned location = cvm_topology::nil;
    longint unsigned period = 0;
    bit sync;
    assign sync = period != '0;
    bit perf_enabled = '0;
    bit perf_start = '0;
    bit perf_end = '0;
    logic ptc_strobe;

    always @(posedge tb_clk) begin
        if (reset) begin
            /* verilator lint_off BLKSEQ */
            location = cvm_topology::get_location(topology.TOP.PLATFORM.PMCI.ID, NUM);
            perf_enabled = (cvm_plusargs::get_bool("perf") != '0) & (location != cvm_topology::nil);
            period = cvm_plusargs::get_ulongint("sync_pmcounters_period");
            /* verilator lint_on BLKSEQ */
        end
    end

    longint unsigned cpu_cycles = 0;
    longint unsigned pmcounter [EVENT_COUNT] = '{default:0};

    always @(posedge clk) begin
      if (reset) begin
        pmcounter[0] <= 0;
      end else begin
        cpu_cycles <= clocks;
      end
    end

    generate
      for (genvar i=1; i < EVENT_COUNT; i++) begin : pmci_regs
        always @(posedge clk) begin
            if (reset) begin
                pmcounter[i] <= 0;
            end else begin
                //NOTE: Hack to support verilator builds -- if EVENT_COUNT is greater than 64, verilator fails to build with Error-BLKLOOPINIT
                //Longer term fix would be adding a higher --unroll-count to verialator's CLI. no time for that on 9/12/2023, though
                pmcounter[i] <= pmcounter[i] + {60'h0, pmci[i]};
            end
        end
      end
    endgenerate

    bit [NRET-1:0] perf_match_array_start;
    bit [NRET-1:0] perf_match_array_end;
    always @(*) begin
      for (integer n = 0; n < NRET; n++) begin
        perf_match_array_start[n] = (rvfi[n].insn == 32'h00058013) && rvfi[n].valid;
        perf_match_array_end[n] = (rvfi[n].insn == 32'h00060013) && rvfi[n].valid;
      end

      perf_start = | perf_match_array_start;
      perf_end = | perf_match_array_end;
    end

   logic [9:0]                   ptc_count;
   logic [EVENT_COUNT-1:0][13:0] ptc_evt_count;
   logic [EVENT_COUNT-1:0][3:0]  evt_avg;
   always @(posedge clk) begin
      if (reset || perf_start || perf_end || ptc_strobe)
        ptc_count <= '0;
      else
        ptc_count <= ptc_count + 10'd1;
   end
   assign ptc_strobe = (ptc_count==10'd999) | perf_start | perf_end;

   generate
      for(genvar i=0; i<EVENT_COUNT; i++) begin : evt_logic
         logic [3:0] mod_pmci;

         assign mod_pmci = (pmci[i][0]===1'bx) ? 4'b0 : pmci[i];

         // 1000-cycle event count
         always @(posedge clk) begin
            if (reset)
              ptc_evt_count[i] <= '0;
            else
              ptc_evt_count[i] <= ({14{~ptc_strobe}} & ptc_evt_count[i]) + {10'b0,mod_pmci};
         end

         // 128-cycle moving average
         logic       ema_busy;
         logic       ema_en;

         assign ema_en   = |mod_pmci | ema_busy;

         pmu_ema #(.WIDTH(4), .DECAY(7))
         u_evt (.i_clk(clk), .i_reset_n(!reset), .i_en(ema_en),
                .i_activity(mod_pmci), .i_decayadj('0),
                .o_activity(evt_avg[i]), .o_busy(ema_busy));
      end
   endgenerate

    //AUTOGENERATED -- NO TOUCH
    assign pmcounterss[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0) || perf_start || perf_end || ptc_strobe);
    assign pmcounterss[0].data.location = location;
    assign pmcounterss[0].data.cpu_cycles = cpu_cycles;
    assign pmcounterss[0].data.instructions = pmcounter[INSTRUCTIONS];
    assign pmcounterss[0].data.perf_start = perf_start;
    assign pmcounterss[0].data.perf_end = perf_end;
    assign pmcounterss[0].data.ptc_strobe = ptc_strobe;
    assign pmcounterss[0].data.m_mode_cycles = pmcounter[M_MODE_CYCLES];
    assign pmcounterss[0].data.ptc_m_mode_cycles = ptc_evt_count[M_MODE_CYCLES];
    assign pmcounterss[0].data.m_mode_instret = pmcounter[M_MODE_INSTRET];
    assign pmcounterss[0].data.ptc_m_mode_instret = ptc_evt_count[M_MODE_INSTRET];
    assign pmcounterss[0].data.s_mode_cycles = pmcounter[S_MODE_CYCLES];
    assign pmcounterss[0].data.ptc_s_mode_cycles = ptc_evt_count[S_MODE_CYCLES];
    assign pmcounterss[0].data.s_mode_instret = pmcounter[S_MODE_INSTRET];
    assign pmcounterss[0].data.ptc_s_mode_instret = ptc_evt_count[S_MODE_INSTRET];
    assign pmcounterss[0].data.u_mode_cycles = pmcounter[U_MODE_CYCLES];
    assign pmcounterss[0].data.ptc_u_mode_cycles = ptc_evt_count[U_MODE_CYCLES];
    assign pmcounterss[0].data.u_mode_instret = pmcounter[U_MODE_INSTRET];
    assign pmcounterss[0].data.ptc_u_mode_instret = ptc_evt_count[U_MODE_INSTRET];
    assign pmcounterss[0].data.ref_cpu_cycles = pmcounter[REF_CPU_CYCLES];
    assign pmcounterss[0].data.ptc_ref_cpu_cycles = ptc_evt_count[REF_CPU_CYCLES];
    assign pmcounterss[0].data.stalls_bst_full = pmcounter[STALLS_BST_FULL];
    assign pmcounterss[0].data.ptc_stalls_bst_full = ptc_evt_count[STALLS_BST_FULL];
    assign pmcounterss[0].data.stalls_pfx_full = pmcounter[STALLS_PFX_FULL];
    assign pmcounterss[0].data.ptc_stalls_pfx_full = ptc_evt_count[STALLS_PFX_FULL];
    assign pmcounterss[0].data.stalls_indirect_miss = pmcounter[STALLS_INDIRECT_MISS];
    assign pmcounterss[0].data.ptc_stalls_indirect_miss = ptc_evt_count[STALLS_INDIRECT_MISS];
    assign pmcounterss[0].data.stalls_icache_miss = pmcounter[STALLS_ICACHE_MISS];
    assign pmcounterss[0].data.ptc_stalls_icache_miss = ptc_evt_count[STALLS_ICACHE_MISS];
    assign pmcounterss[0].data.stalls_itlb_miss = pmcounter[STALLS_ITLB_MISS];
    assign pmcounterss[0].data.ptc_stalls_itlb_miss = ptc_evt_count[STALLS_ITLB_MISS];
    assign pmcounterss[0].data.stalls_irb_full = pmcounter[STALLS_IRB_FULL];
    assign pmcounterss[0].data.ptc_stalls_irb_full = ptc_evt_count[STALLS_IRB_FULL];
    assign pmcounterss[0].data.stalls_ifbuf_full = pmcounter[STALLS_IFBUF_FULL];
    assign pmcounterss[0].data.ptc_stalls_ifbuf_full = ptc_evt_count[STALLS_IFBUF_FULL];
    assign pmcounterss[0].data.stalls_exception = pmcounter[STALLS_EXCEPTION];
    assign pmcounterss[0].data.ptc_stalls_exception = ptc_evt_count[STALLS_EXCEPTION];
    assign pmcounterss[0].data.page_crossing_fetchblocks = pmcounter[PAGE_CROSSING_FETCHBLOCKS];
    assign pmcounterss[0].data.ptc_page_crossing_fetchblocks = ptc_evt_count[PAGE_CROSSING_FETCHBLOCKS];
    assign pmcounterss[0].data.nfp_early_redirect = pmcounter[NFP_EARLY_REDIRECT];
    assign pmcounterss[0].data.ptc_nfp_early_redirect = ptc_evt_count[NFP_EARLY_REDIRECT];
    assign pmcounterss[0].data.nfp_late_redirect = pmcounter[NFP_LATE_REDIRECT];
    assign pmcounterss[0].data.ptc_nfp_late_redirect = ptc_evt_count[NFP_LATE_REDIRECT];
    assign pmcounterss[0].data.nonspec_resync = pmcounter[NONSPEC_RESYNC];
    assign pmcounterss[0].data.ptc_nonspec_resync = ptc_evt_count[NONSPEC_RESYNC];
    assign pmcounterss[0].data.fault_resync = pmcounter[FAULT_RESYNC];
    assign pmcounterss[0].data.ptc_fault_resync = ptc_evt_count[FAULT_RESYNC];
    assign pmcounterss[0].data.fault_refetch = pmcounter[FAULT_REFETCH];
    assign pmcounterss[0].data.ptc_fault_refetch = ptc_evt_count[FAULT_REFETCH];
    assign pmcounterss[0].data.cmode_entry = pmcounter[CMODE_ENTRY];
    assign pmcounterss[0].data.ptc_cmode_entry = ptc_evt_count[CMODE_ENTRY];
    assign pmcounterss[0].data.branch_misses = pmcounter[BRANCH_MISSES];
    assign pmcounterss[0].data.ptc_branch_misses = ptc_evt_count[BRANCH_MISSES];
    assign pmcounterss[0].data.br_ret_misses = pmcounter[BR_RET_MISSES];
    assign pmcounterss[0].data.ptc_br_ret_misses = ptc_evt_count[BR_RET_MISSES];
    assign pmcounterss[0].data.ind_br_misses = pmcounter[IND_BR_MISSES];
    assign pmcounterss[0].data.ptc_ind_br_misses = ptc_evt_count[IND_BR_MISSES];
    assign pmcounterss[0].data.rel_br_misses = pmcounter[REL_BR_MISSES];
    assign pmcounterss[0].data.ptc_rel_br_misses = ptc_evt_count[REL_BR_MISSES];
    assign pmcounterss[0].data.spec_branch_redirect = pmcounter[SPEC_BRANCH_REDIRECT];
    assign pmcounterss[0].data.ptc_spec_branch_redirect = ptc_evt_count[SPEC_BRANCH_REDIRECT];
    assign pmcounterss[0].data.spec_lsu_resyncs = pmcounter[SPEC_LSU_RESYNCS];
    assign pmcounterss[0].data.ptc_spec_lsu_resyncs = ptc_evt_count[SPEC_LSU_RESYNCS];
    assign pmcounterss[0].data.total_flushes = pmcounter[TOTAL_FLUSHES];
    assign pmcounterss[0].data.ptc_total_flushes = ptc_evt_count[TOTAL_FLUSHES];
    assign pmcounterss[0].data.uops_decoded = pmcounter[UOPS_DECODED];
    assign pmcounterss[0].data.ptc_uops_decoded = ptc_evt_count[UOPS_DECODED];
    assign pmcounterss[0].data.l1i_read_access = pmcounter[L1I_READ_ACCESS];
    assign pmcounterss[0].data.ptc_l1i_read_access = ptc_evt_count[L1I_READ_ACCESS];
    assign pmcounterss[0].data.l1i_read_miss = pmcounter[L1I_READ_MISS];
    assign pmcounterss[0].data.ptc_l1i_read_miss = ptc_evt_count[L1I_READ_MISS];
    assign pmcounterss[0].data.l1i_prefetch_access = pmcounter[L1I_PREFETCH_ACCESS];
    assign pmcounterss[0].data.ptc_l1i_prefetch_access = ptc_evt_count[L1I_PREFETCH_ACCESS];
    assign pmcounterss[0].data.l1i_prefetch_miss = pmcounter[L1I_PREFETCH_MISS];
    assign pmcounterss[0].data.ptc_l1i_prefetch_miss = ptc_evt_count[L1I_PREFETCH_MISS];
    assign pmcounterss[0].data.itlb_read_access = pmcounter[ITLB_READ_ACCESS];
    assign pmcounterss[0].data.ptc_itlb_read_access = ptc_evt_count[ITLB_READ_ACCESS];
    assign pmcounterss[0].data.itlb_read_miss = pmcounter[ITLB_READ_MISS];
    assign pmcounterss[0].data.ptc_itlb_read_miss = ptc_evt_count[ITLB_READ_MISS];
    assign pmcounterss[0].data.itlb_prefetch_access = pmcounter[ITLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.ptc_itlb_prefetch_access = ptc_evt_count[ITLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.itlb_prefetch_miss = pmcounter[ITLB_PREFETCH_MISS];
    assign pmcounterss[0].data.ptc_itlb_prefetch_miss = ptc_evt_count[ITLB_PREFETCH_MISS];
    assign pmcounterss[0].data.ic_way_mispred = pmcounter[IC_WAY_MISPRED];
    assign pmcounterss[0].data.ptc_ic_way_mispred = ptc_evt_count[IC_WAY_MISPRED];
    assign pmcounterss[0].data.ras_underflow = pmcounter[RAS_UNDERFLOW];
    assign pmcounterss[0].data.ptc_ras_underflow = ptc_evt_count[RAS_UNDERFLOW];
    assign pmcounterss[0].data.ras_overflow = pmcounter[RAS_OVERFLOW];
    assign pmcounterss[0].data.ptc_ras_overflow = ptc_evt_count[RAS_OVERFLOW];
    assign pmcounterss[0].data.num_fetchgroups = pmcounter[NUM_FETCHGROUPS];
    assign pmcounterss[0].data.ptc_num_fetchgroups = ptc_evt_count[NUM_FETCHGROUPS];
    assign pmcounterss[0].data.bdp_bank_conflicts = pmcounter[BDP_BANK_CONFLICTS];
    assign pmcounterss[0].data.ptc_bdp_bank_conflicts = ptc_evt_count[BDP_BANK_CONFLICTS];
    assign pmcounterss[0].data.btp_bank_conflicts = pmcounter[BTP_BANK_CONFLICTS];
    assign pmcounterss[0].data.ptc_btp_bank_conflicts = ptc_evt_count[BTP_BANK_CONFLICTS];
    assign pmcounterss[0].data.bpu_writes = pmcounter[BPU_WRITES];
    assign pmcounterss[0].data.ptc_bpu_writes = ptc_evt_count[BPU_WRITES];
    assign pmcounterss[0].data.stalled_cycles_frontend = pmcounter[STALLED_CYCLES_FRONTEND];
    assign pmcounterss[0].data.ptc_stalled_cycles_frontend = ptc_evt_count[STALLED_CYCLES_FRONTEND];
    assign pmcounterss[0].data.stalled_cycles_backend = pmcounter[STALLED_CYCLES_BACKEND];
    assign pmcounterss[0].data.ptc_stalled_cycles_backend = ptc_evt_count[STALLED_CYCLES_BACKEND];
    assign pmcounterss[0].data.cycles_no_int_prn = pmcounter[CYCLES_NO_INT_PRN];
    assign pmcounterss[0].data.ptc_cycles_no_int_prn = ptc_evt_count[CYCLES_NO_INT_PRN];
    assign pmcounterss[0].data.cycles_no_fp_prn = pmcounter[CYCLES_NO_FP_PRN];
    assign pmcounterss[0].data.ptc_cycles_no_fp_prn = ptc_evt_count[CYCLES_NO_FP_PRN];
    assign pmcounterss[0].data.cycles_no_vec_prn = pmcounter[CYCLES_NO_VEC_PRN];
    assign pmcounterss[0].data.ptc_cycles_no_vec_prn = ptc_evt_count[CYCLES_NO_VEC_PRN];
    assign pmcounterss[0].data.cycles_no_vl_prn = pmcounter[CYCLES_NO_VL_PRN];
    assign pmcounterss[0].data.ptc_cycles_no_vl_prn = ptc_evt_count[CYCLES_NO_VL_PRN];
    assign pmcounterss[0].data.cycles_no_vm_prn = pmcounter[CYCLES_NO_VM_PRN];
    assign pmcounterss[0].data.ptc_cycles_no_vm_prn = ptc_evt_count[CYCLES_NO_VM_PRN];
    assign pmcounterss[0].data.cycles_no_rob = pmcounter[CYCLES_NO_ROB];
    assign pmcounterss[0].data.ptc_cycles_no_rob = ptc_evt_count[CYCLES_NO_ROB];
    assign pmcounterss[0].data.branch_instructions = pmcounter[BRANCH_INSTRUCTIONS];
    assign pmcounterss[0].data.ptc_branch_instructions = ptc_evt_count[BRANCH_INSTRUCTIONS];
    assign pmcounterss[0].data.uop_retired = pmcounter[UOP_RETIRED];
    assign pmcounterss[0].data.ptc_uop_retired = ptc_evt_count[UOP_RETIRED];
    assign pmcounterss[0].data.ld_retired = pmcounter[LD_RETIRED];
    assign pmcounterss[0].data.ptc_ld_retired = ptc_evt_count[LD_RETIRED];
    assign pmcounterss[0].data.st_retired = pmcounter[ST_RETIRED];
    assign pmcounterss[0].data.ptc_st_retired = ptc_evt_count[ST_RETIRED];
    assign pmcounterss[0].data.int_retired = pmcounter[INT_RETIRED];
    assign pmcounterss[0].data.ptc_int_retired = ptc_evt_count[INT_RETIRED];
    assign pmcounterss[0].data.csr_retired = pmcounter[CSR_RETIRED];
    assign pmcounterss[0].data.ptc_csr_retired = ptc_evt_count[CSR_RETIRED];
    assign pmcounterss[0].data.br_ret_retired = pmcounter[BR_RET_RETIRED];
    assign pmcounterss[0].data.ptc_br_ret_retired = ptc_evt_count[BR_RET_RETIRED];
    assign pmcounterss[0].data.ind_br_retired = pmcounter[IND_BR_RETIRED];
    assign pmcounterss[0].data.ptc_ind_br_retired = ptc_evt_count[IND_BR_RETIRED];
    assign pmcounterss[0].data.rel_br_retired = pmcounter[REL_BR_RETIRED];
    assign pmcounterss[0].data.ptc_rel_br_retired = ptc_evt_count[REL_BR_RETIRED];
    assign pmcounterss[0].data.fp_retired = pmcounter[FP_RETIRED];
    assign pmcounterss[0].data.ptc_fp_retired = ptc_evt_count[FP_RETIRED];
    assign pmcounterss[0].data.vec_retired = pmcounter[VEC_RETIRED];
    assign pmcounterss[0].data.ptc_vec_retired = ptc_evt_count[VEC_RETIRED];
    assign pmcounterss[0].data.xfer_retired = pmcounter[XFER_RETIRED];
    assign pmcounterss[0].data.ptc_xfer_retired = ptc_evt_count[XFER_RETIRED];
    assign pmcounterss[0].data.uop_confirmed = pmcounter[UOP_CONFIRMED];
    assign pmcounterss[0].data.ptc_uop_confirmed = ptc_evt_count[UOP_CONFIRMED];
    assign pmcounterss[0].data.uop_issued_int = pmcounter[UOP_ISSUED_INT];
    assign pmcounterss[0].data.ptc_uop_issued_int = ptc_evt_count[UOP_ISSUED_INT];
    assign pmcounterss[0].data.uop_issued_ldst = pmcounter[UOP_ISSUED_LDST];
    assign pmcounterss[0].data.ptc_uop_issued_ldst = ptc_evt_count[UOP_ISSUED_LDST];
    assign pmcounterss[0].data.uop_issued_fp = pmcounter[UOP_ISSUED_FP];
    assign pmcounterss[0].data.ptc_uop_issued_fp = ptc_evt_count[UOP_ISSUED_FP];
    assign pmcounterss[0].data.uop_issued_vec = pmcounter[UOP_ISSUED_VEC];
    assign pmcounterss[0].data.ptc_uop_issued_vec = ptc_evt_count[UOP_ISSUED_VEC];
    assign pmcounterss[0].data.br_direct_spec = pmcounter[BR_DIRECT_SPEC];
    assign pmcounterss[0].data.ptc_br_direct_spec = ptc_evt_count[BR_DIRECT_SPEC];
    assign pmcounterss[0].data.br_indirect_spec = pmcounter[BR_INDIRECT_SPEC];
    assign pmcounterss[0].data.ptc_br_indirect_spec = ptc_evt_count[BR_INDIRECT_SPEC];
    assign pmcounterss[0].data.br_ret_spec = pmcounter[BR_RET_SPEC];
    assign pmcounterss[0].data.ptc_br_ret_spec = ptc_evt_count[BR_RET_SPEC];
    assign pmcounterss[0].data.int_executed = pmcounter[INT_EXECUTED];
    assign pmcounterss[0].data.ptc_int_executed = ptc_evt_count[INT_EXECUTED];
    assign pmcounterss[0].data.fp_executed = pmcounter[FP_EXECUTED];
    assign pmcounterss[0].data.ptc_fp_executed = ptc_evt_count[FP_EXECUTED];
    assign pmcounterss[0].data.vec_executed = pmcounter[VEC_EXECUTED];
    assign pmcounterss[0].data.ptc_vec_executed = ptc_evt_count[VEC_EXECUTED];
    assign pmcounterss[0].data.compressed_instret = pmcounter[COMPRESSED_INSTRET];
    assign pmcounterss[0].data.ptc_compressed_instret = ptc_evt_count[COMPRESSED_INSTRET];
    assign pmcounterss[0].data.cache_references = pmcounter[CACHE_REFERENCES];
    assign pmcounterss[0].data.ptc_cache_references = ptc_evt_count[CACHE_REFERENCES];
    assign pmcounterss[0].data.cache_misses = pmcounter[CACHE_MISSES];
    assign pmcounterss[0].data.ptc_cache_misses = ptc_evt_count[CACHE_MISSES];
    assign pmcounterss[0].data.tlb_invalidates = pmcounter[TLB_INVALIDATES];
    assign pmcounterss[0].data.ptc_tlb_invalidates = ptc_evt_count[TLB_INVALIDATES];
    assign pmcounterss[0].data.utlb_miss = pmcounter[UTLB_MISS];
    assign pmcounterss[0].data.ptc_utlb_miss = ptc_evt_count[UTLB_MISS];
    assign pmcounterss[0].data.nonleaf_tlb_access_fiter = pmcounter[NONLEAF_TLB_ACCESS_FITER];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_access_fiter = ptc_evt_count[NONLEAF_TLB_ACCESS_FITER];
    assign pmcounterss[0].data.page_walks = pmcounter[PAGE_WALKS];
    assign pmcounterss[0].data.ptc_page_walks = ptc_evt_count[PAGE_WALKS];
    assign pmcounterss[0].data.stalls_mem_l1d_miss = pmcounter[STALLS_MEM_L1D_MISS];
    assign pmcounterss[0].data.ptc_stalls_mem_l1d_miss = ptc_evt_count[STALLS_MEM_L1D_MISS];
    assign pmcounterss[0].data.stalls_mem_stores = pmcounter[STALLS_MEM_STORES];
    assign pmcounterss[0].data.ptc_stalls_mem_stores = ptc_evt_count[STALLS_MEM_STORES];
    assign pmcounterss[0].data.stalls_mem_l1dtlb_miss = pmcounter[STALLS_MEM_L1DTLB_MISS];
    assign pmcounterss[0].data.ptc_stalls_mem_l1dtlb_miss = ptc_evt_count[STALLS_MEM_L1DTLB_MISS];
    assign pmcounterss[0].data.stlf_hits = pmcounter[STLF_HITS];
    assign pmcounterss[0].data.ptc_stlf_hits = ptc_evt_count[STLF_HITS];
    assign pmcounterss[0].data.rar_cannot_alloc = pmcounter[RAR_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_rar_cannot_alloc = ptc_evt_count[RAR_CANNOT_ALLOC];
    assign pmcounterss[0].data.raw_cannot_alloc = pmcounter[RAW_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_raw_cannot_alloc = ptc_evt_count[RAW_CANNOT_ALLOC];
    assign pmcounterss[0].data.ldq_cannot_alloc = pmcounter[LDQ_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_ldq_cannot_alloc = ptc_evt_count[LDQ_CANNOT_ALLOC];
    assign pmcounterss[0].data.smb_cannot_alloc = pmcounter[SMB_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_smb_cannot_alloc = ptc_evt_count[SMB_CANNOT_ALLOC];
    assign pmcounterss[0].data.fillbuf_cannot_alloc = pmcounter[FILLBUF_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_fillbuf_cannot_alloc = ptc_evt_count[FILLBUF_CANNOT_ALLOC];
    assign pmcounterss[0].data.udb_cannot_alloc = pmcounter[UDB_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_udb_cannot_alloc = ptc_evt_count[UDB_CANNOT_ALLOC];
    assign pmcounterss[0].data.udb_data_return = pmcounter[UDB_DATA_RETURN];
    assign pmcounterss[0].data.ptc_udb_data_return = ptc_evt_count[UDB_DATA_RETURN];
    assign pmcounterss[0].data.udb_lost = pmcounter[UDB_LOST];
    assign pmcounterss[0].data.ptc_udb_lost = ptc_evt_count[UDB_LOST];
    assign pmcounterss[0].data.uwp_access = pmcounter[UWP_ACCESS];
    assign pmcounterss[0].data.ptc_uwp_access = ptc_evt_count[UWP_ACCESS];
    assign pmcounterss[0].data.uwp_miss = pmcounter[UWP_MISS];
    assign pmcounterss[0].data.ptc_uwp_miss = ptc_evt_count[UWP_MISS];
    assign pmcounterss[0].data.uwp_true_hit = pmcounter[UWP_TRUE_HIT];
    assign pmcounterss[0].data.ptc_uwp_true_hit = ptc_evt_count[UWP_TRUE_HIT];
    assign pmcounterss[0].data.wp_access = pmcounter[WP_ACCESS];
    assign pmcounterss[0].data.ptc_wp_access = ptc_evt_count[WP_ACCESS];
    assign pmcounterss[0].data.wp_miss = pmcounter[WP_MISS];
    assign pmcounterss[0].data.ptc_wp_miss = ptc_evt_count[WP_MISS];
    assign pmcounterss[0].data.wp_true_hit = pmcounter[WP_TRUE_HIT];
    assign pmcounterss[0].data.ptc_wp_true_hit = ptc_evt_count[WP_TRUE_HIT];
    assign pmcounterss[0].data.mdp_correct_prediction = pmcounter[MDP_CORRECT_PREDICTION];
    assign pmcounterss[0].data.ptc_mdp_correct_prediction = ptc_evt_count[MDP_CORRECT_PREDICTION];
    assign pmcounterss[0].data.mdp_false_hit = pmcounter[MDP_FALSE_HIT];
    assign pmcounterss[0].data.ptc_mdp_false_hit = ptc_evt_count[MDP_FALSE_HIT];
    assign pmcounterss[0].data.mdp_false_miss = pmcounter[MDP_FALSE_MISS];
    assign pmcounterss[0].data.ptc_mdp_false_miss = ptc_evt_count[MDP_FALSE_MISS];
    assign pmcounterss[0].data.mdp_total_prediction = pmcounter[MDP_TOTAL_PREDICTION];
    assign pmcounterss[0].data.ptc_mdp_total_prediction = ptc_evt_count[MDP_TOTAL_PREDICTION];
    assign pmcounterss[0].data.ll_retired = pmcounter[LL_RETIRED];
    assign pmcounterss[0].data.ptc_ll_retired = ptc_evt_count[LL_RETIRED];
    assign pmcounterss[0].data.atomics_retired = pmcounter[ATOMICS_RETIRED];
    assign pmcounterss[0].data.ptc_atomics_retired = ptc_evt_count[ATOMICS_RETIRED];
    assign pmcounterss[0].data.ldst_masked_nano = pmcounter[LDST_MASKED_NANO];
    assign pmcounterss[0].data.ptc_ldst_masked_nano = ptc_evt_count[LDST_MASKED_NANO];
    assign pmcounterss[0].data.ld_executed_nano = pmcounter[LD_EXECUTED_NANO];
    assign pmcounterss[0].data.ptc_ld_executed_nano = ptc_evt_count[LD_EXECUTED_NANO];
    assign pmcounterss[0].data.st_executed_nano = pmcounter[ST_EXECUTED_NANO];
    assign pmcounterss[0].data.ptc_st_executed_nano = ptc_evt_count[ST_EXECUTED_NANO];
    assign pmcounterss[0].data.pfc_agt_cannot_alloc = pmcounter[PFC_AGT_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_pfc_agt_cannot_alloc = ptc_evt_count[PFC_AGT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_agt_evict = pmcounter[PFC_AGT_EVICT];
    assign pmcounterss[0].data.ptc_pfc_agt_evict = ptc_evt_count[PFC_AGT_EVICT];
    assign pmcounterss[0].data.pfc_pht_cannot_alloc = pmcounter[PFC_PHT_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_pfc_pht_cannot_alloc = ptc_evt_count[PFC_PHT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_pht_lookup = pmcounter[PFC_PHT_LOOKUP];
    assign pmcounterss[0].data.ptc_pfc_pht_lookup = ptc_evt_count[PFC_PHT_LOOKUP];
    assign pmcounterss[0].data.pfc_pht_hit = pmcounter[PFC_PHT_HIT];
    assign pmcounterss[0].data.ptc_pfc_pht_hit = ptc_evt_count[PFC_PHT_HIT];
    assign pmcounterss[0].data.pfc_prt_cannot_alloc = pmcounter[PFC_PRT_CANNOT_ALLOC];
    assign pmcounterss[0].data.ptc_pfc_prt_cannot_alloc = ptc_evt_count[PFC_PRT_CANNOT_ALLOC];
    assign pmcounterss[0].data.pfc_no_tlb_credit_stalls = pmcounter[PFC_NO_TLB_CREDIT_STALLS];
    assign pmcounterss[0].data.ptc_pfc_no_tlb_credit_stalls = ptc_evt_count[PFC_NO_TLB_CREDIT_STALLS];
    assign pmcounterss[0].data.pfc_no_tag_credit_stalls = pmcounter[PFC_NO_TAG_CREDIT_STALLS];
    assign pmcounterss[0].data.ptc_pfc_no_tag_credit_stalls = ptc_evt_count[PFC_NO_TAG_CREDIT_STALLS];
    assign pmcounterss[0].data.pfc_prefetches_sent = pmcounter[PFC_PREFETCHES_SENT];
    assign pmcounterss[0].data.ptc_pfc_prefetches_sent = ptc_evt_count[PFC_PREFETCHES_SENT];
    assign pmcounterss[0].data.pfc_prefetches_hit = pmcounter[PFC_PREFETCHES_HIT];
    assign pmcounterss[0].data.ptc_pfc_prefetches_hit = ptc_evt_count[PFC_PREFETCHES_HIT];
    assign pmcounterss[0].data.pfc_prefetches_late = pmcounter[PFC_PREFETCHES_LATE];
    assign pmcounterss[0].data.ptc_pfc_prefetches_late = ptc_evt_count[PFC_PREFETCHES_LATE];
    assign pmcounterss[0].data.pfc_victim_prefetches = pmcounter[PFC_VICTIM_PREFETCHES];
    assign pmcounterss[0].data.ptc_pfc_victim_prefetches = ptc_evt_count[PFC_VICTIM_PREFETCHES];
    assign pmcounterss[0].data.l1d_read_access_aligned = pmcounter[L1D_READ_ACCESS_ALIGNED];
    assign pmcounterss[0].data.ptc_l1d_read_access_aligned = ptc_evt_count[L1D_READ_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_read_access_clc = pmcounter[L1D_READ_ACCESS_CLC];
    assign pmcounterss[0].data.ptc_l1d_read_access_clc = ptc_evt_count[L1D_READ_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_read_access_4kx = pmcounter[L1D_READ_ACCESS_4KX];
    assign pmcounterss[0].data.ptc_l1d_read_access_4kx = ptc_evt_count[L1D_READ_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_read_access_all = pmcounter[L1D_READ_ACCESS_ALL];
    assign pmcounterss[0].data.ptc_l1d_read_access_all = ptc_evt_count[L1D_READ_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_write_access_aligned = pmcounter[L1D_WRITE_ACCESS_ALIGNED];
    assign pmcounterss[0].data.ptc_l1d_write_access_aligned = ptc_evt_count[L1D_WRITE_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_write_access_clc = pmcounter[L1D_WRITE_ACCESS_CLC];
    assign pmcounterss[0].data.ptc_l1d_write_access_clc = ptc_evt_count[L1D_WRITE_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_write_access_4kx = pmcounter[L1D_WRITE_ACCESS_4KX];
    assign pmcounterss[0].data.ptc_l1d_write_access_4kx = ptc_evt_count[L1D_WRITE_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_write_access_all = pmcounter[L1D_WRITE_ACCESS_ALL];
    assign pmcounterss[0].data.ptc_l1d_write_access_all = ptc_evt_count[L1D_WRITE_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_prefetch_access_aligned = pmcounter[L1D_PREFETCH_ACCESS_ALIGNED];
    assign pmcounterss[0].data.ptc_l1d_prefetch_access_aligned = ptc_evt_count[L1D_PREFETCH_ACCESS_ALIGNED];
    assign pmcounterss[0].data.l1d_prefetch_access_clc = pmcounter[L1D_PREFETCH_ACCESS_CLC];
    assign pmcounterss[0].data.ptc_l1d_prefetch_access_clc = ptc_evt_count[L1D_PREFETCH_ACCESS_CLC];
    assign pmcounterss[0].data.l1d_prefetch_access_4kx = pmcounter[L1D_PREFETCH_ACCESS_4KX];
    assign pmcounterss[0].data.ptc_l1d_prefetch_access_4kx = ptc_evt_count[L1D_PREFETCH_ACCESS_4KX];
    assign pmcounterss[0].data.l1d_prefetch_access_all = pmcounter[L1D_PREFETCH_ACCESS_ALL];
    assign pmcounterss[0].data.ptc_l1d_prefetch_access_all = ptc_evt_count[L1D_PREFETCH_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_mmu_access = pmcounter[L1D_MMU_ACCESS];
    assign pmcounterss[0].data.ptc_l1d_mmu_access = ptc_evt_count[L1D_MMU_ACCESS];
    assign pmcounterss[0].data.l1d_snoop_access = pmcounter[L1D_SNOOP_ACCESS];
    assign pmcounterss[0].data.ptc_l1d_snoop_access = ptc_evt_count[L1D_SNOOP_ACCESS];
    assign pmcounterss[0].data.l1d_access_all = pmcounter[L1D_ACCESS_ALL];
    assign pmcounterss[0].data.ptc_l1d_access_all = ptc_evt_count[L1D_ACCESS_ALL];
    assign pmcounterss[0].data.l1d_read_miss = pmcounter[L1D_READ_MISS];
    assign pmcounterss[0].data.ptc_l1d_read_miss = ptc_evt_count[L1D_READ_MISS];
    assign pmcounterss[0].data.l1d_write_miss = pmcounter[L1D_WRITE_MISS];
    assign pmcounterss[0].data.ptc_l1d_write_miss = ptc_evt_count[L1D_WRITE_MISS];
    assign pmcounterss[0].data.l1d_prefetch_miss = pmcounter[L1D_PREFETCH_MISS];
    assign pmcounterss[0].data.ptc_l1d_prefetch_miss = ptc_evt_count[L1D_PREFETCH_MISS];
    assign pmcounterss[0].data.l1d_mmu_miss = pmcounter[L1D_MMU_MISS];
    assign pmcounterss[0].data.ptc_l1d_mmu_miss = ptc_evt_count[L1D_MMU_MISS];
    assign pmcounterss[0].data.l1d_snoop_miss = pmcounter[L1D_SNOOP_MISS];
    assign pmcounterss[0].data.ptc_l1d_snoop_miss = ptc_evt_count[L1D_SNOOP_MISS];
    assign pmcounterss[0].data.l1d_miss_all = pmcounter[L1D_MISS_ALL];
    assign pmcounterss[0].data.ptc_l1d_miss_all = ptc_evt_count[L1D_MISS_ALL];
    assign pmcounterss[0].data.l1d_cache_invalidate_snoop = pmcounter[L1D_CACHE_INVALIDATE_SNOOP];
    assign pmcounterss[0].data.ptc_l1d_cache_invalidate_snoop = ptc_evt_count[L1D_CACHE_INVALIDATE_SNOOP];
    assign pmcounterss[0].data.l1d_cache_invalidate_cmo = pmcounter[L1D_CACHE_INVALIDATE_CMO];
    assign pmcounterss[0].data.ptc_l1d_cache_invalidate_cmo = ptc_evt_count[L1D_CACHE_INVALIDATE_CMO];
    assign pmcounterss[0].data.l1d_cache_invalidate_load_eviction = pmcounter[L1D_CACHE_INVALIDATE_LOAD_EVICTION];
    assign pmcounterss[0].data.ptc_l1d_cache_invalidate_load_eviction = ptc_evt_count[L1D_CACHE_INVALIDATE_LOAD_EVICTION];
    assign pmcounterss[0].data.l1d_cache_invalidate_store_eviction = pmcounter[L1D_CACHE_INVALIDATE_STORE_EVICTION];
    assign pmcounterss[0].data.ptc_l1d_cache_invalidate_store_eviction = ptc_evt_count[L1D_CACHE_INVALIDATE_STORE_EVICTION];
    assign pmcounterss[0].data.l1d_cache_invalidate_prefetch_eviction = pmcounter[L1D_CACHE_INVALIDATE_PREFETCH_EVICTION];
    assign pmcounterss[0].data.ptc_l1d_cache_invalidate_prefetch_eviction = ptc_evt_count[L1D_CACHE_INVALIDATE_PREFETCH_EVICTION];
    assign pmcounterss[0].data.dtlb_read_access = pmcounter[DTLB_READ_ACCESS];
    assign pmcounterss[0].data.ptc_dtlb_read_access = ptc_evt_count[DTLB_READ_ACCESS];
    assign pmcounterss[0].data.dtlb_write_access = pmcounter[DTLB_WRITE_ACCESS];
    assign pmcounterss[0].data.ptc_dtlb_write_access = ptc_evt_count[DTLB_WRITE_ACCESS];
    assign pmcounterss[0].data.dtlb_prefetch_access = pmcounter[DTLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.ptc_dtlb_prefetch_access = ptc_evt_count[DTLB_PREFETCH_ACCESS];
    assign pmcounterss[0].data.dtlb_access_4k = pmcounter[DTLB_ACCESS_4K];
    assign pmcounterss[0].data.ptc_dtlb_access_4k = ptc_evt_count[DTLB_ACCESS_4K];
    assign pmcounterss[0].data.dtlb_access_hugepage = pmcounter[DTLB_ACCESS_HUGEPAGE];
    assign pmcounterss[0].data.ptc_dtlb_access_hugepage = ptc_evt_count[DTLB_ACCESS_HUGEPAGE];
    assign pmcounterss[0].data.dtlb_access_cacheable = pmcounter[DTLB_ACCESS_CACHEABLE];
    assign pmcounterss[0].data.ptc_dtlb_access_cacheable = ptc_evt_count[DTLB_ACCESS_CACHEABLE];
    assign pmcounterss[0].data.dtlb_access_noncacheable = pmcounter[DTLB_ACCESS_NONCACHEABLE];
    assign pmcounterss[0].data.ptc_dtlb_access_noncacheable = ptc_evt_count[DTLB_ACCESS_NONCACHEABLE];
    assign pmcounterss[0].data.dtlb_access_all = pmcounter[DTLB_ACCESS_ALL];
    assign pmcounterss[0].data.ptc_dtlb_access_all = ptc_evt_count[DTLB_ACCESS_ALL];
    assign pmcounterss[0].data.dtlb_read_miss = pmcounter[DTLB_READ_MISS];
    assign pmcounterss[0].data.ptc_dtlb_read_miss = ptc_evt_count[DTLB_READ_MISS];
    assign pmcounterss[0].data.dtlb_write_miss = pmcounter[DTLB_WRITE_MISS];
    assign pmcounterss[0].data.ptc_dtlb_write_miss = ptc_evt_count[DTLB_WRITE_MISS];
    assign pmcounterss[0].data.dtlb_prefetch_miss = pmcounter[DTLB_PREFETCH_MISS];
    assign pmcounterss[0].data.ptc_dtlb_prefetch_miss = ptc_evt_count[DTLB_PREFETCH_MISS];
    assign pmcounterss[0].data.dtlb_miss_4k = pmcounter[DTLB_MISS_4K];
    assign pmcounterss[0].data.ptc_dtlb_miss_4k = ptc_evt_count[DTLB_MISS_4K];
    assign pmcounterss[0].data.dtlb_miss_hugepage = pmcounter[DTLB_MISS_HUGEPAGE];
    assign pmcounterss[0].data.ptc_dtlb_miss_hugepage = ptc_evt_count[DTLB_MISS_HUGEPAGE];
    assign pmcounterss[0].data.dtlb_miss_all = pmcounter[DTLB_MISS_ALL];
    assign pmcounterss[0].data.ptc_dtlb_miss_all = ptc_evt_count[DTLB_MISS_ALL];
    assign pmcounterss[0].data.leaf_tlb_access_ls = pmcounter[LEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.ptc_leaf_tlb_access_ls = ptc_evt_count[LEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.leaf_tlb_access_fe = pmcounter[LEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.ptc_leaf_tlb_access_fe = ptc_evt_count[LEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.leaf_tlb_access_prefetch = pmcounter[LEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.ptc_leaf_tlb_access_prefetch = ptc_evt_count[LEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.leaf_tlb_miss_ls = pmcounter[LEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.ptc_leaf_tlb_miss_ls = ptc_evt_count[LEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.leaf_tlb_miss_fe = pmcounter[LEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.ptc_leaf_tlb_miss_fe = ptc_evt_count[LEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.leaf_tlb_miss_prefetch = pmcounter[LEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.ptc_leaf_tlb_miss_prefetch = ptc_evt_count[LEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.nonleaf_tlb_access_ls = pmcounter[NONLEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_access_ls = ptc_evt_count[NONLEAF_TLB_ACCESS_LS];
    assign pmcounterss[0].data.nonleaf_tlb_access_fe = pmcounter[NONLEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_access_fe = ptc_evt_count[NONLEAF_TLB_ACCESS_FE];
    assign pmcounterss[0].data.nonleaf_tlb_access_prefetch = pmcounter[NONLEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_access_prefetch = ptc_evt_count[NONLEAF_TLB_ACCESS_PREFETCH];
    assign pmcounterss[0].data.nonleaf_tlb_miss_ls = pmcounter[NONLEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_miss_ls = ptc_evt_count[NONLEAF_TLB_MISS_LS];
    assign pmcounterss[0].data.nonleaf_tlb_miss_fe = pmcounter[NONLEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_miss_fe = ptc_evt_count[NONLEAF_TLB_MISS_FE];
    assign pmcounterss[0].data.nonleaf_tlb_miss_prefetch = pmcounter[NONLEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.ptc_nonleaf_tlb_miss_prefetch = ptc_evt_count[NONLEAF_TLB_MISS_PREFETCH];
    assign pmcounterss[0].data.lsu_resyncs_raw = pmcounter[LSU_RESYNCS_RAW];
    assign pmcounterss[0].data.ptc_lsu_resyncs_raw = ptc_evt_count[LSU_RESYNCS_RAW];
    assign pmcounterss[0].data.lsu_resyncs_rar = pmcounter[LSU_RESYNCS_RAR];
    assign pmcounterss[0].data.ptc_lsu_resyncs_rar = ptc_evt_count[LSU_RESYNCS_RAR];
    assign pmcounterss[0].data.lsu_resyncs_all = pmcounter[LSU_RESYNCS_ALL];
    assign pmcounterss[0].data.ptc_lsu_resyncs_all = ptc_evt_count[LSU_RESYNCS_ALL];
    assign pmcounterss[0].data.ls_replay_load = pmcounter[LS_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_ls_replay_load = ptc_evt_count[LS_REPLAY_LOAD];
    assign pmcounterss[0].data.ls_replay_store = pmcounter[LS_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_ls_replay_store = ptc_evt_count[LS_REPLAY_STORE];
    assign pmcounterss[0].data.ls_replay_prefetch = pmcounter[LS_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_ls_replay_prefetch = ptc_evt_count[LS_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ls_replay_mmu = pmcounter[LS_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_ls_replay_mmu = ptc_evt_count[LS_REPLAY_MMU];
    assign pmcounterss[0].data.ls_replay_all = pmcounter[LS_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_ls_replay_all = ptc_evt_count[LS_REPLAY_ALL];
    assign pmcounterss[0].data.ls_way_predictor_replay_load = pmcounter[LS_WAY_PREDICTOR_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_ls_way_predictor_replay_load = ptc_evt_count[LS_WAY_PREDICTOR_REPLAY_LOAD];
    assign pmcounterss[0].data.ls_way_predictor_replay_store = pmcounter[LS_WAY_PREDICTOR_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_ls_way_predictor_replay_store = ptc_evt_count[LS_WAY_PREDICTOR_REPLAY_STORE];
    assign pmcounterss[0].data.ls_way_predictor_replay_prefetch = pmcounter[LS_WAY_PREDICTOR_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_ls_way_predictor_replay_prefetch = ptc_evt_count[LS_WAY_PREDICTOR_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ls_way_predictor_replay_mmu = pmcounter[LS_WAY_PREDICTOR_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_ls_way_predictor_replay_mmu = ptc_evt_count[LS_WAY_PREDICTOR_REPLAY_MMU];
    assign pmcounterss[0].data.ls_way_predictor_replay_all = pmcounter[LS_WAY_PREDICTOR_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_ls_way_predictor_replay_all = ptc_evt_count[LS_WAY_PREDICTOR_REPLAY_ALL];
    assign pmcounterss[0].data.sipt_replay_load = pmcounter[SIPT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_sipt_replay_load = ptc_evt_count[SIPT_REPLAY_LOAD];
    assign pmcounterss[0].data.sipt_replay_store = pmcounter[SIPT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_sipt_replay_store = ptc_evt_count[SIPT_REPLAY_STORE];
    assign pmcounterss[0].data.sipt_replay_prefetch = pmcounter[SIPT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_sipt_replay_prefetch = ptc_evt_count[SIPT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.sipt_replay_mmu = pmcounter[SIPT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_sipt_replay_mmu = ptc_evt_count[SIPT_REPLAY_MMU];
    assign pmcounterss[0].data.sipt_replay_all = pmcounter[SIPT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_sipt_replay_all = ptc_evt_count[SIPT_REPLAY_ALL];
    assign pmcounterss[0].data.stlf_replay_load = pmcounter[STLF_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_stlf_replay_load = ptc_evt_count[STLF_REPLAY_LOAD];
    assign pmcounterss[0].data.stlf_replay_store = pmcounter[STLF_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_stlf_replay_store = ptc_evt_count[STLF_REPLAY_STORE];
    assign pmcounterss[0].data.stlf_replay_prefetch = pmcounter[STLF_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_stlf_replay_prefetch = ptc_evt_count[STLF_REPLAY_PREFETCH];
    assign pmcounterss[0].data.stlf_replay_mmu = pmcounter[STLF_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_stlf_replay_mmu = ptc_evt_count[STLF_REPLAY_MMU];
    assign pmcounterss[0].data.stlf_replay_all = pmcounter[STLF_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_stlf_replay_all = ptc_evt_count[STLF_REPLAY_ALL];
    assign pmcounterss[0].data.tag_bank_conflict_replay_load = pmcounter[TAG_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_tag_bank_conflict_replay_load = ptc_evt_count[TAG_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.tag_bank_conflict_replay_store = pmcounter[TAG_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_tag_bank_conflict_replay_store = ptc_evt_count[TAG_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.tag_bank_conflict_replay_prefetch = pmcounter[TAG_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_tag_bank_conflict_replay_prefetch = ptc_evt_count[TAG_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.tag_bank_conflict_replay_mmu = pmcounter[TAG_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_tag_bank_conflict_replay_mmu = ptc_evt_count[TAG_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.tag_bank_conflict_replay_all = pmcounter[TAG_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_tag_bank_conflict_replay_all = ptc_evt_count[TAG_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.data_bank_conflict_replay_load = pmcounter[DATA_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_data_bank_conflict_replay_load = ptc_evt_count[DATA_BANK_CONFLICT_REPLAY_LOAD];
    assign pmcounterss[0].data.data_bank_conflict_replay_store = pmcounter[DATA_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_data_bank_conflict_replay_store = ptc_evt_count[DATA_BANK_CONFLICT_REPLAY_STORE];
    assign pmcounterss[0].data.data_bank_conflict_replay_prefetch = pmcounter[DATA_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_data_bank_conflict_replay_prefetch = ptc_evt_count[DATA_BANK_CONFLICT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.data_bank_conflict_replay_mmu = pmcounter[DATA_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_data_bank_conflict_replay_mmu = ptc_evt_count[DATA_BANK_CONFLICT_REPLAY_MMU];
    assign pmcounterss[0].data.data_bank_conflict_replay_all = pmcounter[DATA_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_data_bank_conflict_replay_all = ptc_evt_count[DATA_BANK_CONFLICT_REPLAY_ALL];
    assign pmcounterss[0].data.fillbuf_hit_replay_load = pmcounter[FILLBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_fillbuf_hit_replay_load = ptc_evt_count[FILLBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.fillbuf_hit_replay_store = pmcounter[FILLBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_fillbuf_hit_replay_store = ptc_evt_count[FILLBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.fillbuf_hit_replay_prefetch = pmcounter[FILLBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_fillbuf_hit_replay_prefetch = ptc_evt_count[FILLBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.fillbuf_hit_replay_mmu = pmcounter[FILLBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_fillbuf_hit_replay_mmu = ptc_evt_count[FILLBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.fillbuf_hit_replay_all = pmcounter[FILLBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_fillbuf_hit_replay_all = ptc_evt_count[FILLBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.transbuf_hit_replay_load = pmcounter[TRANSBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_transbuf_hit_replay_load = ptc_evt_count[TRANSBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.transbuf_hit_replay_store = pmcounter[TRANSBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_transbuf_hit_replay_store = ptc_evt_count[TRANSBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.transbuf_hit_replay_prefetch = pmcounter[TRANSBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_transbuf_hit_replay_prefetch = ptc_evt_count[TRANSBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.transbuf_hit_replay_mmu = pmcounter[TRANSBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_transbuf_hit_replay_mmu = ptc_evt_count[TRANSBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.transbuf_hit_replay_all = pmcounter[TRANSBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_transbuf_hit_replay_all = ptc_evt_count[TRANSBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.reqbuf_hit_replay_load = pmcounter[REQBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_reqbuf_hit_replay_load = ptc_evt_count[REQBUF_HIT_REPLAY_LOAD];
    assign pmcounterss[0].data.reqbuf_hit_replay_store = pmcounter[REQBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_reqbuf_hit_replay_store = ptc_evt_count[REQBUF_HIT_REPLAY_STORE];
    assign pmcounterss[0].data.reqbuf_hit_replay_prefetch = pmcounter[REQBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_reqbuf_hit_replay_prefetch = ptc_evt_count[REQBUF_HIT_REPLAY_PREFETCH];
    assign pmcounterss[0].data.reqbuf_hit_replay_mmu = pmcounter[REQBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_reqbuf_hit_replay_mmu = ptc_evt_count[REQBUF_HIT_REPLAY_MMU];
    assign pmcounterss[0].data.reqbuf_hit_replay_all = pmcounter[REQBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_reqbuf_hit_replay_all = ptc_evt_count[REQBUF_HIT_REPLAY_ALL];
    assign pmcounterss[0].data.dtlb_replay_load = pmcounter[DTLB_REPLAY_LOAD];
    assign pmcounterss[0].data.ptc_dtlb_replay_load = ptc_evt_count[DTLB_REPLAY_LOAD];
    assign pmcounterss[0].data.dtlb_replay_store = pmcounter[DTLB_REPLAY_STORE];
    assign pmcounterss[0].data.ptc_dtlb_replay_store = ptc_evt_count[DTLB_REPLAY_STORE];
    assign pmcounterss[0].data.dtlb_replay_prefetch = pmcounter[DTLB_REPLAY_PREFETCH];
    assign pmcounterss[0].data.ptc_dtlb_replay_prefetch = ptc_evt_count[DTLB_REPLAY_PREFETCH];
    assign pmcounterss[0].data.dtlb_replay_mmu = pmcounter[DTLB_REPLAY_MMU];
    assign pmcounterss[0].data.ptc_dtlb_replay_mmu = ptc_evt_count[DTLB_REPLAY_MMU];
    assign pmcounterss[0].data.dtlb_replay_all = pmcounter[DTLB_REPLAY_ALL];
    assign pmcounterss[0].data.ptc_dtlb_replay_all = ptc_evt_count[DTLB_REPLAY_ALL];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_load = pmcounter[REQBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.ptc_reqbuf_cannot_alloc_load = ptc_evt_count[REQBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_store = pmcounter[REQBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.ptc_reqbuf_cannot_alloc_store = ptc_evt_count[REQBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_prefetch = pmcounter[REQBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.ptc_reqbuf_cannot_alloc_prefetch = ptc_evt_count[REQBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_mmu = pmcounter[REQBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.ptc_reqbuf_cannot_alloc_mmu = ptc_evt_count[REQBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.reqbuf_cannot_alloc_all = pmcounter[REQBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.ptc_reqbuf_cannot_alloc_all = ptc_evt_count[REQBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.transbuf_cannot_alloc_load = pmcounter[TRANSBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.ptc_transbuf_cannot_alloc_load = ptc_evt_count[TRANSBUF_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.transbuf_cannot_alloc_store = pmcounter[TRANSBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.ptc_transbuf_cannot_alloc_store = ptc_evt_count[TRANSBUF_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.transbuf_cannot_alloc_prefetch = pmcounter[TRANSBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.ptc_transbuf_cannot_alloc_prefetch = ptc_evt_count[TRANSBUF_CANNOT_ALLOC_PREFETCH];
    assign pmcounterss[0].data.transbuf_cannot_alloc_mmu = pmcounter[TRANSBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.ptc_transbuf_cannot_alloc_mmu = ptc_evt_count[TRANSBUF_CANNOT_ALLOC_MMU];
    assign pmcounterss[0].data.transbuf_cannot_alloc_all = pmcounter[TRANSBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.ptc_transbuf_cannot_alloc_all = ptc_evt_count[TRANSBUF_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.pcb_cannot_alloc_load = pmcounter[PCB_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.ptc_pcb_cannot_alloc_load = ptc_evt_count[PCB_CANNOT_ALLOC_LOAD];
    assign pmcounterss[0].data.pcb_cannot_alloc_store = pmcounter[PCB_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.ptc_pcb_cannot_alloc_store = ptc_evt_count[PCB_CANNOT_ALLOC_STORE];
    assign pmcounterss[0].data.pcb_cannot_alloc_all = pmcounter[PCB_CANNOT_ALLOC_ALL];
    assign pmcounterss[0].data.ptc_pcb_cannot_alloc_all = ptc_evt_count[PCB_CANNOT_ALLOC_ALL];

endmodule

module pmu_ema #(parameter WIDTH=8, // Width of Reported Value / Activity
                 parameter DECAY=8) // Width of extra decay bits, total size = WIDTH+DECAY
(
  input              i_clk,
  input              i_reset_n,
  input              i_en,
  input [WIDTH-1:0]  i_activity, // new activity to add in
  input [WIDTH-1:0]  i_decayadj, // decay rate adjustment in powers of 2, tie to 0 if unneeded
  output [WIDTH-1:0] o_activity, // Ema Current Value
  output             o_busy // Ema is non-zero
);

   localparam EMA_SIZE = WIDTH+DECAY;
   logic [EMA_SIZE-1:0] NxtEma;
   logic [EMA_SIZE-1:0] Ema;

   // Old Value + New Activity - OldValue Decayed
   assign NxtEma[EMA_SIZE-1:0]
     = Ema[EMA_SIZE-1:0] +
       ({{DECAY{1'b0}},i_activity[WIDTH-1:0]} << i_decayadj[WIDTH-1:0]) -
       ({{DECAY{1'b0}},Ema[WIDTH+DECAY-1:DECAY+1],        // upper bits
         Ema[DECAY] |                                     // bit 0 of upper
         ~(|Ema[WIDTH+DECAY-1:DECAY]) & (|Ema[DECAY-1:0]) // no upper bits, decay lower bits rounded up
         } << i_decayadj[WIDTH-1:0]);

   always_ff @(posedge i_clk)
     if (~i_reset_n)
       Ema[EMA_SIZE-1:0] <= {EMA_SIZE{1'b0}};
     else if (i_en)
       Ema[EMA_SIZE-1:0] <= NxtEma[EMA_SIZE-1:0];

   assign o_activity[WIDTH-1:0] = Ema[WIDTH+DECAY-1:DECAY];
   assign o_busy = |Ema;

endmodule
