#include "cvm/logger.hpp"
#include "cvm/topology.hpp"
#include "rv_tester_transactions.hpp"
#include "rv_tester/rv_tester_structs.h"
#include <cassert>
#include <vector>

class pmu {

public:
  // AUTOGENERATED -- NO TOUCH

  typedef enum : size_t {
    // Event for each CPU cycle; impelemented via the mcycle CSR
    CPU_CYCLES,
    // Event for each retired instruction; impelemented via the minstret CSR
    INSTRUCTIONS,
    // The count will represent all the requests made to cache subsystem that
    // hit in any level in cache. includes accesses made by Speculatively
    // executed instructions and hardware prefetchers, but does not include
    // non-cacheable requests
    CACHE_REFERENCES,
    // Event for a request made to cache subsystem that misses in last level.
    // includes accesses made by Speculatively executed instructions and
    // hardware prefetchers, but does not include non-cacheable requests
    CACHE_MISSES,
    // Event for retired branch instructions. Branch instructions are all
    // control instructions -- conditional and unconditional, direct and
    // indirect. branches, jumps, calls, returns.
    BRANCH_INSTRUCTIONS,
    // Event for retiring a branch instruction that mispredicted during its
    // execution. The misprediction could be due to direction predictor or
    // target predictor. This will not include mispredictions due to next-fetch
    // predictor.
    BRANCH_MISSES,
    // Event for each BUS cycle
    BUS_CYCLES,
    // Event fired on each cycle when backend is ready to accept a fetch bundle,
    // but frontend is not able to supply any instructions.
    STALLED_CYCLES_FRONTEND,
    // Event fired on each where frontend is ready to supply at least one
    // instruction, but backend is not able to accept. This should be measured
    // at stage MC0
    STALLED_CYCLES_BACKEND,
    // Event for each reference CPU cycle; wall clock
    REF_CPU_CYCLES,
    // Event for a l1d_cache access caused by a demand Memory-read operation.
    // includes accesses made by Speculatively executed instructions, but does
    // not include accesses to IO or noncacheable regions
    L1D_READ_ACCESS,
    // Event for a l1d_cache refill that is due to a demand Memory-read
    // operation. includes accesses made by Speculatively executed instructions,
    // but does not include accesses to IO or noncacheable regions
    L1D_READ_MISS,
    // Event for a l1d_cache access caused by a Memory-write operation. includes
    // accesses made by Speculatively executed instructions, but does not
    // include accesses to IO or noncacheable regions
    L1D_WRITE_ACCESS,
    // Event for a l1d_cache refill caused by a Memory-read operation. includes
    // accesses made by Speculatively executed instructions, but does not
    // include accesses to IO or noncacheable regions
    L1D_WRITE_MISS,
    // Event for a l1d_cache access caused by a hardware prefetcher
    L1D_PREFETCH_ACCESS,
    // Event for a l1d_cache refill caused by a hardware prefetcher
    L1D_PREFETCH_MISS,
    // Event for an l1i_cache access, includes accesses made by Speculatively
    // executed instructions. Any access that happens after a miss should not be
    // counted -- this is explicit to address the common case of an access that
    // happens after an l1i miss occurs
    L1I_READ_ACCESS,
    // Event for an l1i_cache miss, includes accesses made by Speculatively
    // executed instructions.
    L1I_READ_MISS,
    // Level1 instruction cache event write access; may not be supported
    L1I_WRITE_ACCESS,
    // Level1 instruction cache event write miss
    L1I_WRITE_MISS,
    // Level1 instruction cache event prefetch access
    L1I_PREFETCH_ACCESS,
    // Level1 instruction cache event prefetch miss
    L1I_PREFETCH_MISS,
    // Last level cache event read access
    LL_READ_ACCESS,
    // Last level cache event read miss
    LL_READ_MISS,
    // Last level cache event write access
    LL_WRITE_ACCESS,
    // Last level cache event write miss
    LL_WRITE_MISS,
    // Last level cache event prefetch access
    LL_PREFETCH_ACCESS,
    // Last level cache event prefetch miss
    LL_PREFETCH_MISS,
    // Event for an l1 dTLB access caused by a demand Memory-read operation.
    // includes accesses made by Speculatively executed instructions.
    DTLB_READ_ACCESS,
    // Event for an l1 dTLB miss caused by a demand Memory-read operation.
    // includes accesses made by Speculatively executed instructions.
    DTLB_READ_MISS,
    // Event for an l1 dTLB access caused by a Memory-write operation. includes
    // accesses made by Speculatively executed instructions.
    DTLB_WRITE_ACCESS,
    // Event for an l1 dTLB access caused by a Memory-write operation. includes
    // accesses made by Speculatively executed instructions.
    DTLB_WRITE_MISS,
    // Data TLB event prefetch access
    DTLB_PREFETCH_ACCESS,
    // Data TLB event prefetch miss
    DTLB_PREFETCH_MISS,
    // Event for an l1itlb access, includes accesses made by Speculatively
    // executed instructions. Any access that happens after a miss should not be
    // counted -- this is explicit to address the common case of an access that
    // happens after an l1i miss occurs
    ITLB_READ_ACCESS,
    // Event for an l1i_cache miss, includes accesses made by Speculatively
    // executed instructions.
    ITLB_READ_MISS,
    // Instruction TLB event write access
    ITLB_WRITE_ACCESS,
    // Instruction TLB event write miss
    ITLB_WRITE_MISS,
    // Instruction TLB event prefetch access
    ITLB_PREFETCH_ACCESS,
    // Instruction TLB event prefetch miss
    ITLB_PREFETCH_MISS,
    // Branch predictor unit event write access
    BPU_WRITE_ACCESS,
    // all l1 data cache invalidates
    L1D_CACHE_INVALIDATE,
    // Event for when the machine observes a backend stall and the oldest
    // instruction in the machine is load that has missed in l1d
    STALLS_MEM_L1D_MISS,
    // Event for when the machine observes a backend stall and the STQ can not
    // drain to SMB.
    STALLS_MEM_STORES,
    // Event for when the machine observes a backend stall and there is an
    // outstanding dtlb miss request
    STALLS_MEM_L1DTLB_MISS,
    // number of cycles spent on a demand l2 miss, from an l1d miss
    STALLS_MEM_L1D_MISS_L2_MISS,
    // cycles spent stalled on any demand miss
    STALLS_MEM_ANY,
    // number of cycles stalled due to l1 ic miss
    STALLS_MEM_L1I_MISS,
    // Any event that causes an nfp bubble -- includes nfp low/high/ras miss or
    // redirect
    NFP_MISPREDICT,
    // operation speculatively executed, branch immediate
    BR_IMMED_SPEC,
    // operation speculatively executed, indirect branch
    BR_INDIRECT_SPEC,
    // operation speculatively executed, return from subroutine
    BR_RET_SPEC,
    // operation speculatively executed, load.
    LD_SPEC,
    // operation speculatively executed, store.
    ST_SPEC,
    // operation speculatively executed, integer data-processing.
    INT_SPEC,
    // operation speculatively executed, floating-point instruction.
    FP_SPEC,
    // Event for each op issuing
    UOP_ISSUED,
    // Event for each op retiring
    UOP_RETIRED,
    // Total number of uops flushed
    TOTAL_UOPS_FLUSHED,
    // number of indirect branches retired
    TOTAL_IND_BR_RETIRED,
    // number of mispredicted indirect branches retired
    TOTAL_IND_BR_RETIRED_MISPRED,
    // number of lsu flush events
    LSU_RESYNCS,
    // Event for anytime a flush is emitted from midcore, regardless of origin
    TOTAL_FLUSHES,
    // Number of misaligned loads
    LOAD_MISAL_ACCESSES,
    // Number of misaligned stores
    STORE_MISAL_ACCESSES,
    // number of store to load forwarding hits
    STLF_HITS,
    // number of cycles there is any valid op being processed by the vector
    // datapath
    VECTOR_BUSY_CYCLES,
    // Event for each CPU cycle that happens while in m mode
    M_MODE_CYCLES,
    // Event for each retired instruction that happens while in m mode
    M_MODE_INSTRET,
    // Event for each CPU cycle that happens while in s mode
    S_MODE_CYCLES,
    // Event for each retired instruction that happens while in s mode
    S_MODE_INSTRET,
    // Event for each CPU cycle that happens while in u mode
    U_MODE_CYCLES,
    // Event for each retired instruction that happens while in u mode
    U_MODE_INSTRET,
    // Event for each compressed instruction that is retired
    COMPRESSED_INSTRET,
    // Event for each tlb invalidation -- this will track retired instructions
    // that invalidate the TLB
    TLB_INVALIDATES,
    // Event for each retired control flow instruction that uses the return
    // address stack for prediction
    BR_RET_RETIRED,
    // Event for each retired  and mispredicted control flow instruction that
    // uses the return address stack for prediction
    BR_RET_MISSES,
    // Event for each retired control flow instruction that uses ITTAGE for
    // prediction
    IND_BR_RETIRED,
    // Event for each retired and mispredicted control flow instruction that
    // uses ITTAGE for prediction
    IND_BR_MISSES,
    // Event for each retired control flow instruction that uses TAGE for
    // prediction
    REL_BR_RETIRED,
    // Event for each retired and mispredicted control flow instruction that
    // uses TAGE for prediction
    REL_BR_MISSES,
    // Event for each cycle when no integer PRNs are free
    CYCLES_NO_INT_PRN,
    // Event for each cycle when no floating point PRNs are free
    CYCLES_NO_FP_PRN,
    // Event for each cycle when no vec PRNs are free
    CYCLES_NO_VEC_PRN,
    // Event for each ic way mispredict
    IC_WAY_MISPRED,
    // Event for any LS replay
    LS_REPLAY,
    // Event for any LS replay caused by the DC way predictor
    LS_REPLAY_WAY_PREDICTOR,
    // Event for each cycle when the ldq is full
    CYCLES_LDQ_FULL,
    // Event for each cycle when the stq is full
    CYCLES_STQ_FULL,
    // Event for each cycle when the rar is full
    CYCLES_RAR_FULL,
    // Event for each cycle when the raw is full
    CYCLES_RAW_FULL,
    COUNT
  } counter;

  // AUTOGENERATED -- NO TOUCH

  std::vector<uint64_t>
  to_vector(const rv_tester_transactions::pmu::pmcounters<> &pmcounters) {
    std::vector<uint64_t> tmp(counter::COUNT);

    tmp[counter::CPU_CYCLES] = pmcounters.cpu_cycles;
    tmp[counter::INSTRUCTIONS] = pmcounters.instructions;
    tmp[counter::CACHE_REFERENCES] = pmcounters.cache_references;
    tmp[counter::CACHE_MISSES] = pmcounters.cache_misses;
    tmp[counter::BRANCH_INSTRUCTIONS] = pmcounters.branch_instructions;
    tmp[counter::BRANCH_MISSES] = pmcounters.branch_misses;
    tmp[counter::BUS_CYCLES] = pmcounters.bus_cycles;
    tmp[counter::STALLED_CYCLES_FRONTEND] = pmcounters.stalled_cycles_frontend;
    tmp[counter::STALLED_CYCLES_BACKEND] = pmcounters.stalled_cycles_backend;
    tmp[counter::REF_CPU_CYCLES] = pmcounters.ref_cpu_cycles;
    tmp[counter::L1D_READ_ACCESS] = pmcounters.l1d_read_access;
    tmp[counter::L1D_READ_MISS] = pmcounters.l1d_read_miss;
    tmp[counter::L1D_WRITE_ACCESS] = pmcounters.l1d_write_access;
    tmp[counter::L1D_WRITE_MISS] = pmcounters.l1d_write_miss;
    tmp[counter::L1D_PREFETCH_ACCESS] = pmcounters.l1d_prefetch_access;
    tmp[counter::L1D_PREFETCH_MISS] = pmcounters.l1d_prefetch_miss;
    tmp[counter::L1I_READ_ACCESS] = pmcounters.l1i_read_access;
    tmp[counter::L1I_READ_MISS] = pmcounters.l1i_read_miss;
    tmp[counter::L1I_WRITE_ACCESS] = pmcounters.l1i_write_access;
    tmp[counter::L1I_WRITE_MISS] = pmcounters.l1i_write_miss;
    tmp[counter::L1I_PREFETCH_ACCESS] = pmcounters.l1i_prefetch_access;
    tmp[counter::L1I_PREFETCH_MISS] = pmcounters.l1i_prefetch_miss;
    tmp[counter::LL_READ_ACCESS] = pmcounters.ll_read_access;
    tmp[counter::LL_READ_MISS] = pmcounters.ll_read_miss;
    tmp[counter::LL_WRITE_ACCESS] = pmcounters.ll_write_access;
    tmp[counter::LL_WRITE_MISS] = pmcounters.ll_write_miss;
    tmp[counter::LL_PREFETCH_ACCESS] = pmcounters.ll_prefetch_access;
    tmp[counter::LL_PREFETCH_MISS] = pmcounters.ll_prefetch_miss;
    tmp[counter::DTLB_READ_ACCESS] = pmcounters.dtlb_read_access;
    tmp[counter::DTLB_READ_MISS] = pmcounters.dtlb_read_miss;
    tmp[counter::DTLB_WRITE_ACCESS] = pmcounters.dtlb_write_access;
    tmp[counter::DTLB_WRITE_MISS] = pmcounters.dtlb_write_miss;
    tmp[counter::DTLB_PREFETCH_ACCESS] = pmcounters.dtlb_prefetch_access;
    tmp[counter::DTLB_PREFETCH_MISS] = pmcounters.dtlb_prefetch_miss;
    tmp[counter::ITLB_READ_ACCESS] = pmcounters.itlb_read_access;
    tmp[counter::ITLB_READ_MISS] = pmcounters.itlb_read_miss;
    tmp[counter::ITLB_WRITE_ACCESS] = pmcounters.itlb_write_access;
    tmp[counter::ITLB_WRITE_MISS] = pmcounters.itlb_write_miss;
    tmp[counter::ITLB_PREFETCH_ACCESS] = pmcounters.itlb_prefetch_access;
    tmp[counter::ITLB_PREFETCH_MISS] = pmcounters.itlb_prefetch_miss;
    tmp[counter::BPU_WRITE_ACCESS] = pmcounters.bpu_write_access;
    tmp[counter::L1D_CACHE_INVALIDATE] = pmcounters.l1d_cache_invalidate;
    tmp[counter::STALLS_MEM_L1D_MISS] = pmcounters.stalls_mem_l1d_miss;
    tmp[counter::STALLS_MEM_STORES] = pmcounters.stalls_mem_stores;
    tmp[counter::STALLS_MEM_L1DTLB_MISS] = pmcounters.stalls_mem_l1dtlb_miss;
    tmp[counter::STALLS_MEM_L1D_MISS_L2_MISS] =
        pmcounters.stalls_mem_l1d_miss_l2_miss;
    tmp[counter::STALLS_MEM_ANY] = pmcounters.stalls_mem_any;
    tmp[counter::STALLS_MEM_L1I_MISS] = pmcounters.stalls_mem_l1i_miss;
    tmp[counter::NFP_MISPREDICT] = pmcounters.nfp_mispredict;
    tmp[counter::BR_IMMED_SPEC] = pmcounters.br_immed_spec;
    tmp[counter::BR_INDIRECT_SPEC] = pmcounters.br_indirect_spec;
    tmp[counter::BR_RET_SPEC] = pmcounters.br_ret_spec;
    tmp[counter::LD_SPEC] = pmcounters.ld_spec;
    tmp[counter::ST_SPEC] = pmcounters.st_spec;
    tmp[counter::INT_SPEC] = pmcounters.int_spec;
    tmp[counter::FP_SPEC] = pmcounters.fp_spec;
    tmp[counter::UOP_ISSUED] = pmcounters.uop_issued;
    tmp[counter::UOP_RETIRED] = pmcounters.uop_retired;
    tmp[counter::TOTAL_UOPS_FLUSHED] = pmcounters.total_uops_flushed;
    tmp[counter::TOTAL_IND_BR_RETIRED] = pmcounters.total_ind_br_retired;
    tmp[counter::TOTAL_IND_BR_RETIRED_MISPRED] =
        pmcounters.total_ind_br_retired_mispred;
    tmp[counter::LSU_RESYNCS] = pmcounters.lsu_resyncs;
    tmp[counter::TOTAL_FLUSHES] = pmcounters.total_flushes;
    tmp[counter::LOAD_MISAL_ACCESSES] = pmcounters.load_misal_accesses;
    tmp[counter::STORE_MISAL_ACCESSES] = pmcounters.store_misal_accesses;
    tmp[counter::STLF_HITS] = pmcounters.stlf_hits;
    tmp[counter::VECTOR_BUSY_CYCLES] = pmcounters.vector_busy_cycles;
    tmp[counter::M_MODE_CYCLES] = pmcounters.m_mode_cycles;
    tmp[counter::M_MODE_INSTRET] = pmcounters.m_mode_instret;
    tmp[counter::S_MODE_CYCLES] = pmcounters.s_mode_cycles;
    tmp[counter::S_MODE_INSTRET] = pmcounters.s_mode_instret;
    tmp[counter::U_MODE_CYCLES] = pmcounters.u_mode_cycles;
    tmp[counter::U_MODE_INSTRET] = pmcounters.u_mode_instret;
    tmp[counter::COMPRESSED_INSTRET] = pmcounters.compressed_instret;
    tmp[counter::TLB_INVALIDATES] = pmcounters.tlb_invalidates;
    tmp[counter::BR_RET_RETIRED] = pmcounters.br_ret_retired;
    tmp[counter::BR_RET_MISSES] = pmcounters.br_ret_misses;
    tmp[counter::IND_BR_RETIRED] = pmcounters.ind_br_retired;
    tmp[counter::IND_BR_MISSES] = pmcounters.ind_br_misses;
    tmp[counter::REL_BR_RETIRED] = pmcounters.rel_br_retired;
    tmp[counter::REL_BR_MISSES] = pmcounters.rel_br_misses;
    tmp[counter::CYCLES_NO_INT_PRN] = pmcounters.cycles_no_int_prn;
    tmp[counter::CYCLES_NO_FP_PRN] = pmcounters.cycles_no_fp_prn;
    tmp[counter::CYCLES_NO_VEC_PRN] = pmcounters.cycles_no_vec_prn;
    tmp[counter::IC_WAY_MISPRED] = pmcounters.ic_way_mispred;
    tmp[counter::LS_REPLAY] = pmcounters.ls_replay;
    tmp[counter::LS_REPLAY_WAY_PREDICTOR] = pmcounters.ls_replay_way_predictor;
    tmp[counter::CYCLES_LDQ_FULL] = pmcounters.cycles_ldq_full;
    tmp[counter::CYCLES_STQ_FULL] = pmcounters.cycles_stq_full;
    tmp[counter::CYCLES_RAR_FULL] = pmcounters.cycles_rar_full;
    tmp[counter::CYCLES_RAW_FULL] = pmcounters.cycles_raw_full;

    return tmp;
  }

  const std::unordered_map<counter, std::string_view> to_string = {
      {CPU_CYCLES, "cpu_cycles"},
      {INSTRUCTIONS, "instructions"},
      {CACHE_REFERENCES, "cache_references"},
      {CACHE_MISSES, "cache_misses"},
      {BRANCH_INSTRUCTIONS, "branch_instructions"},
      {BRANCH_MISSES, "branch_misses"},
      {BUS_CYCLES, "bus_cycles"},
      {STALLED_CYCLES_FRONTEND, "stalled_cycles_frontend"},
      {STALLED_CYCLES_BACKEND, "stalled_cycles_backend"},
      {REF_CPU_CYCLES, "ref_cpu_cycles"},
      {L1D_READ_ACCESS, "l1d_read_access"},
      {L1D_READ_MISS, "l1d_read_miss"},
      {L1D_WRITE_ACCESS, "l1d_write_access"},
      {L1D_WRITE_MISS, "l1d_write_miss"},
      {L1D_PREFETCH_ACCESS, "l1d_prefetch_access"},
      {L1D_PREFETCH_MISS, "l1d_prefetch_miss"},
      {L1I_READ_ACCESS, "l1i_read_access"},
      {L1I_READ_MISS, "l1i_read_miss"},
      {L1I_WRITE_ACCESS, "l1i_write_access"},
      {L1I_WRITE_MISS, "l1i_write_miss"},
      {L1I_PREFETCH_ACCESS, "l1i_prefetch_access"},
      {L1I_PREFETCH_MISS, "l1i_prefetch_miss"},
      {LL_READ_ACCESS, "ll_read_access"},
      {LL_READ_MISS, "ll_read_miss"},
      {LL_WRITE_ACCESS, "ll_write_access"},
      {LL_WRITE_MISS, "ll_write_miss"},
      {LL_PREFETCH_ACCESS, "ll_prefetch_access"},
      {LL_PREFETCH_MISS, "ll_prefetch_miss"},
      {DTLB_READ_ACCESS, "dtlb_read_access"},
      {DTLB_READ_MISS, "dtlb_read_miss"},
      {DTLB_WRITE_ACCESS, "dtlb_write_access"},
      {DTLB_WRITE_MISS, "dtlb_write_miss"},
      {DTLB_PREFETCH_ACCESS, "dtlb_prefetch_access"},
      {DTLB_PREFETCH_MISS, "dtlb_prefetch_miss"},
      {ITLB_READ_ACCESS, "itlb_read_access"},
      {ITLB_READ_MISS, "itlb_read_miss"},
      {ITLB_WRITE_ACCESS, "itlb_write_access"},
      {ITLB_WRITE_MISS, "itlb_write_miss"},
      {ITLB_PREFETCH_ACCESS, "itlb_prefetch_access"},
      {ITLB_PREFETCH_MISS, "itlb_prefetch_miss"},
      {BPU_WRITE_ACCESS, "bpu_write_access"},
      {L1D_CACHE_INVALIDATE, "l1d_cache_invalidate"},
      {STALLS_MEM_L1D_MISS, "stalls_mem_l1d_miss"},
      {STALLS_MEM_STORES, "stalls_mem_stores"},
      {STALLS_MEM_L1DTLB_MISS, "stalls_mem_l1dtlb_miss"},
      {STALLS_MEM_L1D_MISS_L2_MISS, "stalls_mem_l1d_miss_l2_miss"},
      {STALLS_MEM_ANY, "stalls_mem_any"},
      {STALLS_MEM_L1I_MISS, "stalls_mem_l1i_miss"},
      {NFP_MISPREDICT, "nfp_mispredict"},
      {BR_IMMED_SPEC, "br_immed_spec"},
      {BR_INDIRECT_SPEC, "br_indirect_spec"},
      {BR_RET_SPEC, "br_ret_spec"},
      {LD_SPEC, "ld_spec"},
      {ST_SPEC, "st_spec"},
      {INT_SPEC, "int_spec"},
      {FP_SPEC, "fp_spec"},
      {UOP_ISSUED, "uop_issued"},
      {UOP_RETIRED, "uop_retired"},
      {TOTAL_UOPS_FLUSHED, "total_uops_flushed"},
      {TOTAL_IND_BR_RETIRED, "total_ind_br_retired"},
      {TOTAL_IND_BR_RETIRED_MISPRED, "total_ind_br_retired_mispred"},
      {LSU_RESYNCS, "lsu_resyncs"},
      {TOTAL_FLUSHES, "total_flushes"},
      {LOAD_MISAL_ACCESSES, "load_misal_accesses"},
      {STORE_MISAL_ACCESSES, "store_misal_accesses"},
      {STLF_HITS, "stlf_hits"},
      {VECTOR_BUSY_CYCLES, "vector_busy_cycles"},
      {M_MODE_CYCLES, "m_mode_cycles"},
      {M_MODE_INSTRET, "m_mode_instret"},
      {S_MODE_CYCLES, "s_mode_cycles"},
      {S_MODE_INSTRET, "s_mode_instret"},
      {U_MODE_CYCLES, "u_mode_cycles"},
      {U_MODE_INSTRET, "u_mode_instret"},
      {COMPRESSED_INSTRET, "compressed_instret"},
      {TLB_INVALIDATES, "tlb_invalidates"},
      {BR_RET_RETIRED, "br_ret_retired"},
      {BR_RET_MISSES, "br_ret_misses"},
      {IND_BR_RETIRED, "ind_br_retired"},
      {IND_BR_MISSES, "ind_br_misses"},
      {REL_BR_RETIRED, "rel_br_retired"},
      {REL_BR_MISSES, "rel_br_misses"},
      {CYCLES_NO_INT_PRN, "cycles_no_int_prn"},
      {CYCLES_NO_FP_PRN, "cycles_no_fp_prn"},
      {CYCLES_NO_VEC_PRN, "cycles_no_vec_prn"},
      {IC_WAY_MISPRED, "ic_way_mispred"},
      {LS_REPLAY, "ls_replay"},
      {LS_REPLAY_WAY_PREDICTOR, "ls_replay_way_predictor"},
      {CYCLES_LDQ_FULL, "cycles_ldq_full"},
      {CYCLES_STQ_FULL, "cycles_stq_full"},
      {CYCLES_RAR_FULL, "cycles_rar_full"},
      {CYCLES_RAW_FULL, "cycles_raw_full"},
  };
  pmu(cvm::topology::loc_t, unsigned);
  ~pmu();

  void report();
  void ipc_check();

  bool is_within_range(double, double, int);
  void configure();
  void process(const rv_tester_transactions::cosim::m_rvfi<> &m_rvfi);
  void process(const rv_tester_transactions::pmu::pmcounters<> &pmcounters);
  void process(const rv_tester::terminate_called_fast &);

private:
  cvm::file_logger log;
  cvm::topology::loc_t loc_;
  unsigned id_;

  std::vector<uint64_t> counters;

  uint64_t perf_start_pc;
  uint64_t perf_start_cycle = 0;
  uint64_t perf_end_pc;
  uint64_t perf_end_cycle = 0;
  bool perf_region_ok = false;
  std::vector<uint64_t> perf_region;

  bool terminated_ = false;
  bool sync_terminate_ = false;
};
