#include "cvm/logger.hpp"
#include "cvm/topology.hpp"
#include "rv_tester_transactions.hpp"
#include "rv_tester/rv_tester_structs.h"
#include <cassert>
#include <vector>

class pmu {

public:
    //AUTOGENERATED -- NO TOUCH

    typedef enum : size_t {
      //Event for each CPU cycle; implemented via the mcycle CSR
      CPU_CYCLES,
      //Event for each retired instruction; implemented via the minstret CSR
      INSTRUCTIONS,
      //Event for each CPU cycle that happens while in m mode
      M_MODE_CYCLES,
      //Event for each retired instruction that happens while in m mode
      M_MODE_INSTRET,
      //Event for each CPU cycle that happens while in s mode
      S_MODE_CYCLES,
      //Event for each retired instruction that happens while in s mode
      S_MODE_INSTRET,
      //Event for each CPU cycle that happens while in u mode
      U_MODE_CYCLES,
      //Event for each retired instruction that happens while in u mode
      U_MODE_INSTRET,
      //Event for each reference CPU cycle; wall clock
      REF_CPU_CYCLES,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full Branch Status Table
      STALLS_BST_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full Prefix table
      STALLS_PFX_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in indirect prediction via Branch Target Predictor or Return Address Stack
      STALLS_INDIRECT_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in instruction cache
      STALLS_ICACHE_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in the ITLB
      STALLS_ITLB_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to i-side request buffers full ITLB/I$
      STALLS_IRB_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full IFBUF
      STALLS_IFBUF_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to stalls_exception
      STALLS_EXCEPTION,
      //Event (speculative) for every fetch block crossing a page boundary and forced to split
      PAGE_CROSSING_FETCHBLOCKS,
      //Event (speculative) for every instance of disagreement between next-fetch predictor and Branch Direction Predictor
      NFP_EARLY_REDIRECT,
      //Event (speculative) for every instance of disagreement between next-fetch predictor and Branch Target Predictor
      NFP_LATE_REDIRECT,
      //Event (speculative) for every instance of redirect caused by IFBUF full
      IFBUF_FULL_REDIRECT,
      //Event for every instance of resync due to CSR access
      NONSPEC_RESYNC,
      //Event (speculative) for every instance of resync due to detectable soft-errors from L2 or LS unit
      FAULT_RESYNC,
      // Event (speculative) for every instance of fetch redirect due to soft-errors in frontend structures
      FAULT_REFETCH,
      //Event (non-speculative) for every instance of entering conservative mode
      CMODE_ENTRY,
      //Event for retiring a branch instruction that mispredicted during its execution. The misprediction could be due to direction predictor or target predictor. This will not include mispredictions due to next-fetch predictor.
      BRANCH_MISSES,
      //Event for each retired and mispredicted control flow instruction that uses the return address stack for prediction
      BR_RET_MISSES,
      //Event for each retired and mispredicted indirect control flow instruction that uses the Branch Target Predictor. Return instructions are not included
      IND_BR_MISSES,
      //Event for each retired and mispredicted conditional control flow instruction that uses the Branch Direction Predictor
      REL_BR_MISSES,
      //Event (speculative) for every instance of branch misprediction flush
      SPEC_BRANCH_REDIRECT,
      //Event (speculative) for every instance of load misprediction flush
      SPEC_LSU_RESYNCS,
      //Event (speculative) for every flush is emitted from midcore regardless of origin
      TOTAL_FLUSHES,
      //Event (speculative) for every instruction provided from decode to Mapper
      UOPS_DECODED,
      //Event (speculative) for an L1I cache access. Only demand accesses are counted. Accesses in the shadow of a demand miss are not counted. Count once for every fetchgroup access
      L1I_READ_ACCESS,
      //Event (speculative) for an L1I cache miss.Misses in the shadow of a demand miss are not counted
      L1I_READ_MISS,
      //Event (speculative) for every L1I cache access for instruction prefetch
      L1I_PREFETCH_ACCESS,
      //Event (speculative) for every L1I cache miss for an instruction prefetch
      L1I_PREFETCH_MISS,
      //Event (speculative) for an L1I TLB demand access. Accesses in the shadow of a demand miss are not counted
      ITLB_READ_ACCESS,
      //Event (speculative) for an L1I TLB demand miss. Misses in the shadow of a demand miss are not counted
      ITLB_READ_MISS,
      //Event (speculative) for an L1I TLB access for an instruction prefetch
      ITLB_PREFETCH_ACCESS,
      //Event (speculative) for an L1I TLB miss for an instruction prefetch
      ITLB_PREFETCH_MISS,
      //Event(speculative) for each instruction cache way misprediction
      IC_WAY_MISPRED,
      //Event (speculative) for every underflow event of return address stack
      RAS_UNDERFLOW,
      //Event (speculative) for every overflow event of return address stack
      RAS_OVERFLOW,
      //Event(speculative) for every fetchgroup written into the IFBUF. If fetchgroup has 2 writes in the same cycle into the IFBUF it is still counted as 1 fetchgroup
      NUM_FETCHGROUPS,
      //Event for every cycle an update to Branch Direction Predictor is delayed due to a bank conflict
      BDP_BANK_CONFLICTS,
      //Event for every cycle an update to Branch Target Predictor is delayed due to bank conflict
      BTP_BANK_CONFLICTS,
      //Event for every write into either Branch Direction Predictor or Branch Target Predictor. Count twice if both are written in the same cycle
      BPU_WRITES,
      //Event fired on each cycle when backend is ready to accept a fetch bundle  but frontend is not able to supply any instructions.
      STALLED_CYCLES_FRONTEND,
      //Event fired on each where frontend is ready to supply at least one instruction but backend is not able to accept. This should be measured at stage MC0
      STALLED_CYCLES_BACKEND,
      //Event (speculative) for each cycle Mapper is stalled due to no integer physical registers
      CYCLES_NO_INT_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to  no floating point physical registers
      CYCLES_NO_FP_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector physical registers
      CYCLES_NO_VEC_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector length physical registers
      CYCLES_NO_VL_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector mask physical registers
      CYCLES_NO_VM_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no reorder buffer entries
      CYCLES_NO_ROB,
      //Event for retired branch instructions. Branch instructions are all control instructions -- conditional and unconditional / direct and indirect jumps
      BRANCH_INSTRUCTIONS,
      //Event for each retiring operation
      UOP_RETIRED,
      //Event for every retired Load operation
      LD_RETIRED,
      //Event for every retired Store operation
      ST_RETIRED,
      //Event for every retired integer operation. This does not include Load or Store operations
      INT_RETIRED,
      //Event for every retired CSR operation
      CSR_RETIRED,
      //Event for each retired control flow instruction that uses the return address stack for prediction
      BR_RET_RETIRED,
      //Event for each retired indirect control flow instruction that uses the Branch Target Predictor for prediction. Return instructions are not included
      IND_BR_RETIRED,
      //Event for each retired conditional control flow instruction that uses the Branch Direction Predictor
      REL_BR_RETIRED,
      //Event for every retired floating point operation. This does not include Load or Store operations
      FP_RETIRED,
      //Event for every retired vector operation. This does not include Load or Store operations
      VEC_RETIRED,
      //Event for every retired transfer(int->fp; int->vec; vec->int; fp->int; fp->vec; vec->fp) operation
      XFER_RETIRED,
      //Event for each confirmed operation
      UOP_CONFIRMED,
      //Event (speculative) for each int affinity op issuing. Multiple issues per cycle should be precisely counted
      UOP_ISSUED_INT,
      //Event (speculative) for each ls affinity op issuing. Multiple issues per cycle should be precisely counted
      UOP_ISSUED_LDST,
      //Event (speculative) for each fp affinity op issuing. Multiple issues per cycle should be precisely counted
      UOP_ISSUED_FP,
      //Event (speculative) for each vec affinity op issuing. Multiple issues per cycle should be precisely counted
      UOP_ISSUED_VEC,
      //Event (speculative) for every confirmed direct Branch
      BR_DIRECT_SPEC,
      //Event (speculative) for every confirmed indirect Branch
      BR_INDIRECT_SPEC,
      //Event (speculative) for every confirmed Return-type operation
      BR_RET_SPEC,
      //Event (speculative) for every confirmed integer operation. This does not include Load or Store operations
      INT_EXECUTED,
      //Event (speculative) for every confirmed floating point operation. This does not include Load or Store operations.
      FP_EXECUTED,
      //Event (speculative) for every confirmed vector point operation. This does not include Load or Store operations.
      VEC_EXECUTED,
      //Event for each compressed instruction that is retired
      COMPRESSED_INSTRET,
      //The count will represent all the requests made to L1 I and D caches. Includes accesses made by Speculatively executed instructions and hardware prefetchers but does not include non-cacheable requests
      CACHE_REFERENCES,
      //Event for a request made to cache subsystem that misses in L1 I and D caches. Includes accesses made by Speculatively executed instructions and hardware prefetchers.  but does not include non-cacheable requests
      CACHE_MISSES,
      //Event for each tlb invalidation -- this will track retired instructions that invalidate the TLB
      TLB_INVALIDATES,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MMU_ACCESS,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_SNOOP_ACCESS,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_ACCESS_ALL,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MMU_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_SNOOP_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MISS_ALL,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_SNOOP,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_CMO,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_LOAD_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_STORE_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_PREFETCH_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_ALL,
      //Event (speculative) for micro-TLB miss caused by a demand memory operation
      UTLB_MISS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_READ_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_WRITE_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_PREFETCH_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_4K,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_HUGEPAGE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_CACHEABLE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_NONCACHEABLE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_ALL,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_READ_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_WRITE_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_PREFETCH_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_4K,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_HUGEPAGE,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_ALL,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_LS,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_FE,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_PREFETCH,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_LS,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_FE,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_PREFETCH,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_LS,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_FE,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_PREFETCH,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_LS,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_FE,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_PREFETCH,
      //Number of page walks initiated
      PAGE_WALKS,
      //Event (speculative) for every cycle the instruction picker has ops -- but does not pick -- and there is a pending L1D demand miss
      STALLS_MEM_L1D_MISS,
      //Event (speculative) for every cycle the instruction picker has ops -- but does not pick -- and the STQ can not drain to SMB.
      STALLS_MEM_STORES,
      //Event (speculative) for every cycle the instruction picker has ops --  but does not pick -- and there is a pending L1 DTLB demand miss
      STALLS_MEM_L1DTLB_MISS,
      //Number of resyncs raised by LSU filtered by (RAW/RAR/All)
      LSU_RESYNCS_RAW,
      //Number of resyncs raised by LSU filtered by (RAW/RAR/All)
      LSU_RESYNCS_RAR,
      //Number of resyncs raised by LSU filtered by (RAW/RAR/All)
      LSU_RESYNCS_ALL,
      //Event (speculative) for every instance of a Store instruction forwarding data to a Load instruction
      STLF_HITS,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_LOAD,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_STORE,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_PREFETCH,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_MMU,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_ALL,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_PREFETCH,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_ALL,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_PREFETCH,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_ALL,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_PREFETCH,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_ALL,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_LOAD,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_STORE,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_PREFETCH,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_MMU,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_ALL,
      //Event (speculative) for every instance of failed Read-After-Read queue allocation to a demand memory-read operation
      RAR_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Read-After-Write queue allocation to a demand memory-read operation
      RAW_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Load Queue allocation to a demand memory-read operation
      LDQ_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Store-Merge-Buffer allocation to a demand memory-write operation
      SMB_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_LOAD,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_STORE,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_PREFETCH,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_MMU,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed FillBuffer allocation
      FILLBUF_CANNOT_ALLOC,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_LOAD,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_STORE,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_PREFETCH,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_MMU,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_LOAD,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_STORE,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed Unaligned Data Buffer allocation
      UDB_CANNOT_ALLOC,
      //Event for every instance a memory operation used the Unaligned Data Buffer for data return
      UDB_DATA_RETURN,
      //Event for every instance an allocated Unaligned Data Buffer entry was lost to another cacheline crossing request
      UDB_LOST,
      //Event for micro way predictor access
      UWP_ACCESS,
      //Event for micro-way-predictor refill caused by a demand memory operation
      UWP_MISS,
      //Event for every instance of a uWP hit matching the L1D hit way
      UWP_TRUE_HIT,
      //Event for way predictor access
      WP_ACCESS,
      //Event for a WP refill caused by a demand memory operation
      WP_MISS,
      //Event for every instance of a WP hit matching the L1D hit way
      WP_TRUE_HIT,
      //Event for a correct prediction by MDP
      MDP_CORRECT_PREDICTION,
      //Event for every instance of prediction by MDP where the load does not get its data from STLF
      MDP_FALSE_HIT,
      //Event for every instance of MDP miss causing a RAW resync
      MDP_FALSE_MISS,
      //Event for every instance of a load predicted by MDP
      MDP_TOTAL_PREDICTION,
      //Event for every retired atomic operation
      ATOMICS_RETIRED,
      //"Event (speculative) for every fully masked
      LDST_MASKED_NANO,
      //Event (speculative) for every confirmed Load nano-operation
      LD_EXECUTED_NANO,
      //Event (speculative) for every confirmed Store nano-operation
      ST_EXECUTED_NANO,
      //Event (speculative) for every failed instance a new Active Generation Table allocation
      PFC_AGT_CANNOT_ALLOC,
      //Event (speculative) for every successful instance of Active Generation Table entry evicted to Pattern History Table
      PFC_AGT_EVICT,
      //Event (speculative) for every failed instance a new entry in Pattern History Table allocation
      PFC_PHT_CANNOT_ALLOC,
      //Event (speculative) for every instance of read-access (lookup) to Pattern History Table
      PFC_PHT_LOOKUP,
      //Event (speculative) for every instance of a hit in the Pattern History Table
      PFC_PHT_HIT,
      //Event (speculative) for every failed instance Prefetch Request Table allocation
      PFC_PRT_CANNOT_ALLOC,
      //Event (speculative) for every failed instance a Prefetch TLB request due to no credits
      PFC_NO_TLB_CREDIT_STALLS,
      //Event (speculative) for every failed instance a Prefetch Tag request due to no credit
      PFC_NO_TAG_CREDIT_STALLS,
      //Event (speculative) for every instance of a Prefetch Tag requests sent to LS
      PFC_PREFETCHES_SENT,
      //Event (speculative) for every instance a demand memory operation hits on prefetch-data. Only count the first hit is counted
      PFC_PREFETCHES_HIT,
      //Event (speculative) for every instance a demand memory operation misses in the L1D cache but but hits on a prefetch request in TxnBuf
      PFC_PREFETCHES_LATE,
      //Event (speculative) for every L1D eviction which is an unused prefetch
      PFC_USELESS_PREFETCHES,
    COUNT
    } counter;


    //AUTOGENERATED -- NO TOUCH

std::vector<uint64_t> to_vector(const rv_tester_transactions::pmu::pmcounters<>& pmcounters)
    {
      std::vector<uint64_t> tmp(counter::COUNT);

            tmp[counter::CPU_CYCLES] = pmcounters.cpu_cycles;
      tmp[counter::INSTRUCTIONS] = pmcounters.instructions;
      tmp[counter::M_MODE_CYCLES] = pmcounters.m_mode_cycles;
      tmp[counter::M_MODE_INSTRET] = pmcounters.m_mode_instret;
      tmp[counter::S_MODE_CYCLES] = pmcounters.s_mode_cycles;
      tmp[counter::S_MODE_INSTRET] = pmcounters.s_mode_instret;
      tmp[counter::U_MODE_CYCLES] = pmcounters.u_mode_cycles;
      tmp[counter::U_MODE_INSTRET] = pmcounters.u_mode_instret;
      tmp[counter::REF_CPU_CYCLES] = pmcounters.ref_cpu_cycles;
      tmp[counter::STALLS_BST_FULL] = pmcounters.stalls_bst_full;
      tmp[counter::STALLS_PFX_FULL] = pmcounters.stalls_pfx_full;
      tmp[counter::STALLS_INDIRECT_MISS] = pmcounters.stalls_indirect_miss;
      tmp[counter::STALLS_ICACHE_MISS] = pmcounters.stalls_icache_miss;
      tmp[counter::STALLS_ITLB_MISS] = pmcounters.stalls_itlb_miss;
      tmp[counter::STALLS_IRB_FULL] = pmcounters.stalls_irb_full;
      tmp[counter::STALLS_IFBUF_FULL] = pmcounters.stalls_ifbuf_full;
      tmp[counter::STALLS_EXCEPTION] = pmcounters.stalls_exception;
      tmp[counter::PAGE_CROSSING_FETCHBLOCKS] = pmcounters.page_crossing_fetchblocks;
      tmp[counter::NFP_EARLY_REDIRECT] = pmcounters.nfp_early_redirect;
      tmp[counter::NFP_LATE_REDIRECT] = pmcounters.nfp_late_redirect;
      tmp[counter::IFBUF_FULL_REDIRECT] = pmcounters.ifbuf_full_redirect;
      tmp[counter::NONSPEC_RESYNC] = pmcounters.nonspec_resync;
      tmp[counter::FAULT_RESYNC] = pmcounters.fault_resync;
      tmp[counter::FAULT_REFETCH] = pmcounters.fault_refetch;
      tmp[counter::CMODE_ENTRY] = pmcounters.cmode_entry;
      tmp[counter::BRANCH_MISSES] = pmcounters.branch_misses;
      tmp[counter::BR_RET_MISSES] = pmcounters.br_ret_misses;
      tmp[counter::IND_BR_MISSES] = pmcounters.ind_br_misses;
      tmp[counter::REL_BR_MISSES] = pmcounters.rel_br_misses;
      tmp[counter::SPEC_BRANCH_REDIRECT] = pmcounters.spec_branch_redirect;
      tmp[counter::SPEC_LSU_RESYNCS] = pmcounters.spec_lsu_resyncs;
      tmp[counter::TOTAL_FLUSHES] = pmcounters.total_flushes;
      tmp[counter::UOPS_DECODED] = pmcounters.uops_decoded;
      tmp[counter::L1I_READ_ACCESS] = pmcounters.l1i_read_access;
      tmp[counter::L1I_READ_MISS] = pmcounters.l1i_read_miss;
      tmp[counter::L1I_PREFETCH_ACCESS] = pmcounters.l1i_prefetch_access;
      tmp[counter::L1I_PREFETCH_MISS] = pmcounters.l1i_prefetch_miss;
      tmp[counter::ITLB_READ_ACCESS] = pmcounters.itlb_read_access;
      tmp[counter::ITLB_READ_MISS] = pmcounters.itlb_read_miss;
      tmp[counter::ITLB_PREFETCH_ACCESS] = pmcounters.itlb_prefetch_access;
      tmp[counter::ITLB_PREFETCH_MISS] = pmcounters.itlb_prefetch_miss;
      tmp[counter::IC_WAY_MISPRED] = pmcounters.ic_way_mispred;
      tmp[counter::RAS_UNDERFLOW] = pmcounters.ras_underflow;
      tmp[counter::RAS_OVERFLOW] = pmcounters.ras_overflow;
      tmp[counter::NUM_FETCHGROUPS] = pmcounters.num_fetchgroups;
      tmp[counter::BDP_BANK_CONFLICTS] = pmcounters.bdp_bank_conflicts;
      tmp[counter::BTP_BANK_CONFLICTS] = pmcounters.btp_bank_conflicts;
      tmp[counter::BPU_WRITES] = pmcounters.bpu_writes;
      tmp[counter::STALLED_CYCLES_FRONTEND] = pmcounters.stalled_cycles_frontend;
      tmp[counter::STALLED_CYCLES_BACKEND] = pmcounters.stalled_cycles_backend;
      tmp[counter::CYCLES_NO_INT_PRN] = pmcounters.cycles_no_int_prn;
      tmp[counter::CYCLES_NO_FP_PRN] = pmcounters.cycles_no_fp_prn;
      tmp[counter::CYCLES_NO_VEC_PRN] = pmcounters.cycles_no_vec_prn;
      tmp[counter::CYCLES_NO_VL_PRN] = pmcounters.cycles_no_vl_prn;
      tmp[counter::CYCLES_NO_VM_PRN] = pmcounters.cycles_no_vm_prn;
      tmp[counter::CYCLES_NO_ROB] = pmcounters.cycles_no_rob;
      tmp[counter::BRANCH_INSTRUCTIONS] = pmcounters.branch_instructions;
      tmp[counter::UOP_RETIRED] = pmcounters.uop_retired;
      tmp[counter::LD_RETIRED] = pmcounters.ld_retired;
      tmp[counter::ST_RETIRED] = pmcounters.st_retired;
      tmp[counter::INT_RETIRED] = pmcounters.int_retired;
      tmp[counter::CSR_RETIRED] = pmcounters.csr_retired;
      tmp[counter::BR_RET_RETIRED] = pmcounters.br_ret_retired;
      tmp[counter::IND_BR_RETIRED] = pmcounters.ind_br_retired;
      tmp[counter::REL_BR_RETIRED] = pmcounters.rel_br_retired;
      tmp[counter::FP_RETIRED] = pmcounters.fp_retired;
      tmp[counter::VEC_RETIRED] = pmcounters.vec_retired;
      tmp[counter::XFER_RETIRED] = pmcounters.xfer_retired;
      tmp[counter::UOP_CONFIRMED] = pmcounters.uop_confirmed;
      tmp[counter::UOP_ISSUED_INT] = pmcounters.uop_issued_int;
      tmp[counter::UOP_ISSUED_LDST] = pmcounters.uop_issued_ldst;
      tmp[counter::UOP_ISSUED_FP] = pmcounters.uop_issued_fp;
      tmp[counter::UOP_ISSUED_VEC] = pmcounters.uop_issued_vec;
      tmp[counter::BR_DIRECT_SPEC] = pmcounters.br_direct_spec;
      tmp[counter::BR_INDIRECT_SPEC] = pmcounters.br_indirect_spec;
      tmp[counter::BR_RET_SPEC] = pmcounters.br_ret_spec;
      tmp[counter::INT_EXECUTED] = pmcounters.int_executed;
      tmp[counter::FP_EXECUTED] = pmcounters.fp_executed;
      tmp[counter::VEC_EXECUTED] = pmcounters.vec_executed;
      tmp[counter::COMPRESSED_INSTRET] = pmcounters.compressed_instret;
      tmp[counter::CACHE_REFERENCES] = pmcounters.cache_references;
      tmp[counter::CACHE_MISSES] = pmcounters.cache_misses;
      tmp[counter::TLB_INVALIDATES] = pmcounters.tlb_invalidates;
      tmp[counter::L1D_READ_ACCESS_ALIGNED] = pmcounters.l1d_read_access_aligned;
      tmp[counter::L1D_READ_ACCESS_CLC] = pmcounters.l1d_read_access_clc;
      tmp[counter::L1D_READ_ACCESS_4KX] = pmcounters.l1d_read_access_4kx;
      tmp[counter::L1D_READ_ACCESS_ALL] = pmcounters.l1d_read_access_all;
      tmp[counter::L1D_WRITE_ACCESS_ALIGNED] = pmcounters.l1d_write_access_aligned;
      tmp[counter::L1D_WRITE_ACCESS_CLC] = pmcounters.l1d_write_access_clc;
      tmp[counter::L1D_WRITE_ACCESS_4KX] = pmcounters.l1d_write_access_4kx;
      tmp[counter::L1D_WRITE_ACCESS_ALL] = pmcounters.l1d_write_access_all;
      tmp[counter::L1D_PREFETCH_ACCESS_ALIGNED] = pmcounters.l1d_prefetch_access_aligned;
      tmp[counter::L1D_PREFETCH_ACCESS_CLC] = pmcounters.l1d_prefetch_access_clc;
      tmp[counter::L1D_PREFETCH_ACCESS_4KX] = pmcounters.l1d_prefetch_access_4kx;
      tmp[counter::L1D_PREFETCH_ACCESS_ALL] = pmcounters.l1d_prefetch_access_all;
      tmp[counter::L1D_MMU_ACCESS] = pmcounters.l1d_mmu_access;
      tmp[counter::L1D_SNOOP_ACCESS] = pmcounters.l1d_snoop_access;
      tmp[counter::L1D_ACCESS_ALL] = pmcounters.l1d_access_all;
      tmp[counter::L1D_READ_MISS] = pmcounters.l1d_read_miss;
      tmp[counter::L1D_WRITE_MISS] = pmcounters.l1d_write_miss;
      tmp[counter::L1D_PREFETCH_MISS] = pmcounters.l1d_prefetch_miss;
      tmp[counter::L1D_MMU_MISS] = pmcounters.l1d_mmu_miss;
      tmp[counter::L1D_SNOOP_MISS] = pmcounters.l1d_snoop_miss;
      tmp[counter::L1D_MISS_ALL] = pmcounters.l1d_miss_all;
      tmp[counter::L1D_CACHE_INVALIDATE_SNOOP] = pmcounters.l1d_cache_invalidate_snoop;
      tmp[counter::L1D_CACHE_INVALIDATE_CMO] = pmcounters.l1d_cache_invalidate_cmo;
      tmp[counter::L1D_CACHE_INVALIDATE_LOAD_EVICTION] = pmcounters.l1d_cache_invalidate_load_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_STORE_EVICTION] = pmcounters.l1d_cache_invalidate_store_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_PREFETCH_EVICTION] = pmcounters.l1d_cache_invalidate_prefetch_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_ALL] = pmcounters.l1d_cache_invalidate_all;
      tmp[counter::UTLB_MISS] = pmcounters.utlb_miss;
      tmp[counter::DTLB_READ_ACCESS] = pmcounters.dtlb_read_access;
      tmp[counter::DTLB_WRITE_ACCESS] = pmcounters.dtlb_write_access;
      tmp[counter::DTLB_PREFETCH_ACCESS] = pmcounters.dtlb_prefetch_access;
      tmp[counter::DTLB_ACCESS_4K] = pmcounters.dtlb_access_4k;
      tmp[counter::DTLB_ACCESS_HUGEPAGE] = pmcounters.dtlb_access_hugepage;
      tmp[counter::DTLB_ACCESS_CACHEABLE] = pmcounters.dtlb_access_cacheable;
      tmp[counter::DTLB_ACCESS_NONCACHEABLE] = pmcounters.dtlb_access_noncacheable;
      tmp[counter::DTLB_ACCESS_ALL] = pmcounters.dtlb_access_all;
      tmp[counter::DTLB_READ_MISS] = pmcounters.dtlb_read_miss;
      tmp[counter::DTLB_WRITE_MISS] = pmcounters.dtlb_write_miss;
      tmp[counter::DTLB_PREFETCH_MISS] = pmcounters.dtlb_prefetch_miss;
      tmp[counter::DTLB_MISS_4K] = pmcounters.dtlb_miss_4k;
      tmp[counter::DTLB_MISS_HUGEPAGE] = pmcounters.dtlb_miss_hugepage;
      tmp[counter::DTLB_MISS_ALL] = pmcounters.dtlb_miss_all;
      tmp[counter::LEAF_TLB_ACCESS_LS] = pmcounters.leaf_tlb_access_ls;
      tmp[counter::LEAF_TLB_ACCESS_FE] = pmcounters.leaf_tlb_access_fe;
      tmp[counter::LEAF_TLB_ACCESS_PREFETCH] = pmcounters.leaf_tlb_access_prefetch;
      tmp[counter::LEAF_TLB_MISS_LS] = pmcounters.leaf_tlb_miss_ls;
      tmp[counter::LEAF_TLB_MISS_FE] = pmcounters.leaf_tlb_miss_fe;
      tmp[counter::LEAF_TLB_MISS_PREFETCH] = pmcounters.leaf_tlb_miss_prefetch;
      tmp[counter::NONLEAF_TLB_ACCESS_LS] = pmcounters.nonleaf_tlb_access_ls;
      tmp[counter::NONLEAF_TLB_ACCESS_FE] = pmcounters.nonleaf_tlb_access_fe;
      tmp[counter::NONLEAF_TLB_ACCESS_PREFETCH] = pmcounters.nonleaf_tlb_access_prefetch;
      tmp[counter::NONLEAF_TLB_MISS_LS] = pmcounters.nonleaf_tlb_miss_ls;
      tmp[counter::NONLEAF_TLB_MISS_FE] = pmcounters.nonleaf_tlb_miss_fe;
      tmp[counter::NONLEAF_TLB_MISS_PREFETCH] = pmcounters.nonleaf_tlb_miss_prefetch;
      tmp[counter::PAGE_WALKS] = pmcounters.page_walks;
      tmp[counter::STALLS_MEM_L1D_MISS] = pmcounters.stalls_mem_l1d_miss;
      tmp[counter::STALLS_MEM_STORES] = pmcounters.stalls_mem_stores;
      tmp[counter::STALLS_MEM_L1DTLB_MISS] = pmcounters.stalls_mem_l1dtlb_miss;
      tmp[counter::LSU_RESYNCS_RAW] = pmcounters.lsu_resyncs_raw;
      tmp[counter::LSU_RESYNCS_RAR] = pmcounters.lsu_resyncs_rar;
      tmp[counter::LSU_RESYNCS_ALL] = pmcounters.lsu_resyncs_all;
      tmp[counter::STLF_HITS] = pmcounters.stlf_hits;
      tmp[counter::LS_REPLAY_LOAD] = pmcounters.ls_replay_load;
      tmp[counter::LS_REPLAY_STORE] = pmcounters.ls_replay_store;
      tmp[counter::LS_REPLAY_PREFETCH] = pmcounters.ls_replay_prefetch;
      tmp[counter::LS_REPLAY_MMU] = pmcounters.ls_replay_mmu;
      tmp[counter::LS_REPLAY_ALL] = pmcounters.ls_replay_all;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_LOAD] = pmcounters.ls_way_predictor_replay_load;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_STORE] = pmcounters.ls_way_predictor_replay_store;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_PREFETCH] = pmcounters.ls_way_predictor_replay_prefetch;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_MMU] = pmcounters.ls_way_predictor_replay_mmu;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_ALL] = pmcounters.ls_way_predictor_replay_all;
      tmp[counter::SIPT_REPLAY_LOAD] = pmcounters.sipt_replay_load;
      tmp[counter::SIPT_REPLAY_STORE] = pmcounters.sipt_replay_store;
      tmp[counter::SIPT_REPLAY_PREFETCH] = pmcounters.sipt_replay_prefetch;
      tmp[counter::SIPT_REPLAY_MMU] = pmcounters.sipt_replay_mmu;
      tmp[counter::SIPT_REPLAY_ALL] = pmcounters.sipt_replay_all;
      tmp[counter::STLF_REPLAY_LOAD] = pmcounters.stlf_replay_load;
      tmp[counter::STLF_REPLAY_STORE] = pmcounters.stlf_replay_store;
      tmp[counter::STLF_REPLAY_PREFETCH] = pmcounters.stlf_replay_prefetch;
      tmp[counter::STLF_REPLAY_MMU] = pmcounters.stlf_replay_mmu;
      tmp[counter::STLF_REPLAY_ALL] = pmcounters.stlf_replay_all;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_LOAD] = pmcounters.tag_bank_conflict_replay_load;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_STORE] = pmcounters.tag_bank_conflict_replay_store;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_PREFETCH] = pmcounters.tag_bank_conflict_replay_prefetch;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_MMU] = pmcounters.tag_bank_conflict_replay_mmu;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_ALL] = pmcounters.tag_bank_conflict_replay_all;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_LOAD] = pmcounters.data_bank_conflict_replay_load;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_STORE] = pmcounters.data_bank_conflict_replay_store;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_PREFETCH] = pmcounters.data_bank_conflict_replay_prefetch;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_MMU] = pmcounters.data_bank_conflict_replay_mmu;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_ALL] = pmcounters.data_bank_conflict_replay_all;
      tmp[counter::FILLBUF_HIT_REPLAY_LOAD] = pmcounters.fillbuf_hit_replay_load;
      tmp[counter::FILLBUF_HIT_REPLAY_STORE] = pmcounters.fillbuf_hit_replay_store;
      tmp[counter::FILLBUF_HIT_REPLAY_PREFETCH] = pmcounters.fillbuf_hit_replay_prefetch;
      tmp[counter::FILLBUF_HIT_REPLAY_MMU] = pmcounters.fillbuf_hit_replay_mmu;
      tmp[counter::FILLBUF_HIT_REPLAY_ALL] = pmcounters.fillbuf_hit_replay_all;
      tmp[counter::TRANSBUF_HIT_REPLAY_LOAD] = pmcounters.transbuf_hit_replay_load;
      tmp[counter::TRANSBUF_HIT_REPLAY_STORE] = pmcounters.transbuf_hit_replay_store;
      tmp[counter::TRANSBUF_HIT_REPLAY_PREFETCH] = pmcounters.transbuf_hit_replay_prefetch;
      tmp[counter::TRANSBUF_HIT_REPLAY_MMU] = pmcounters.transbuf_hit_replay_mmu;
      tmp[counter::TRANSBUF_HIT_REPLAY_ALL] = pmcounters.transbuf_hit_replay_all;
      tmp[counter::REQBUF_HIT_REPLAY_LOAD] = pmcounters.reqbuf_hit_replay_load;
      tmp[counter::REQBUF_HIT_REPLAY_STORE] = pmcounters.reqbuf_hit_replay_store;
      tmp[counter::REQBUF_HIT_REPLAY_PREFETCH] = pmcounters.reqbuf_hit_replay_prefetch;
      tmp[counter::REQBUF_HIT_REPLAY_MMU] = pmcounters.reqbuf_hit_replay_mmu;
      tmp[counter::REQBUF_HIT_REPLAY_ALL] = pmcounters.reqbuf_hit_replay_all;
      tmp[counter::DTLB_REPLAY_LOAD] = pmcounters.dtlb_replay_load;
      tmp[counter::DTLB_REPLAY_STORE] = pmcounters.dtlb_replay_store;
      tmp[counter::DTLB_REPLAY_PREFETCH] = pmcounters.dtlb_replay_prefetch;
      tmp[counter::DTLB_REPLAY_MMU] = pmcounters.dtlb_replay_mmu;
      tmp[counter::DTLB_REPLAY_ALL] = pmcounters.dtlb_replay_all;
      tmp[counter::RAR_CANNOT_ALLOC] = pmcounters.rar_cannot_alloc;
      tmp[counter::RAW_CANNOT_ALLOC] = pmcounters.raw_cannot_alloc;
      tmp[counter::LDQ_CANNOT_ALLOC] = pmcounters.ldq_cannot_alloc;
      tmp[counter::SMB_CANNOT_ALLOC] = pmcounters.smb_cannot_alloc;
      tmp[counter::REQBUF_CANNOT_ALLOC_LOAD] = pmcounters.reqbuf_cannot_alloc_load;
      tmp[counter::REQBUF_CANNOT_ALLOC_STORE] = pmcounters.reqbuf_cannot_alloc_store;
      tmp[counter::REQBUF_CANNOT_ALLOC_PREFETCH] = pmcounters.reqbuf_cannot_alloc_prefetch;
      tmp[counter::REQBUF_CANNOT_ALLOC_MMU] = pmcounters.reqbuf_cannot_alloc_mmu;
      tmp[counter::REQBUF_CANNOT_ALLOC_ALL] = pmcounters.reqbuf_cannot_alloc_all;
      tmp[counter::FILLBUF_CANNOT_ALLOC] = pmcounters.fillbuf_cannot_alloc;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_LOAD] = pmcounters.transbuf_cannot_alloc_load;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_STORE] = pmcounters.transbuf_cannot_alloc_store;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_PREFETCH] = pmcounters.transbuf_cannot_alloc_prefetch;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_MMU] = pmcounters.transbuf_cannot_alloc_mmu;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_ALL] = pmcounters.transbuf_cannot_alloc_all;
      tmp[counter::PCB_CANNOT_ALLOC_LOAD] = pmcounters.pcb_cannot_alloc_load;
      tmp[counter::PCB_CANNOT_ALLOC_STORE] = pmcounters.pcb_cannot_alloc_store;
      tmp[counter::PCB_CANNOT_ALLOC_ALL] = pmcounters.pcb_cannot_alloc_all;
      tmp[counter::UDB_CANNOT_ALLOC] = pmcounters.udb_cannot_alloc;
      tmp[counter::UDB_DATA_RETURN] = pmcounters.udb_data_return;
      tmp[counter::UDB_LOST] = pmcounters.udb_lost;
      tmp[counter::UWP_ACCESS] = pmcounters.uwp_access;
      tmp[counter::UWP_MISS] = pmcounters.uwp_miss;
      tmp[counter::UWP_TRUE_HIT] = pmcounters.uwp_true_hit;
      tmp[counter::WP_ACCESS] = pmcounters.wp_access;
      tmp[counter::WP_MISS] = pmcounters.wp_miss;
      tmp[counter::WP_TRUE_HIT] = pmcounters.wp_true_hit;
      tmp[counter::MDP_CORRECT_PREDICTION] = pmcounters.mdp_correct_prediction;
      tmp[counter::MDP_FALSE_HIT] = pmcounters.mdp_false_hit;
      tmp[counter::MDP_FALSE_MISS] = pmcounters.mdp_false_miss;
      tmp[counter::MDP_TOTAL_PREDICTION] = pmcounters.mdp_total_prediction;
      tmp[counter::ATOMICS_RETIRED] = pmcounters.atomics_retired;
      tmp[counter::LDST_MASKED_NANO] = pmcounters.ldst_masked_nano;
      tmp[counter::LD_EXECUTED_NANO] = pmcounters.ld_executed_nano;
      tmp[counter::ST_EXECUTED_NANO] = pmcounters.st_executed_nano;
      tmp[counter::PFC_AGT_CANNOT_ALLOC] = pmcounters.pfc_agt_cannot_alloc;
      tmp[counter::PFC_AGT_EVICT] = pmcounters.pfc_agt_evict;
      tmp[counter::PFC_PHT_CANNOT_ALLOC] = pmcounters.pfc_pht_cannot_alloc;
      tmp[counter::PFC_PHT_LOOKUP] = pmcounters.pfc_pht_lookup;
      tmp[counter::PFC_PHT_HIT] = pmcounters.pfc_pht_hit;
      tmp[counter::PFC_PRT_CANNOT_ALLOC] = pmcounters.pfc_prt_cannot_alloc;
      tmp[counter::PFC_NO_TLB_CREDIT_STALLS] = pmcounters.pfc_no_tlb_credit_stalls;
      tmp[counter::PFC_NO_TAG_CREDIT_STALLS] = pmcounters.pfc_no_tag_credit_stalls;
      tmp[counter::PFC_PREFETCHES_SENT] = pmcounters.pfc_prefetches_sent;
      tmp[counter::PFC_PREFETCHES_HIT] = pmcounters.pfc_prefetches_hit;
      tmp[counter::PFC_PREFETCHES_LATE] = pmcounters.pfc_prefetches_late;
      tmp[counter::PFC_USELESS_PREFETCHES] = pmcounters.pfc_useless_prefetches;

      return tmp;
    }


    const std::unordered_map<counter, std::string_view> to_string =
      {
      {CPU_CYCLES,"cpu_cycles"},
      {INSTRUCTIONS,"instructions"},
      {M_MODE_CYCLES,"m_mode_cycles"},
      {M_MODE_INSTRET,"m_mode_instret"},
      {S_MODE_CYCLES,"s_mode_cycles"},
      {S_MODE_INSTRET,"s_mode_instret"},
      {U_MODE_CYCLES,"u_mode_cycles"},
      {U_MODE_INSTRET,"u_mode_instret"},
      {REF_CPU_CYCLES,"ref_cpu_cycles"},
      {STALLS_BST_FULL,"stalls_bst_full"},
      {STALLS_PFX_FULL,"stalls_pfx_full"},
      {STALLS_INDIRECT_MISS,"stalls_indirect_miss"},
      {STALLS_ICACHE_MISS,"stalls_icache_miss"},
      {STALLS_ITLB_MISS,"stalls_itlb_miss"},
      {STALLS_IRB_FULL,"stalls_irb_full"},
      {STALLS_IFBUF_FULL,"stalls_ifbuf_full"},
      {STALLS_EXCEPTION,"stalls_exception"},
      {PAGE_CROSSING_FETCHBLOCKS,"page_crossing_fetchblocks"},
      {NFP_EARLY_REDIRECT,"nfp_early_redirect"},
      {NFP_LATE_REDIRECT,"nfp_late_redirect"},
      {IFBUF_FULL_REDIRECT,"ifbuf_full_redirect"},
      {NONSPEC_RESYNC,"nonspec_resync"},
      {FAULT_RESYNC,"fault_resync"},
      {FAULT_REFETCH,"fault_refetch"},
      {CMODE_ENTRY,"cmode_entry"},
      {BRANCH_MISSES,"branch_misses"},
      {BR_RET_MISSES,"br_ret_misses"},
      {IND_BR_MISSES,"ind_br_misses"},
      {REL_BR_MISSES,"rel_br_misses"},
      {SPEC_BRANCH_REDIRECT,"spec_branch_redirect"},
      {SPEC_LSU_RESYNCS,"spec_lsu_resyncs"},
      {TOTAL_FLUSHES,"total_flushes"},
      {UOPS_DECODED,"uops_decoded"},
      {L1I_READ_ACCESS,"l1i_read_access"},
      {L1I_READ_MISS,"l1i_read_miss"},
      {L1I_PREFETCH_ACCESS,"l1i_prefetch_access"},
      {L1I_PREFETCH_MISS,"l1i_prefetch_miss"},
      {ITLB_READ_ACCESS,"itlb_read_access"},
      {ITLB_READ_MISS,"itlb_read_miss"},
      {ITLB_PREFETCH_ACCESS,"itlb_prefetch_access"},
      {ITLB_PREFETCH_MISS,"itlb_prefetch_miss"},
      {IC_WAY_MISPRED,"ic_way_mispred"},
      {RAS_UNDERFLOW,"ras_underflow"},
      {RAS_OVERFLOW,"ras_overflow"},
      {NUM_FETCHGROUPS,"num_fetchgroups"},
      {BDP_BANK_CONFLICTS,"bdp_bank_conflicts"},
      {BTP_BANK_CONFLICTS,"btp_bank_conflicts"},
      {BPU_WRITES,"bpu_writes"},
      {STALLED_CYCLES_FRONTEND,"stalled_cycles_frontend"},
      {STALLED_CYCLES_BACKEND,"stalled_cycles_backend"},
      {CYCLES_NO_INT_PRN,"cycles_no_int_prn"},
      {CYCLES_NO_FP_PRN,"cycles_no_fp_prn"},
      {CYCLES_NO_VEC_PRN,"cycles_no_vec_prn"},
      {CYCLES_NO_VL_PRN,"cycles_no_vl_prn"},
      {CYCLES_NO_VM_PRN,"cycles_no_vm_prn"},
      {CYCLES_NO_ROB,"cycles_no_rob"},
      {BRANCH_INSTRUCTIONS,"branch_instructions"},
      {UOP_RETIRED,"uop_retired"},
      {LD_RETIRED,"ld_retired"},
      {ST_RETIRED,"st_retired"},
      {INT_RETIRED,"int_retired"},
      {CSR_RETIRED,"csr_retired"},
      {BR_RET_RETIRED,"br_ret_retired"},
      {IND_BR_RETIRED,"ind_br_retired"},
      {REL_BR_RETIRED,"rel_br_retired"},
      {FP_RETIRED,"fp_retired"},
      {VEC_RETIRED,"vec_retired"},
      {XFER_RETIRED,"xfer_retired"},
      {UOP_CONFIRMED,"uop_confirmed"},
      {UOP_ISSUED_INT,"uop_issued_int"},
      {UOP_ISSUED_LDST,"uop_issued_ldst"},
      {UOP_ISSUED_FP,"uop_issued_fp"},
      {UOP_ISSUED_VEC,"uop_issued_vec"},
      {BR_DIRECT_SPEC,"br_direct_spec"},
      {BR_INDIRECT_SPEC,"br_indirect_spec"},
      {BR_RET_SPEC,"br_ret_spec"},
      {INT_EXECUTED,"int_executed"},
      {FP_EXECUTED,"fp_executed"},
      {VEC_EXECUTED,"vec_executed"},
      {COMPRESSED_INSTRET,"compressed_instret"},
      {CACHE_REFERENCES,"cache_references"},
      {CACHE_MISSES,"cache_misses"},
      {TLB_INVALIDATES,"tlb_invalidates"},
      {L1D_READ_ACCESS_ALIGNED,"l1d_read_access_aligned"},
      {L1D_READ_ACCESS_CLC,"l1d_read_access_clc"},
      {L1D_READ_ACCESS_4KX,"l1d_read_access_4kx"},
      {L1D_READ_ACCESS_ALL,"l1d_read_access_all"},
      {L1D_WRITE_ACCESS_ALIGNED,"l1d_write_access_aligned"},
      {L1D_WRITE_ACCESS_CLC,"l1d_write_access_clc"},
      {L1D_WRITE_ACCESS_4KX,"l1d_write_access_4kx"},
      {L1D_WRITE_ACCESS_ALL,"l1d_write_access_all"},
      {L1D_PREFETCH_ACCESS_ALIGNED,"l1d_prefetch_access_aligned"},
      {L1D_PREFETCH_ACCESS_CLC,"l1d_prefetch_access_clc"},
      {L1D_PREFETCH_ACCESS_4KX,"l1d_prefetch_access_4kx"},
      {L1D_PREFETCH_ACCESS_ALL,"l1d_prefetch_access_all"},
      {L1D_MMU_ACCESS,"l1d_mmu_access"},
      {L1D_SNOOP_ACCESS,"l1d_snoop_access"},
      {L1D_ACCESS_ALL,"l1d_access_all"},
      {L1D_READ_MISS,"l1d_read_miss"},
      {L1D_WRITE_MISS,"l1d_write_miss"},
      {L1D_PREFETCH_MISS,"l1d_prefetch_miss"},
      {L1D_MMU_MISS,"l1d_mmu_miss"},
      {L1D_SNOOP_MISS,"l1d_snoop_miss"},
      {L1D_MISS_ALL,"l1d_miss_all"},
      {L1D_CACHE_INVALIDATE_SNOOP,"l1d_cache_invalidate_snoop"},
      {L1D_CACHE_INVALIDATE_CMO,"l1d_cache_invalidate_cmo"},
      {L1D_CACHE_INVALIDATE_LOAD_EVICTION,"l1d_cache_invalidate_load_eviction"},
      {L1D_CACHE_INVALIDATE_STORE_EVICTION,"l1d_cache_invalidate_store_eviction"},
      {L1D_CACHE_INVALIDATE_PREFETCH_EVICTION,"l1d_cache_invalidate_prefetch_eviction"},
      {L1D_CACHE_INVALIDATE_ALL,"l1d_cache_invalidate_all"},
      {UTLB_MISS,"utlb_miss"},
      {DTLB_READ_ACCESS,"dtlb_read_access"},
      {DTLB_WRITE_ACCESS,"dtlb_write_access"},
      {DTLB_PREFETCH_ACCESS,"dtlb_prefetch_access"},
      {DTLB_ACCESS_4K,"dtlb_access_4k"},
      {DTLB_ACCESS_HUGEPAGE,"dtlb_access_hugepage"},
      {DTLB_ACCESS_CACHEABLE,"dtlb_access_cacheable"},
      {DTLB_ACCESS_NONCACHEABLE,"dtlb_access_noncacheable"},
      {DTLB_ACCESS_ALL,"dtlb_access_all"},
      {DTLB_READ_MISS,"dtlb_read_miss"},
      {DTLB_WRITE_MISS,"dtlb_write_miss"},
      {DTLB_PREFETCH_MISS,"dtlb_prefetch_miss"},
      {DTLB_MISS_4K,"dtlb_miss_4k"},
      {DTLB_MISS_HUGEPAGE,"dtlb_miss_hugepage"},
      {DTLB_MISS_ALL,"dtlb_miss_all"},
      {LEAF_TLB_ACCESS_LS,"leaf_tlb_access_ls"},
      {LEAF_TLB_ACCESS_FE,"leaf_tlb_access_fe"},
      {LEAF_TLB_ACCESS_PREFETCH,"leaf_tlb_access_prefetch"},
      {LEAF_TLB_MISS_LS,"leaf_tlb_miss_ls"},
      {LEAF_TLB_MISS_FE,"leaf_tlb_miss_fe"},
      {LEAF_TLB_MISS_PREFETCH,"leaf_tlb_miss_prefetch"},
      {NONLEAF_TLB_ACCESS_LS,"nonleaf_tlb_access_ls"},
      {NONLEAF_TLB_ACCESS_FE,"nonleaf_tlb_access_fe"},
      {NONLEAF_TLB_ACCESS_PREFETCH,"nonleaf_tlb_access_prefetch"},
      {NONLEAF_TLB_MISS_LS,"nonleaf_tlb_miss_ls"},
      {NONLEAF_TLB_MISS_FE,"nonleaf_tlb_miss_fe"},
      {NONLEAF_TLB_MISS_PREFETCH,"nonleaf_tlb_miss_prefetch"},
      {PAGE_WALKS,"page_walks"},
      {STALLS_MEM_L1D_MISS,"stalls_mem_l1d_miss"},
      {STALLS_MEM_STORES,"stalls_mem_stores"},
      {STALLS_MEM_L1DTLB_MISS,"stalls_mem_l1dtlb_miss"},
      {LSU_RESYNCS_RAW,"lsu_resyncs_raw"},
      {LSU_RESYNCS_RAR,"lsu_resyncs_rar"},
      {LSU_RESYNCS_ALL,"lsu_resyncs_all"},
      {STLF_HITS,"stlf_hits"},
      {LS_REPLAY_LOAD,"ls_replay_load"},
      {LS_REPLAY_STORE,"ls_replay_store"},
      {LS_REPLAY_PREFETCH,"ls_replay_prefetch"},
      {LS_REPLAY_MMU,"ls_replay_mmu"},
      {LS_REPLAY_ALL,"ls_replay_all"},
      {LS_WAY_PREDICTOR_REPLAY_LOAD,"ls_way_predictor_replay_load"},
      {LS_WAY_PREDICTOR_REPLAY_STORE,"ls_way_predictor_replay_store"},
      {LS_WAY_PREDICTOR_REPLAY_PREFETCH,"ls_way_predictor_replay_prefetch"},
      {LS_WAY_PREDICTOR_REPLAY_MMU,"ls_way_predictor_replay_mmu"},
      {LS_WAY_PREDICTOR_REPLAY_ALL,"ls_way_predictor_replay_all"},
      {SIPT_REPLAY_LOAD,"sipt_replay_load"},
      {SIPT_REPLAY_STORE,"sipt_replay_store"},
      {SIPT_REPLAY_PREFETCH,"sipt_replay_prefetch"},
      {SIPT_REPLAY_MMU,"sipt_replay_mmu"},
      {SIPT_REPLAY_ALL,"sipt_replay_all"},
      {STLF_REPLAY_LOAD,"stlf_replay_load"},
      {STLF_REPLAY_STORE,"stlf_replay_store"},
      {STLF_REPLAY_PREFETCH,"stlf_replay_prefetch"},
      {STLF_REPLAY_MMU,"stlf_replay_mmu"},
      {STLF_REPLAY_ALL,"stlf_replay_all"},
      {TAG_BANK_CONFLICT_REPLAY_LOAD,"tag_bank_conflict_replay_load"},
      {TAG_BANK_CONFLICT_REPLAY_STORE,"tag_bank_conflict_replay_store"},
      {TAG_BANK_CONFLICT_REPLAY_PREFETCH,"tag_bank_conflict_replay_prefetch"},
      {TAG_BANK_CONFLICT_REPLAY_MMU,"tag_bank_conflict_replay_mmu"},
      {TAG_BANK_CONFLICT_REPLAY_ALL,"tag_bank_conflict_replay_all"},
      {DATA_BANK_CONFLICT_REPLAY_LOAD,"data_bank_conflict_replay_load"},
      {DATA_BANK_CONFLICT_REPLAY_STORE,"data_bank_conflict_replay_store"},
      {DATA_BANK_CONFLICT_REPLAY_PREFETCH,"data_bank_conflict_replay_prefetch"},
      {DATA_BANK_CONFLICT_REPLAY_MMU,"data_bank_conflict_replay_mmu"},
      {DATA_BANK_CONFLICT_REPLAY_ALL,"data_bank_conflict_replay_all"},
      {FILLBUF_HIT_REPLAY_LOAD,"fillbuf_hit_replay_load"},
      {FILLBUF_HIT_REPLAY_STORE,"fillbuf_hit_replay_store"},
      {FILLBUF_HIT_REPLAY_PREFETCH,"fillbuf_hit_replay_prefetch"},
      {FILLBUF_HIT_REPLAY_MMU,"fillbuf_hit_replay_mmu"},
      {FILLBUF_HIT_REPLAY_ALL,"fillbuf_hit_replay_all"},
      {TRANSBUF_HIT_REPLAY_LOAD,"transbuf_hit_replay_load"},
      {TRANSBUF_HIT_REPLAY_STORE,"transbuf_hit_replay_store"},
      {TRANSBUF_HIT_REPLAY_PREFETCH,"transbuf_hit_replay_prefetch"},
      {TRANSBUF_HIT_REPLAY_MMU,"transbuf_hit_replay_mmu"},
      {TRANSBUF_HIT_REPLAY_ALL,"transbuf_hit_replay_all"},
      {REQBUF_HIT_REPLAY_LOAD,"reqbuf_hit_replay_load"},
      {REQBUF_HIT_REPLAY_STORE,"reqbuf_hit_replay_store"},
      {REQBUF_HIT_REPLAY_PREFETCH,"reqbuf_hit_replay_prefetch"},
      {REQBUF_HIT_REPLAY_MMU,"reqbuf_hit_replay_mmu"},
      {REQBUF_HIT_REPLAY_ALL,"reqbuf_hit_replay_all"},
      {DTLB_REPLAY_LOAD,"dtlb_replay_load"},
      {DTLB_REPLAY_STORE,"dtlb_replay_store"},
      {DTLB_REPLAY_PREFETCH,"dtlb_replay_prefetch"},
      {DTLB_REPLAY_MMU,"dtlb_replay_mmu"},
      {DTLB_REPLAY_ALL,"dtlb_replay_all"},
      {RAR_CANNOT_ALLOC,"rar_cannot_alloc"},
      {RAW_CANNOT_ALLOC,"raw_cannot_alloc"},
      {LDQ_CANNOT_ALLOC,"ldq_cannot_alloc"},
      {SMB_CANNOT_ALLOC,"smb_cannot_alloc"},
      {REQBUF_CANNOT_ALLOC_LOAD,"reqbuf_cannot_alloc_load"},
      {REQBUF_CANNOT_ALLOC_STORE,"reqbuf_cannot_alloc_store"},
      {REQBUF_CANNOT_ALLOC_PREFETCH,"reqbuf_cannot_alloc_prefetch"},
      {REQBUF_CANNOT_ALLOC_MMU,"reqbuf_cannot_alloc_mmu"},
      {REQBUF_CANNOT_ALLOC_ALL,"reqbuf_cannot_alloc_all"},
      {FILLBUF_CANNOT_ALLOC,"fillbuf_cannot_alloc"},
      {TRANSBUF_CANNOT_ALLOC_LOAD,"transbuf_cannot_alloc_load"},
      {TRANSBUF_CANNOT_ALLOC_STORE,"transbuf_cannot_alloc_store"},
      {TRANSBUF_CANNOT_ALLOC_PREFETCH,"transbuf_cannot_alloc_prefetch"},
      {TRANSBUF_CANNOT_ALLOC_MMU,"transbuf_cannot_alloc_mmu"},
      {TRANSBUF_CANNOT_ALLOC_ALL,"transbuf_cannot_alloc_all"},
      {PCB_CANNOT_ALLOC_LOAD,"pcb_cannot_alloc_load"},
      {PCB_CANNOT_ALLOC_STORE,"pcb_cannot_alloc_store"},
      {PCB_CANNOT_ALLOC_ALL,"pcb_cannot_alloc_all"},
      {UDB_CANNOT_ALLOC,"udb_cannot_alloc"},
      {UDB_DATA_RETURN,"udb_data_return"},
      {UDB_LOST,"udb_lost"},
      {UWP_ACCESS,"uwp_access"},
      {UWP_MISS,"uwp_miss"},
      {UWP_TRUE_HIT,"uwp_true_hit"},
      {WP_ACCESS,"wp_access"},
      {WP_MISS,"wp_miss"},
      {WP_TRUE_HIT,"wp_true_hit"},
      {MDP_CORRECT_PREDICTION,"mdp_correct_prediction"},
      {MDP_FALSE_HIT,"mdp_false_hit"},
      {MDP_FALSE_MISS,"mdp_false_miss"},
      {MDP_TOTAL_PREDICTION,"mdp_total_prediction"},
      {ATOMICS_RETIRED,"atomics_retired"},
      {LDST_MASKED_NANO,"ldst_masked_nano"},
      {LD_EXECUTED_NANO,"ld_executed_nano"},
      {ST_EXECUTED_NANO,"st_executed_nano"},
      {PFC_AGT_CANNOT_ALLOC,"pfc_agt_cannot_alloc"},
      {PFC_AGT_EVICT,"pfc_agt_evict"},
      {PFC_PHT_CANNOT_ALLOC,"pfc_pht_cannot_alloc"},
      {PFC_PHT_LOOKUP,"pfc_pht_lookup"},
      {PFC_PHT_HIT,"pfc_pht_hit"},
      {PFC_PRT_CANNOT_ALLOC,"pfc_prt_cannot_alloc"},
      {PFC_NO_TLB_CREDIT_STALLS,"pfc_no_tlb_credit_stalls"},
      {PFC_NO_TAG_CREDIT_STALLS,"pfc_no_tag_credit_stalls"},
      {PFC_PREFETCHES_SENT,"pfc_prefetches_sent"},
      {PFC_PREFETCHES_HIT,"pfc_prefetches_hit"},
      {PFC_PREFETCHES_LATE,"pfc_prefetches_late"},
      {PFC_USELESS_PREFETCHES,"pfc_useless_prefetches"},
    };

  pmu(cvm::topology::loc_t, unsigned);
  ~pmu();

  void report();
  void ipc_check();

  // snapshot current counter values, to be used in perf region
  void perf_region_start() {
    assert(perf_region.size() == counters.size());

    for (size_t i = 0; i < perf_region.size(); i++)
      perf_region[i] = counters[i];

    perf_start_cycle = counters[CPU_CYCLES];
  }

  void perf_region_end() {
    assert(perf_region.size() == counters.size());

    for (size_t i = 0; i < perf_region.size(); i++) {
      perf_region[i] = counters[i] - perf_region[i];
    }

    perf_end_cycle = counters[CPU_CYCLES];
  }

  bool is_within_range(double, double, int);
  void process(const rv_tester_transactions::pmu::pmcounters<> &pmcounters);
  void process(const rv_tester::terminate_called_fast &);
  std::string trigger_str(const rv_tester_transactions::pmu::pmcounters<> &pmcounters);

private:
  cvm::file_logger log;
  cvm::topology::loc_t loc_;
  unsigned id_;

  std::vector<uint64_t> counters;

  uint64_t perf_start_cycle = 0;
  uint64_t perf_end_cycle = 0;
  std::vector<uint64_t> perf_region;

  bool terminated_ = false;
  bool sync_terminate_ = false;
};
