module pmu
import rv_tester_params::*;
#(
  parameter int NUM = -1,
  parameter int NRET = 1,
  `TOPOLOGY,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PARAMS
)(
  input tb_clk,
  input clk,
  input reset,
  input longint unsigned clocks,
  input pmci_t pmci,
  input rvfi_t [NRET-1:0] rvfi,
  input bit terminate,
  `RV_TESTER_TRANSACTIONS_PMU_OUTPUT_PORTS
);

    int unsigned location = cvm_topology::nil;
    longint unsigned period = 0;
    bit sync;
    assign sync = period != '0;
    bit perf_enabled = '0;

    always @(posedge tb_clk) begin
        if (reset) begin
            /* verilator lint_off BLKSEQ */
            location = cvm_topology::get_location(topology.TOP.PLATFORM.PMCI.ID, NUM);
            perf_enabled = (cvm_plusargs::get_bool("perf") != '0) & (location != cvm_topology::nil);
            period = cvm_plusargs::get_ulongint("sync_pmcounters_period");
            /* verilator lint_on BLKSEQ */
        end
    end

    longint unsigned cpu_cycles = 0;
    longint unsigned pmcounter [EVENT_COUNT] = '{default:0};

    always @(posedge clk) begin
        if (!reset) begin
            cpu_cycles <= clocks;
            // Count supported events
            for (integer n = 0; n < EVENT_COUNT/2; n++) begin
              pmcounter[n] <= pmcounter[n] + {60'h0, pmci[n]};
            end
            //NOTE: Hack to support verilator builds -- if EVENT_COUNT is greater than 64, verilator fails to build with Error-BLKLOOPINIT
            //Longer term fix would be adding a higher --unroll-count to verialator's CLI. no time for that on 9/12/2023, though
            for (integer n = EVENT_COUNT/2; n < EVENT_COUNT; n++) begin
              pmcounter[n] <= pmcounter[n] + {60'h0, pmci[n]};
            end

        end
    end

    //AUTOGENERATED -- NO TOUCH
    assign pmcounters_as[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0));
    assign pmcounters_as[0].data.location = location;
    assign pmcounters_as[0].data.cpu_cycles = cpu_cycles;
    assign pmcounters_as[0].data.instructions = pmcounter[INSTRUCTIONS];
    assign pmcounters_as[0].data.cache_references = pmcounter[CACHE_REFERENCES];
    assign pmcounters_as[0].data.cache_misses = pmcounter[CACHE_MISSES];
    assign pmcounters_as[0].data.branch_instructions = pmcounter[BRANCH_INSTRUCTIONS];
    assign pmcounters_as[0].data.branch_misses = pmcounter[BRANCH_MISSES];
    assign pmcounters_as[0].data.bus_cycles = pmcounter[BUS_CYCLES];
    assign pmcounters_as[0].data.stalled_cycles_frontend = pmcounter[STALLED_CYCLES_FRONTEND];
    assign pmcounters_as[0].data.stalled_cycles_backend = pmcounter[STALLED_CYCLES_BACKEND];
    assign pmcounters_as[0].data.ref_cpu_cycles = pmcounter[REF_CPU_CYCLES];
    assign pmcounters_as[0].data.l1d_read_access = pmcounter[L1D_READ_ACCESS];
    assign pmcounters_as[0].data.l1d_read_miss = pmcounter[L1D_READ_MISS];
    assign pmcounters_as[0].data.l1d_write_access = pmcounter[L1D_WRITE_ACCESS];
    assign pmcounters_as[0].data.l1d_write_miss = pmcounter[L1D_WRITE_MISS];
    assign pmcounters_as[0].data.l1d_prefetch_access = pmcounter[L1D_PREFETCH_ACCESS];
    assign pmcounters_as[0].data.l1d_prefetch_miss = pmcounter[L1D_PREFETCH_MISS];
    assign pmcounters_as[0].data.l1i_read_access = pmcounter[L1I_READ_ACCESS];
    assign pmcounters_as[0].data.l1i_read_miss = pmcounter[L1I_READ_MISS];
    assign pmcounters_as[0].data.l1i_write_access = pmcounter[L1I_WRITE_ACCESS];
    assign pmcounters_as[0].data.l1i_write_miss = pmcounter[L1I_WRITE_MISS];
    assign pmcounters_as[0].data.l1i_prefetch_access = pmcounter[L1I_PREFETCH_ACCESS];
    assign pmcounters_as[0].data.l1i_prefetch_miss = pmcounter[L1I_PREFETCH_MISS];
    assign pmcounters_as[0].data.ll_read_access = pmcounter[LL_READ_ACCESS];
    assign pmcounters_as[0].data.ll_read_miss = pmcounter[LL_READ_MISS];
    assign pmcounters_as[0].data.ll_write_access = pmcounter[LL_WRITE_ACCESS];
    assign pmcounters_as[0].data.ll_write_miss = pmcounter[LL_WRITE_MISS];
    assign pmcounters_as[0].data.ll_prefetch_access = pmcounter[LL_PREFETCH_ACCESS];
    assign pmcounters_as[0].data.ll_prefetch_miss = pmcounter[LL_PREFETCH_MISS];

    assign pmcounters_bs[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0));
    assign pmcounters_bs[0].data.location = location;
    assign pmcounters_bs[0].data.dtlb_read_access = pmcounter[DTLB_READ_ACCESS];
    assign pmcounters_bs[0].data.dtlb_read_miss = pmcounter[DTLB_READ_MISS];
    assign pmcounters_bs[0].data.dtlb_write_access = pmcounter[DTLB_WRITE_ACCESS];
    assign pmcounters_bs[0].data.dtlb_write_miss = pmcounter[DTLB_WRITE_MISS];
    assign pmcounters_bs[0].data.dtlb_prefetch_access = pmcounter[DTLB_PREFETCH_ACCESS];
    assign pmcounters_bs[0].data.dtlb_prefetch_miss = pmcounter[DTLB_PREFETCH_MISS];
    assign pmcounters_bs[0].data.itlb_read_access = pmcounter[ITLB_READ_ACCESS];
    assign pmcounters_bs[0].data.itlb_read_miss = pmcounter[ITLB_READ_MISS];
    assign pmcounters_bs[0].data.itlb_write_access = pmcounter[ITLB_WRITE_ACCESS];
    assign pmcounters_bs[0].data.itlb_write_miss = pmcounter[ITLB_WRITE_MISS];
    assign pmcounters_bs[0].data.itlb_prefetch_access = pmcounter[ITLB_PREFETCH_ACCESS];
    assign pmcounters_bs[0].data.itlb_prefetch_miss = pmcounter[ITLB_PREFETCH_MISS];
    assign pmcounters_bs[0].data.bpu_write_access = pmcounter[BPU_WRITE_ACCESS];
    assign pmcounters_bs[0].data.l1d_cache_invalidate = pmcounter[L1D_CACHE_INVALIDATE];
    assign pmcounters_bs[0].data.stalls_mem_l1d_miss = pmcounter[STALLS_MEM_L1D_MISS];
    assign pmcounters_bs[0].data.stalls_mem_stores = pmcounter[STALLS_MEM_STORES];
    assign pmcounters_bs[0].data.stalls_mem_l1dtlb_miss = pmcounter[STALLS_MEM_L1DTLB_MISS];
    assign pmcounters_bs[0].data.stalls_mem_l1d_miss_l2_miss = pmcounter[STALLS_MEM_L1D_MISS_L2_MISS];
    assign pmcounters_bs[0].data.stalls_mem_any = pmcounter[STALLS_MEM_ANY];
    assign pmcounters_bs[0].data.stalls_mem_l1i_miss = pmcounter[STALLS_MEM_L1I_MISS];
    assign pmcounters_bs[0].data.nfp_mispredict = pmcounter[NFP_MISPREDICT];
    assign pmcounters_bs[0].data.br_immed_spec = pmcounter[BR_IMMED_SPEC];
    assign pmcounters_bs[0].data.br_indirect_spec = pmcounter[BR_INDIRECT_SPEC];
    assign pmcounters_bs[0].data.br_ret_spec = pmcounter[BR_RET_SPEC];
    assign pmcounters_bs[0].data.ld_spec = pmcounter[LD_SPEC];
    assign pmcounters_bs[0].data.st_spec = pmcounter[ST_SPEC];
    assign pmcounters_bs[0].data.int_spec = pmcounter[INT_SPEC];
    assign pmcounters_bs[0].data.fp_spec = pmcounter[FP_SPEC];

    assign pmcounters_cs[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0));
    assign pmcounters_cs[0].data.location = location;
    assign pmcounters_cs[0].data.uop_issued = pmcounter[UOP_ISSUED];
    assign pmcounters_cs[0].data.uop_retired = pmcounter[UOP_RETIRED];
    assign pmcounters_cs[0].data.total_uops_flushed = pmcounter[TOTAL_UOPS_FLUSHED];
    assign pmcounters_cs[0].data.total_ind_br_retired = pmcounter[TOTAL_IND_BR_RETIRED];
    assign pmcounters_cs[0].data.total_ind_br_retired_mispred = pmcounter[TOTAL_IND_BR_RETIRED_MISPRED];
    assign pmcounters_cs[0].data.lsu_resyncs = pmcounter[LSU_RESYNCS];
    assign pmcounters_cs[0].data.total_flushes = pmcounter[TOTAL_FLUSHES];
    assign pmcounters_cs[0].data.load_misal_accesses = pmcounter[LOAD_MISAL_ACCESSES];
    assign pmcounters_cs[0].data.store_misal_accesses = pmcounter[STORE_MISAL_ACCESSES];
    assign pmcounters_cs[0].data.stlf_hits = pmcounter[STLF_HITS];
    assign pmcounters_cs[0].data.vector_busy_cycles = pmcounter[VECTOR_BUSY_CYCLES];
    assign pmcounters_cs[0].data.m_mode_cycles = pmcounter[M_MODE_CYCLES];
    assign pmcounters_cs[0].data.m_mode_instret = pmcounter[M_MODE_INSTRET];
    assign pmcounters_cs[0].data.s_mode_cycles = pmcounter[S_MODE_CYCLES];
    assign pmcounters_cs[0].data.s_mode_instret = pmcounter[S_MODE_INSTRET];
    assign pmcounters_cs[0].data.u_mode_cycles = pmcounter[U_MODE_CYCLES];
    assign pmcounters_cs[0].data.u_mode_instret = pmcounter[U_MODE_INSTRET];

    assign pmcounters_ds[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0));
    assign pmcounters_ds[0].data.location = location;
    assign pmcounters_ds[0].data.compressed_instret = pmcounter[COMPRESSED_INSTRET];
    assign pmcounters_ds[0].data.tlb_invalidates = pmcounter[TLB_INVALIDATES];
    assign pmcounters_ds[0].data.br_ret_retired = pmcounter[BR_RET_RETIRED];
    assign pmcounters_ds[0].data.br_ret_misses = pmcounter[BR_RET_MISSES];
    assign pmcounters_ds[0].data.ind_br_retired = pmcounter[IND_BR_RETIRED];
    assign pmcounters_ds[0].data.ind_br_misses = pmcounter[IND_BR_MISSES];
    assign pmcounters_ds[0].data.rel_br_retired = pmcounter[REL_BR_RETIRED];
    assign pmcounters_ds[0].data.rel_br_misses = pmcounter[REL_BR_MISSES];
    assign pmcounters_ds[0].data.cycles_no_int_prn = pmcounter[CYCLES_NO_INT_PRN];
    assign pmcounters_ds[0].data.cycles_no_fp_prn = pmcounter[CYCLES_NO_FP_PRN];
    assign pmcounters_ds[0].data.cycles_no_vec_prn = pmcounter[CYCLES_NO_VEC_PRN];
    assign pmcounters_ds[0].data.ic_way_mispred = pmcounter[IC_WAY_MISPRED];
    assign pmcounters_ds[0].data.ls_replay = pmcounter[LS_REPLAY];
    assign pmcounters_ds[0].data.ls_replay_way_predictor = pmcounter[LS_REPLAY_WAY_PREDICTOR];
    assign pmcounters_ds[0].data.cycles_ldq_full = pmcounter[CYCLES_LDQ_FULL];
    assign pmcounters_ds[0].data.cycles_stq_full = pmcounter[CYCLES_STQ_FULL];
    assign pmcounters_ds[0].data.cycles_rar_full = pmcounter[CYCLES_RAR_FULL];
    assign pmcounters_ds[0].data.cycles_raw_full = pmcounter[CYCLES_RAW_FULL];

endmodule
