#include "cvm/logger.hpp"
#include "cvm/topology.hpp"
#include "rv_tester_transactions.hpp"
#include "rv_tester/rv_tester_structs.h"
#include <cassert>
#include <vector>

class pmu {

public:
    //AUTOGENERATED -- NO TOUCH

    typedef enum : size_t {
      //Event for each CPU cycle; implemented via the mcycle CSR
      CPU_CYCLES,
      //Event for each retired instruction; implemented via the minstret CSR
      INSTRUCTIONS,
      //Sum of retired branches
      BRANCH_INSTRUCTION,
      //Event for each CPU cycle that happens while in m mode
      M_MODE_CYCLES,
      //Event for each retired instruction that happens while in m mode
      M_MODE_INSTRET,
      //Event for each CPU cycle that happens while in s mode
      S_MODE_CYCLES,
      //Event for each retired instruction that happens while in s mode
      S_MODE_INSTRET,
      //Event for each CPU cycle that happens while in u mode
      U_MODE_CYCLES,
      //Event for each retired instruction that happens while in u mode
      U_MODE_INSTRET,
      //Event for each reference CPU cycle; wall clock
      REF_CPU_CYCLES,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full Branch Status Table
      STALLS_BST_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full Prefix table
      STALLS_PFX_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in indirect prediction via Branch Target Predictor or Return Address Stack
      STALLS_INDIRECT_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in instruction cache
      STALLS_ICACHE_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to a miss in the IC
      STALLS_ITLB_MISS,
      //Event (speculative) for each cycle BPM1 mux is stalled due to i-side request buffers full IC/I$
      STALLS_IRB_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to full IFBUF
      STALLS_IFBUF_FULL,
      //Event (speculative) for each cycle BPM1 mux is stalled due to stalls_exception
      STALLS_EXCEPTION,
      //Event (speculative) for every fetch block crossing a page boundary and forced to split
      PAGE_CROSSING_FETCHBLOCKS,
      //Event (speculative) for every instance of disagreement between next-fetch predictor and Branch Direction Predictor
      NFP_EARLY_REDIRECT,
      //Event (speculative) for every instance of disagreement between next-fetch predictor and Branch Target Predictor
      NFP_LATE_REDIRECT,
      //Event (speculative) for every instance of redirect caused by IFBUF full
      IFBUF_FULL_REDIRECT,
      //Event for every instance of resync due to CSR access
      NONSPEC_RESYNC,
      //Event (speculative) for every instance of resync due to detectable soft-errors from L2 or LS unit
      FAULT_RESYNC,
      // Event (speculative) for every instance of fetch redirect due to soft-errors in frontend structures
      FAULT_REFETCH,
      //Event (non-speculative) for every instance of entering conservative mode
      CMODE_ENTRY,
      //Event for retiring a branch instruction that mispredicted during its execution. The misprediction could be due to direction predictor or target predictor. This will not include mispredictions due to next-fetch predictor.
      BRANCH_MISSES,
      //Event for each retired and mispredicted control flow instruction that uses the return address stack for prediction
      BR_RET_MISSES,
      //Event for each retired and mispredicted indirect control flow instruction that uses the Branch Target Predictor. Return instructions are not included
      IND_BR_MISSES,
      //Event for each retired and mispredicted conditional control flow instruction that uses the Branch Direction Predictor
      REL_BR_MISSES,
      //Event (speculative) for every instance of branch misprediction flush
      SPEC_BRANCH_REDIRECT,
      //Event (speculative) for every instance of load misprediction flush
      SPEC_LSU_RESYNCS,
      //Event (speculative) for every flush is emitted from midcore regardless of origin
      TOTAL_FLUSHES,
      //Event (speculative) for every instruction provided from decode to Mapper
      UOPS_DECODED,
      //Event (speculative) for an L1I cache access. Only demand accesses are counted. Accesses in the shadow of a demand miss are not counted. Count once for every fetchgroup access
      L1I_READ_ACCESS,
      //Event (speculative) for an L1I cache miss.Misses in the shadow of a demand miss are not counted
      L1I_READ_MISS,
      //Event (speculative) for every L1I cache access for instruction prefetch
      L1I_PREFETCH_ACCESS,
      //Event (speculative) for every L1I cache miss for an instruction prefetch
      L1I_PREFETCH_MISS,
      //Event (speculative) for an L1I TLB demand access. Accesses in the shadow of a demand miss are not counted
      ITLB_READ_ACCESS,
      //Event (speculative) for an L1I TLB demand miss. Misses in the shadow of a demand miss are not counted
      ITLB_READ_MISS,
      //Event (speculative) for an L1I TLB access for an instruction prefetch
      ITLB_PREFETCH_ACCESS,
      //Event (speculative) for an L1I TLB miss for an instruction prefetch
      ITLB_PREFETCH_MISS,
      //Event(speculative) for each instruction cache way misprediction
      IC_WAY_MISPRED,
      //Event (speculative) for every underflow event of return address stack
      RAS_UNDERFLOW,
      //Event (speculative) for every overflow event of return address stack
      RAS_OVERFLOW,
      //Event(speculative) for every fetchgroup written into the IFBUF. If fetchgroup has 2 writes in the same cycle into the IFBUF it is still counted as 1 fetchgroup
      NUM_FETCHGROUPS,
      //Event for every cycle an update to Branch Direction Predictor is delayed due to a bank conflict
      BDP_BANK_CONFLICTS,
      //Event for every cycle an update to Branch Target Predictor is delayed due to bank conflict
      BTP_BANK_CONFLICTS,
      //Event for every write into either Branch Direction Predictor or Branch Target Predictor. Count twice if both are written in the same cycle
      BPU_WRITES,
      //Event fired on each cycle when backend is ready to accept a fetch bundle  but frontend is not able to supply any instructions.
      STALLED_CYCLES_FRONTEND,
      //Event fired on each where frontend is ready to supply at least one instruction but backend is not able to accept. This should be measured at stage MC0
      STALLED_CYCLES_BACKEND,
      //Event (speculative) for each cycle Mapper is stalled due to no integer physical registers
      CYCLES_NO_INT_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to  no floating point physical registers
      CYCLES_NO_FP_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector physical registers
      CYCLES_NO_VEC_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector length physical registers
      CYCLES_NO_VL_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no Vector mask physical registers
      CYCLES_NO_VM_PRN,
      //Event (speculative) for each cycle Mapper is stalled due to no reorder buffer entries
      CYCLES_NO_ROB,
      //Event for each retired direct control flow instruction
      OP_RETIRED_DIRECT_BRANCH,
      //Event for each retired control flow instruction that uses the return address stack for prediction
      OP_RETIRED_RET_BRANCH,
      //Event for each retired indirect control flow instruction that uses the Branch Target Predictor for prediction. Return instructions are not included
      OP_RETIRED_INDIRECT_BRANCH,
      //Event for each retired conditional control flow instruction that uses the Branch Direction Predictor
      OP_RETIRED_COND_BRANCH,
      //Event for every retired Load operation
      OP_RETIRED_LD,
      //Event for every retired Store operation
      OP_RETIRED_ST,
      //Event for every retired integer operation. This does not include Load or Store operations
      OP_RETIRED_INT,
      //Event for every retired CSR operation
      OP_RETIRED_CSR,
      //Event for every retired floating point operation. This does not include Load or Store operations
      OP_RETIRED_FP,
      //Event for every retired vector operation. This does not include Load or Store operations
      OP_RETIRED_VEC,
      //Event (speculative) for every confirmed load operation. This does not include Load or Store operations
      OP_COMPLETE_LD,
      //Event (speculative) for every confirmed store operation. This does not include Load or Store operations
      OP_COMPLETE_ST,
      //Event (speculative) for every confirmed integer operation. This does not include Load or Store operations
      OP_COMPLETE_INT,
      //Event (speculative) for every confirmed floating point operation. This does not include Load or Store operations.
      OP_COMPLETE_FP,
      //Event (speculative) for every confirmed vector point operation. This does not include Load or Store operations.
      OP_COMPLETE_VEC,
      //Event (speculative) for pipe 0 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE0,
      //Event (speculative) for pipe 1 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE1,
      //Event (speculative) for pipe 2 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE2,
      //Event (speculative) for pipe 3 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE3,
      //Event (speculative) for pipe 4 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE4,
      //Event (speculative) for pipe 5 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE5,
      //Event (speculative) for pipe 6 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE6,
      //Event (speculative) for pipe 7 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE7,
      //Event (speculative) for pipe 8 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE8,
      //Event (speculative) for pipe 9 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE9,
      //Event (speculative) for pipe 10 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE10,
      //Event (speculative) for pipe 11 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE11,
      //Event (speculative) for pipe 12 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE12,
      //Event (speculative) for pipe 13 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE13,
      //Event (speculative) for pipe 14 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE14,
      //Event (speculative) for pipe 15 issuing. Multiple issues per cycle should be precisely counted
      OP_ISSUED_PIPE15,
      //The count will represent all the requests made to L1 I and D caches. Includes accesses made by Speculatively executed instructions and hardware prefetchers but does not include non-cacheable requests
      CACHE_REFERENCES,
      //Event for a request made to cache subsystem that misses in L1 I and D caches. Includes accesses made by Speculatively executed instructions and hardware prefetchers.  but does not include non-cacheable requests
      CACHE_MISSES,
      //Event for each tlb invalidation -- this will track retired instructions that invalidate the TLB
      TLB_INVALIDATES,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_ALIGNED,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_CLC,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_4KX,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_ACCESS_ALL,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MMU_ACCESS,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_SNOOP_ACCESS,
      //Event for a l1d_cache access caused by a demand Memory-read operation (filtered by load/store/prefetch/MMU/Snoop/All and by Aligned/CLC/4kX/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_ACCESS_ALL,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_READ_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_WRITE_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_PREFETCH_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MMU_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_SNOOP_MISS,
      //Event for a l1d_cache refill that is due to a demand Memory-read operation (filtered by load/store/prefetch/MMU/snoop/All). Includes accesses made by Speculatively executed instructions but does not include accesses to IO or noncacheable regions
      L1D_MISS_ALL,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_SNOOP,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_CMO,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_LOAD_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_STORE_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_PREFETCH_EVICTION,
      //all l1 data cache invalidates (filtered by snoops/CMOs/load-evictions/store-evictions/prefetch-evictions)
      L1D_CACHE_INVALIDATE_ALL,
      //Event (speculative) for micro-TLB miss caused by a demand memory operation
      UTLB_MISS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_READ_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_WRITE_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_PREFETCH_ACCESS,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_4K,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_HUGEPAGE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_CACHEABLE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_NONCACHEABLE,
      //Event for an l1 dTLB access caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/all and by Cacheable/Non-cacheable. Includes accesses made by Speculatively executed instructions.
      DTLB_ACCESS_ALL,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_READ_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_WRITE_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_PREFETCH_MISS,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_4K,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_HUGEPAGE,
      //Event for an l1 dTLB miss caused by a demand Memory-read operation (filtered by load/store/prefetch/All and by 4k/huge-page/All. Includes accesses made by Speculatively executed instructions.
      DTLB_MISS_ALL,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_LS,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_FE,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_PREFETCH,
      //Event for leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_ACCESS_ALL,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_LS,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_FE,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_PREFETCH,
      //Event for leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      LEAF_TLB_MISS_ALL,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_LS,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_FE,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_PREFETCH,
      //Event for non-leaf TLB access (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_ACCESS_ALL,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_LS,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_FE,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_PREFETCH,
      //Event for non-leaf TLB miss (filtered by LS/FE/Prefetch). Includes accesses made by Speculatively executed instructions.
      NONLEAF_TLB_MISS_ALL,
      //Number of page walks initiated
      PAGE_WALKS,
      //Event (speculative) for every cycle the instruction picker has ops -- but does not pick -- and there is a pending L1D demand miss
      STALLS_MEM_L1D_MISS,
      //Event (speculative) for every cycle the instruction picker has ops -- but does not pick -- and the STQ can not drain to SMB.
      STALLS_MEM_STORES,
      //Event (speculative) for every cycle the instruction picker has ops --  but does not pick -- and there is a pending L1 DTLB demand miss
      STALLS_MEM_L1DTLB_MISS,
      //Number of resyncs raised by LSU filtered by (RAW/RAR/All)
      LSU_RESYNCS_RAW,
      //Number of resyncs raised by LSU filtered by (RAW/RAR/All)
      LSU_RESYNCS_RAR,
      //Event (speculative) for every instance of a Store instruction forwarding data to a Load instruction
      STLF_HITS,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_LOAD,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_STORE,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_PREFETCH,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_MMU,
      //Event (speculative) for any condition triggering replay from LS (Filtered by Load/Store/Prefetch/MMU/All)
      LS_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by the DC way predictor (Filtered by Load/Store/Prefetch/MMU/All)
      LS_WAY_PREDICTOR_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by incorrect PA prediction (Filtered by Load/Store/Prefetch/MMU/All)
      SIPT_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by STLF (Filtered by Load/Store/Prefetch/MMU/All)
      STLF_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by tag bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      TAG_BANK_CONFLICT_REPLAY_ALL,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_LOAD,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_STORE,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_PREFETCH,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_MMU,
      //Event (speculative) for any LS replay caused by data bank conflict (Filtered by Load/Store/Prefetch/MMU/All)
      DATA_BANK_CONFLICT_REPLAY_ALL,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a fillbuffer entry (Filtered by Load/Store/Prefetch/MMU/All)
      FILLBUF_HIT_REPLAY_ALL,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_PREFETCH,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a transbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      TRANSBUF_HIT_REPLAY_ALL,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_LOAD,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_STORE,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_MMU,
      //Event for any replay caused by hitting on a reqbuf entry (Filtered by Load/Store/Prefetch/MMU/All)
      REQBUF_HIT_REPLAY_ALL,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_LOAD,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_STORE,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_PREFETCH,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_MMU,
      //Event for any LS replay caused by DTLB miss (Filtered by Load/Store/Prefetch/MMU/All)
      DTLB_REPLAY_ALL,
      //Event (speculative) for every instance of failed Read-After-Read queue allocation to a demand memory-read operation
      RAR_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Read-After-Write queue allocation to a demand memory-read operation
      RAW_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Load Queue allocation to a demand memory-read operation
      LDQ_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Store-Merge-Buffer allocation to a demand memory-write operation
      SMB_CANNOT_ALLOC,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_LOAD,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_STORE,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_PREFETCH,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_MMU,
      //Event (speculative) for every instance of a failed Memory-Request-Buffer allocation to a demand memory operation (filtered by load/store/prefetch/MMU/All)
      REQBUF_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed FillBuffer allocation
      FILLBUF_CANNOT_ALLOC,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_LOAD,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_STORE,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_PREFETCH,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_MMU,
      //Event for every instance of a failed TransBuffer allocation (filtered by load/store/prefetch/MMU/All)
      TRANSBUF_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_LOAD,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_STORE,
      //Event for every instance of a failed Page Cross Buffer allocation (filtered by load/store/All)
      PCB_CANNOT_ALLOC_ALL,
      //Event for every instance of a failed Unaligned Data Buffer allocation
      UDB_CANNOT_ALLOC,
      //Event for every instance a memory operation used the Unaligned Data Buffer for data return
      UDB_DATA_RETURN,
      //Event for every instance an allocated Unaligned Data Buffer entry was lost to another cacheline crossing request
      UDB_LOST,
      //Event for micro way predictor access
      UWP_ACCESS,
      //Event for micro-way-predictor refill caused by a demand memory operation
      UWP_MISS,
      //Event for every instance of a uWP hit matching the L1D hit way
      UWP_TRUE_HIT,
      //Event for way predictor access
      WP_ACCESS,
      //Event for a WP refill caused by a demand memory operation
      WP_MISS,
      //Event for every instance of a WP hit matching the L1D hit way
      WP_TRUE_HIT,
      //Event for a correct prediction by MDP
      MDP_CORRECT_PREDICTION,
      //Event for every instance of prediction by MDP where the load does not get its data from STLF
      MDP_FALSE_HIT,
      //Event for every instance of MDP miss causing a RAW resync
      MDP_FALSE_MISS,
      //Event for every instance of a load predicted by MDP
      MDP_TOTAL_PREDICTION,
      //Event for every retired atomic operation
      ATOMICS_RETIRED,
      //"Event (speculative) for every fully masked
      LDST_MASKED_NANO,
      //Event (speculative) for every confirmed Load nano-operation
      LD_EXECUTED_NANO,
      //Event (speculative) for every confirmed Store nano-operation
      ST_EXECUTED_NANO,
      //Event (speculative) for every failed instance a new Active Generation Table allocation
      PFC_AGT_CANNOT_ALLOC,
      //Event (speculative) for every successful instance of Active Generation Table entry evicted to Pattern History Table
      PFC_AGT_EVICT,
      //Event (speculative) for every failed instance a new entry in Pattern History Table allocation
      PFC_PHT_CANNOT_ALLOC,
      //Event (speculative) for every instance of read-access (lookup) to Pattern History Table
      PFC_PHT_LOOKUP,
      //Event (speculative) for every instance of a hit in the Pattern History Table
      PFC_PHT_HIT,
      //Event (speculative) for every failed instance Prefetch Request Table allocation
      PFC_PRT_CANNOT_ALLOC,
      //Event (speculative) for every failed instance a Prefetch TLB request due to no credits
      PFC_NO_TLB_CREDIT_STALLS,
      //Event (speculative) for every failed instance a Prefetch Tag request due to no credit
      PFC_NO_TAG_CREDIT_STALLS,
      //Event (speculative) for every instance of a Prefetch Tag requests sent to LS
      PFC_PREFETCHES_SENT,
      //Event (speculative) for every instance a demand memory operation hits on prefetch-data. Only count the first hit is counted
      PFC_PREFETCHES_HIT,
      //Event (speculative) for every instance a demand memory operation misses in the L1D cache but but hits on a prefetch request in TxnBuf
      PFC_PREFETCHES_LATE,
      //Event (speculative) for every L1D eviction which is an unused prefetch
      PFC_USELESS_PREFETCHES,
      //"Count each Memory-read operation or Memory-write operation that causes a cache access to SC. Each access to a cache line is counted
      SC_CACHE_ACCESS,
      //Count Memory-read operation that causes a cache access to SC.
      SC_CACHE_RD,
      //Count each Memory-read operation or Memory-write operation that causes a cache access to SC but is not completed by SC.
      SC_CACHE_MISS,
      //Count Memory-read operation that causes a cache access to SC but is not completed by SC.
      SC_CACHE_MISS_RD,
      //Counts each access counted by SC_CACHE_ACCESS that causes a refill of the SC from outside of SC.
      SC_CACHE_REFILL,
      //Counts each Memory-write operation that writes an entire line into SC without fetching data from outside SC.
      SC_CACHE_ALLOCATE,
      //Counts each write-back of dirty cache lines from SC to outside of SC.
      SC_CACHE_WB_DIRTY,
      //Counts each write-back of clean cache lines from SC to outside of SC.
      SC_CACHE_WB_CLEAN,
      //"Counts each invalidation of a cache line in SC
      SC_CACHE_INVAL,
      //Count external snoops received by SC.
      SC_SNOOP,
      //Count Memory-read operation to ScratchPad Memory.
      SC_SCRATCHPAD_RD,
      //Count Memory-write operation to ScratchPad Memory.
      SC_SCRATCHPAD_WR,
      //Read requests from fabric
      F2SC_RD,
      //Write requests from fabric
      F2SC_WR,
      //Cummulative cycles between MSHR allocation and release
      MSHR_LIFETIME,
      //Number of MSHR allocations
      MSHR_ALLOCATIONS,
      //ReadUnique requests to fabric
      SC2F_RD_U,
      //ReadClean requests to fabric
      SC2F_RD_C,
      //ReadOnce requests to fabric
      SC2F_RD_O,
      //Write requests to fabric
      SC2F_WR,
      //Read requests from instruction fetch
      C2SC_RD_I,
      //Read requests from data cache
      C2SC_RD_D,
      //Write requests from cores
      C2SC_WB_FULL,
      //Clean evictions from cores
      C2SC_EVICT,
      //Snoop writeback full from cores
      C2SC_SNP_WB_FULL,
      //
      C2SC_WRNOSNPPTL,
      //Snoop to cores
      C2SC_SNP,
      //Number of cycles that REQ channel is stalled
      C2SC_REQ_STALL,
      //Number of cycles that WDAT channel is stalled
      C2SC_WDAT_STALL,
      //Number of cycles that SRSP channel is stalled
      C2SC_SRSP_STALL,
      //Number of cycles that RDAT channel is stalled
      C2SC_RDAT_STALL,
      //Number of cycles that SNP channel is stalled
      C2SC_SNP_STALL,
      //Number of cycles that CRSP channel is stalled
      C2SC_CRSP_STALL,
      //Clean evictions to fabric
      SC2F_EVICT,
      //Dirty evictions to fabric
      SC2F_WRBACKFULL,
      //WDAT 32B beats to fabric
      SC2F_WDAT,
      //Snoop from fabric
      SC2F_SNOOP,
      //RDAT 32B beats from fabric
      SC2F_RDAT,
      //Number of cycles that REQ channel is stalled
      SC2F_REQ_STALL,
      //Number of cycles that WDAT channel is stalled
      SC2F_WDAT_STALL,
      //Number of cycles that SRSP channel is stalled
      SC2F_SRSP_STALL,
      //Number of cycles that RDAT channel is stalled
      SC2F_RDAT_STALL,
      //Number of cycles that SNP channel is stalled
      SC2F_SNOOP_STALL,
      //Number of cycles that CRSP channel is stalled
      SC2F_CRSP_STALL,
      //WDAT 32B beats to fabric
      F2SC_WDAT,
      //RDAT 32B beats from fabric
      F2SC_RDAT,
      //
      F2SC_WRNOSNPPTL,
      //Number of cycles that REQ channel is stalled
      F2SC_REQ_STALL,
      //Number of cycles that WDAT channel is stalled
      F2SC_WDAT_STALL,
      //Number of cycles that RDAT channel is stalled
      F2SC_RDAT_STALL,
      //Number of cycles that CRSP channel is stalled
      F2SC_CRSP_STALL,
      //SC tag array lookup
      SC_TAG_LOOKUP,
      //SC tag array write
      SC_TAG_WRITE,
      //SC state array write
      SC_STATE_WRITE,
      //SC repl array write
      SC_REPL_WRITE,
      //SC tag hit
      SC_TAG_HIT,
      //SC data array read
      SC_DATA_READ,
      //SC data array write
      SC_DATA_WRITE,
      //Cache line state from Invalid to Exclusive
      SC_STATE_I2E,
      //Cache line state from Invalid to Modified
      SC_STATE_I2M,
      //Cache line state from Invalid to Shared
      SC_STATE_I2S,
      //Cache line state from Shared to Invalid
      SC_STATE_S2I,
      //Cache line state from Shared to Modified
      SC_STATE_S2M,
      //Cache line state from Shared to Exclusive
      SC_STATE_S2E,
      //Cache line state from Modified to Invalid
      SC_STATE_M2I,
      //Cache line state from Modified to Shared
      SC_STATE_M2S,
      //Cache line state from Modified to Exclusive
      SC_STATE_M2E,
      //Cache line state from Exclusive to Invalid
      SC_STATE_E2I,
      //Cache line state from Exclusive to Shared
      SC_STATE_E2S,
      //Cache line state from Exclusive to Modified
      SC_STATE_E2M,
      //Snoop filter lookup
      SFT_LOOKUP,
      //Snoop filter hit
      SFT_HIT,
      //Snoop filter write
      SFT_WRITE,
      //Snoop filter eviciton
      SFT_EVICTION,
      //Snoop filter sends snoop to single I-cache
      SFT_SNP_SINGLE_ICACHE,
      //Snoop filter sends snoop to single D-cache
      SFT_SNP_SINGLE_DCACHE,
      //Snoop filter sends snoop to multiple cores
      SFT_SNP_MULTI_CORES,
      //Snoop filter replay due to no MSHR for evictions
      SFT_EVICTION_REPLAY,
      //Cummulative number of MSHRs used
      MSHR_OCCUPANCY,
      //SC not accept new requests due to no MSHR available
      MSHR_FULL,
      //MSHR same address queue entry allocated
      MSHR_SAQ_ALLOC,
      //MSHR same address queue is full
      MSHR_SAQ_FULL,
      //Cache line not allocated into SC due to no MSHR avaiable
      NO_ALLOC_NO_MSHR,
      //Cache line not allocated into SC due to allocation hint is not set
      NO_ALLOC_HINT_NOT_SET,
      //SC replay due to ECC errors
      SC_REPLAY_ECC,
      COUNT
    } counter;


    //AUTOGENERATED -- NO TOUCH

std::vector<uint64_t> to_vector(const rv_tester_transactions::pmu::pmcounters<>& pmcounters)
    {
      std::vector<uint64_t> tmp(counter::COUNT);

      tmp[counter::CPU_CYCLES] = pmcounters.cpu_cycles;
      tmp[counter::INSTRUCTIONS] = pmcounters.instructions;
      tmp[counter::BRANCH_INSTRUCTION] = pmcounters.branch_instruction;
      tmp[counter::M_MODE_CYCLES] = pmcounters.m_mode_cycles;
      tmp[counter::M_MODE_INSTRET] = pmcounters.m_mode_instret;
      tmp[counter::S_MODE_CYCLES] = pmcounters.s_mode_cycles;
      tmp[counter::S_MODE_INSTRET] = pmcounters.s_mode_instret;
      tmp[counter::U_MODE_CYCLES] = pmcounters.u_mode_cycles;
      tmp[counter::U_MODE_INSTRET] = pmcounters.u_mode_instret;
      tmp[counter::REF_CPU_CYCLES] = pmcounters.ref_cpu_cycles;
      tmp[counter::STALLS_BST_FULL] = pmcounters.stalls_bst_full;
      tmp[counter::STALLS_PFX_FULL] = pmcounters.stalls_pfx_full;
      tmp[counter::STALLS_INDIRECT_MISS] = pmcounters.stalls_indirect_miss;
      tmp[counter::STALLS_ICACHE_MISS] = pmcounters.stalls_icache_miss;
      tmp[counter::STALLS_ITLB_MISS] = pmcounters.stalls_itlb_miss;
      tmp[counter::STALLS_IRB_FULL] = pmcounters.stalls_irb_full;
      tmp[counter::STALLS_IFBUF_FULL] = pmcounters.stalls_ifbuf_full;
      tmp[counter::STALLS_EXCEPTION] = pmcounters.stalls_exception;
      tmp[counter::PAGE_CROSSING_FETCHBLOCKS] = pmcounters.page_crossing_fetchblocks;
      tmp[counter::NFP_EARLY_REDIRECT] = pmcounters.nfp_early_redirect;
      tmp[counter::NFP_LATE_REDIRECT] = pmcounters.nfp_late_redirect;
      tmp[counter::IFBUF_FULL_REDIRECT] = pmcounters.ifbuf_full_redirect;
      tmp[counter::NONSPEC_RESYNC] = pmcounters.nonspec_resync;
      tmp[counter::FAULT_RESYNC] = pmcounters.fault_resync;
      tmp[counter::FAULT_REFETCH] = pmcounters.fault_refetch;
      tmp[counter::CMODE_ENTRY] = pmcounters.cmode_entry;
      tmp[counter::BRANCH_MISSES] = pmcounters.branch_misses;
      tmp[counter::BR_RET_MISSES] = pmcounters.br_ret_misses;
      tmp[counter::IND_BR_MISSES] = pmcounters.ind_br_misses;
      tmp[counter::REL_BR_MISSES] = pmcounters.rel_br_misses;
      tmp[counter::SPEC_BRANCH_REDIRECT] = pmcounters.spec_branch_redirect;
      tmp[counter::SPEC_LSU_RESYNCS] = pmcounters.spec_lsu_resyncs;
      tmp[counter::TOTAL_FLUSHES] = pmcounters.total_flushes;
      tmp[counter::UOPS_DECODED] = pmcounters.uops_decoded;
      tmp[counter::L1I_READ_ACCESS] = pmcounters.l1i_read_access;
      tmp[counter::L1I_READ_MISS] = pmcounters.l1i_read_miss;
      tmp[counter::L1I_PREFETCH_ACCESS] = pmcounters.l1i_prefetch_access;
      tmp[counter::L1I_PREFETCH_MISS] = pmcounters.l1i_prefetch_miss;
      tmp[counter::ITLB_READ_ACCESS] = pmcounters.itlb_read_access;
      tmp[counter::ITLB_READ_MISS] = pmcounters.itlb_read_miss;
      tmp[counter::ITLB_PREFETCH_ACCESS] = pmcounters.itlb_prefetch_access;
      tmp[counter::ITLB_PREFETCH_MISS] = pmcounters.itlb_prefetch_miss;
      tmp[counter::IC_WAY_MISPRED] = pmcounters.ic_way_mispred;
      tmp[counter::RAS_UNDERFLOW] = pmcounters.ras_underflow;
      tmp[counter::RAS_OVERFLOW] = pmcounters.ras_overflow;
      tmp[counter::NUM_FETCHGROUPS] = pmcounters.num_fetchgroups;
      tmp[counter::BDP_BANK_CONFLICTS] = pmcounters.bdp_bank_conflicts;
      tmp[counter::BTP_BANK_CONFLICTS] = pmcounters.btp_bank_conflicts;
      tmp[counter::BPU_WRITES] = pmcounters.bpu_writes;
      tmp[counter::STALLED_CYCLES_FRONTEND] = pmcounters.stalled_cycles_frontend;
      tmp[counter::STALLED_CYCLES_BACKEND] = pmcounters.stalled_cycles_backend;
      tmp[counter::CYCLES_NO_INT_PRN] = pmcounters.cycles_no_int_prn;
      tmp[counter::CYCLES_NO_FP_PRN] = pmcounters.cycles_no_fp_prn;
      tmp[counter::CYCLES_NO_VEC_PRN] = pmcounters.cycles_no_vec_prn;
      tmp[counter::CYCLES_NO_VL_PRN] = pmcounters.cycles_no_vl_prn;
      tmp[counter::CYCLES_NO_VM_PRN] = pmcounters.cycles_no_vm_prn;
      tmp[counter::CYCLES_NO_ROB] = pmcounters.cycles_no_rob;
      tmp[counter::OP_RETIRED_DIRECT_BRANCH] = pmcounters.op_retired_direct_branch;
      tmp[counter::OP_RETIRED_RET_BRANCH] = pmcounters.op_retired_ret_branch;
      tmp[counter::OP_RETIRED_INDIRECT_BRANCH] = pmcounters.op_retired_indirect_branch;
      tmp[counter::OP_RETIRED_COND_BRANCH] = pmcounters.op_retired_cond_branch;
      tmp[counter::OP_RETIRED_LD] = pmcounters.op_retired_ld;
      tmp[counter::OP_RETIRED_ST] = pmcounters.op_retired_st;
      tmp[counter::OP_RETIRED_INT] = pmcounters.op_retired_int;
      tmp[counter::OP_RETIRED_CSR] = pmcounters.op_retired_csr;
      tmp[counter::OP_RETIRED_FP] = pmcounters.op_retired_fp;
      tmp[counter::OP_RETIRED_VEC] = pmcounters.op_retired_vec;
      tmp[counter::OP_COMPLETE_LD] = pmcounters.op_complete_ld;
      tmp[counter::OP_COMPLETE_ST] = pmcounters.op_complete_st;
      tmp[counter::OP_COMPLETE_INT] = pmcounters.op_complete_int;
      tmp[counter::OP_COMPLETE_FP] = pmcounters.op_complete_fp;
      tmp[counter::OP_COMPLETE_VEC] = pmcounters.op_complete_vec;
      tmp[counter::OP_ISSUED_PIPE0] = pmcounters.op_issued_pipe0;
      tmp[counter::OP_ISSUED_PIPE1] = pmcounters.op_issued_pipe1;
      tmp[counter::OP_ISSUED_PIPE2] = pmcounters.op_issued_pipe2;
      tmp[counter::OP_ISSUED_PIPE3] = pmcounters.op_issued_pipe3;
      tmp[counter::OP_ISSUED_PIPE4] = pmcounters.op_issued_pipe4;
      tmp[counter::OP_ISSUED_PIPE5] = pmcounters.op_issued_pipe5;
      tmp[counter::OP_ISSUED_PIPE6] = pmcounters.op_issued_pipe6;
      tmp[counter::OP_ISSUED_PIPE7] = pmcounters.op_issued_pipe7;
      tmp[counter::OP_ISSUED_PIPE8] = pmcounters.op_issued_pipe8;
      tmp[counter::OP_ISSUED_PIPE9] = pmcounters.op_issued_pipe9;
      tmp[counter::OP_ISSUED_PIPE10] = pmcounters.op_issued_pipe10;
      tmp[counter::OP_ISSUED_PIPE11] = pmcounters.op_issued_pipe11;
      tmp[counter::OP_ISSUED_PIPE12] = pmcounters.op_issued_pipe12;
      tmp[counter::OP_ISSUED_PIPE13] = pmcounters.op_issued_pipe13;
      tmp[counter::OP_ISSUED_PIPE14] = pmcounters.op_issued_pipe14;
      tmp[counter::OP_ISSUED_PIPE15] = pmcounters.op_issued_pipe15;
      tmp[counter::CACHE_REFERENCES] = pmcounters.cache_references;
      tmp[counter::CACHE_MISSES] = pmcounters.cache_misses;
      tmp[counter::TLB_INVALIDATES] = pmcounters.tlb_invalidates;
      tmp[counter::L1D_READ_ACCESS_ALIGNED] = pmcounters.l1d_read_access_aligned;
      tmp[counter::L1D_READ_ACCESS_CLC] = pmcounters.l1d_read_access_clc;
      tmp[counter::L1D_READ_ACCESS_4KX] = pmcounters.l1d_read_access_4kx;
      tmp[counter::L1D_READ_ACCESS_ALL] = pmcounters.l1d_read_access_all;
      tmp[counter::L1D_WRITE_ACCESS_ALIGNED] = pmcounters.l1d_write_access_aligned;
      tmp[counter::L1D_WRITE_ACCESS_CLC] = pmcounters.l1d_write_access_clc;
      tmp[counter::L1D_WRITE_ACCESS_4KX] = pmcounters.l1d_write_access_4kx;
      tmp[counter::L1D_WRITE_ACCESS_ALL] = pmcounters.l1d_write_access_all;
      tmp[counter::L1D_PREFETCH_ACCESS_ALIGNED] = pmcounters.l1d_prefetch_access_aligned;
      tmp[counter::L1D_PREFETCH_ACCESS_CLC] = pmcounters.l1d_prefetch_access_clc;
      tmp[counter::L1D_PREFETCH_ACCESS_4KX] = pmcounters.l1d_prefetch_access_4kx;
      tmp[counter::L1D_PREFETCH_ACCESS_ALL] = pmcounters.l1d_prefetch_access_all;
      tmp[counter::L1D_MMU_ACCESS] = pmcounters.l1d_mmu_access;
      tmp[counter::L1D_SNOOP_ACCESS] = pmcounters.l1d_snoop_access;
      tmp[counter::L1D_ACCESS_ALL] = pmcounters.l1d_access_all;
      tmp[counter::L1D_READ_MISS] = pmcounters.l1d_read_miss;
      tmp[counter::L1D_WRITE_MISS] = pmcounters.l1d_write_miss;
      tmp[counter::L1D_PREFETCH_MISS] = pmcounters.l1d_prefetch_miss;
      tmp[counter::L1D_MMU_MISS] = pmcounters.l1d_mmu_miss;
      tmp[counter::L1D_SNOOP_MISS] = pmcounters.l1d_snoop_miss;
      tmp[counter::L1D_MISS_ALL] = pmcounters.l1d_miss_all;
      tmp[counter::L1D_CACHE_INVALIDATE_SNOOP] = pmcounters.l1d_cache_invalidate_snoop;
      tmp[counter::L1D_CACHE_INVALIDATE_CMO] = pmcounters.l1d_cache_invalidate_cmo;
      tmp[counter::L1D_CACHE_INVALIDATE_LOAD_EVICTION] = pmcounters.l1d_cache_invalidate_load_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_STORE_EVICTION] = pmcounters.l1d_cache_invalidate_store_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_PREFETCH_EVICTION] = pmcounters.l1d_cache_invalidate_prefetch_eviction;
      tmp[counter::L1D_CACHE_INVALIDATE_ALL] = pmcounters.l1d_cache_invalidate_all;
      tmp[counter::UTLB_MISS] = pmcounters.utlb_miss;
      tmp[counter::DTLB_READ_ACCESS] = pmcounters.dtlb_read_access;
      tmp[counter::DTLB_WRITE_ACCESS] = pmcounters.dtlb_write_access;
      tmp[counter::DTLB_PREFETCH_ACCESS] = pmcounters.dtlb_prefetch_access;
      tmp[counter::DTLB_ACCESS_4K] = pmcounters.dtlb_access_4k;
      tmp[counter::DTLB_ACCESS_HUGEPAGE] = pmcounters.dtlb_access_hugepage;
      tmp[counter::DTLB_ACCESS_CACHEABLE] = pmcounters.dtlb_access_cacheable;
      tmp[counter::DTLB_ACCESS_NONCACHEABLE] = pmcounters.dtlb_access_noncacheable;
      tmp[counter::DTLB_ACCESS_ALL] = pmcounters.dtlb_access_all;
      tmp[counter::DTLB_READ_MISS] = pmcounters.dtlb_read_miss;
      tmp[counter::DTLB_WRITE_MISS] = pmcounters.dtlb_write_miss;
      tmp[counter::DTLB_PREFETCH_MISS] = pmcounters.dtlb_prefetch_miss;
      tmp[counter::DTLB_MISS_4K] = pmcounters.dtlb_miss_4k;
      tmp[counter::DTLB_MISS_HUGEPAGE] = pmcounters.dtlb_miss_hugepage;
      tmp[counter::DTLB_MISS_ALL] = pmcounters.dtlb_miss_all;
      tmp[counter::LEAF_TLB_ACCESS_LS] = pmcounters.leaf_tlb_access_ls;
      tmp[counter::LEAF_TLB_ACCESS_FE] = pmcounters.leaf_tlb_access_fe;
      tmp[counter::LEAF_TLB_ACCESS_PREFETCH] = pmcounters.leaf_tlb_access_prefetch;
      tmp[counter::LEAF_TLB_ACCESS_ALL] = pmcounters.leaf_tlb_access_all;
      tmp[counter::LEAF_TLB_MISS_LS] = pmcounters.leaf_tlb_miss_ls;
      tmp[counter::LEAF_TLB_MISS_FE] = pmcounters.leaf_tlb_miss_fe;
      tmp[counter::LEAF_TLB_MISS_PREFETCH] = pmcounters.leaf_tlb_miss_prefetch;
      tmp[counter::LEAF_TLB_MISS_ALL] = pmcounters.leaf_tlb_miss_all;
      tmp[counter::NONLEAF_TLB_ACCESS_LS] = pmcounters.nonleaf_tlb_access_ls;
      tmp[counter::NONLEAF_TLB_ACCESS_FE] = pmcounters.nonleaf_tlb_access_fe;
      tmp[counter::NONLEAF_TLB_ACCESS_PREFETCH] = pmcounters.nonleaf_tlb_access_prefetch;
      tmp[counter::NONLEAF_TLB_ACCESS_ALL] = pmcounters.nonleaf_tlb_access_all;
      tmp[counter::NONLEAF_TLB_MISS_LS] = pmcounters.nonleaf_tlb_miss_ls;
      tmp[counter::NONLEAF_TLB_MISS_FE] = pmcounters.nonleaf_tlb_miss_fe;
      tmp[counter::NONLEAF_TLB_MISS_PREFETCH] = pmcounters.nonleaf_tlb_miss_prefetch;
      tmp[counter::NONLEAF_TLB_MISS_ALL] = pmcounters.nonleaf_tlb_miss_all;
      tmp[counter::PAGE_WALKS] = pmcounters.page_walks;
      tmp[counter::STALLS_MEM_L1D_MISS] = pmcounters.stalls_mem_l1d_miss;
      tmp[counter::STALLS_MEM_STORES] = pmcounters.stalls_mem_stores;
      tmp[counter::STALLS_MEM_L1DTLB_MISS] = pmcounters.stalls_mem_l1dtlb_miss;
      tmp[counter::LSU_RESYNCS_RAW] = pmcounters.lsu_resyncs_raw;
      tmp[counter::LSU_RESYNCS_RAR] = pmcounters.lsu_resyncs_rar;
      tmp[counter::STLF_HITS] = pmcounters.stlf_hits;
      tmp[counter::LS_REPLAY_LOAD] = pmcounters.ls_replay_load;
      tmp[counter::LS_REPLAY_STORE] = pmcounters.ls_replay_store;
      tmp[counter::LS_REPLAY_PREFETCH] = pmcounters.ls_replay_prefetch;
      tmp[counter::LS_REPLAY_MMU] = pmcounters.ls_replay_mmu;
      tmp[counter::LS_REPLAY_ALL] = pmcounters.ls_replay_all;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_LOAD] = pmcounters.ls_way_predictor_replay_load;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_STORE] = pmcounters.ls_way_predictor_replay_store;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_PREFETCH] = pmcounters.ls_way_predictor_replay_prefetch;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_MMU] = pmcounters.ls_way_predictor_replay_mmu;
      tmp[counter::LS_WAY_PREDICTOR_REPLAY_ALL] = pmcounters.ls_way_predictor_replay_all;
      tmp[counter::SIPT_REPLAY_LOAD] = pmcounters.sipt_replay_load;
      tmp[counter::SIPT_REPLAY_STORE] = pmcounters.sipt_replay_store;
      tmp[counter::SIPT_REPLAY_PREFETCH] = pmcounters.sipt_replay_prefetch;
      tmp[counter::SIPT_REPLAY_MMU] = pmcounters.sipt_replay_mmu;
      tmp[counter::SIPT_REPLAY_ALL] = pmcounters.sipt_replay_all;
      tmp[counter::STLF_REPLAY_LOAD] = pmcounters.stlf_replay_load;
      tmp[counter::STLF_REPLAY_MMU] = pmcounters.stlf_replay_mmu;
      tmp[counter::STLF_REPLAY_ALL] = pmcounters.stlf_replay_all;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_LOAD] = pmcounters.tag_bank_conflict_replay_load;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_STORE] = pmcounters.tag_bank_conflict_replay_store;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_PREFETCH] = pmcounters.tag_bank_conflict_replay_prefetch;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_MMU] = pmcounters.tag_bank_conflict_replay_mmu;
      tmp[counter::TAG_BANK_CONFLICT_REPLAY_ALL] = pmcounters.tag_bank_conflict_replay_all;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_LOAD] = pmcounters.data_bank_conflict_replay_load;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_STORE] = pmcounters.data_bank_conflict_replay_store;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_PREFETCH] = pmcounters.data_bank_conflict_replay_prefetch;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_MMU] = pmcounters.data_bank_conflict_replay_mmu;
      tmp[counter::DATA_BANK_CONFLICT_REPLAY_ALL] = pmcounters.data_bank_conflict_replay_all;
      tmp[counter::FILLBUF_HIT_REPLAY_LOAD] = pmcounters.fillbuf_hit_replay_load;
      tmp[counter::FILLBUF_HIT_REPLAY_STORE] = pmcounters.fillbuf_hit_replay_store;
      tmp[counter::FILLBUF_HIT_REPLAY_MMU] = pmcounters.fillbuf_hit_replay_mmu;
      tmp[counter::FILLBUF_HIT_REPLAY_ALL] = pmcounters.fillbuf_hit_replay_all;
      tmp[counter::TRANSBUF_HIT_REPLAY_LOAD] = pmcounters.transbuf_hit_replay_load;
      tmp[counter::TRANSBUF_HIT_REPLAY_STORE] = pmcounters.transbuf_hit_replay_store;
      tmp[counter::TRANSBUF_HIT_REPLAY_PREFETCH] = pmcounters.transbuf_hit_replay_prefetch;
      tmp[counter::TRANSBUF_HIT_REPLAY_MMU] = pmcounters.transbuf_hit_replay_mmu;
      tmp[counter::TRANSBUF_HIT_REPLAY_ALL] = pmcounters.transbuf_hit_replay_all;
      tmp[counter::REQBUF_HIT_REPLAY_LOAD] = pmcounters.reqbuf_hit_replay_load;
      tmp[counter::REQBUF_HIT_REPLAY_STORE] = pmcounters.reqbuf_hit_replay_store;
      tmp[counter::REQBUF_HIT_REPLAY_MMU] = pmcounters.reqbuf_hit_replay_mmu;
      tmp[counter::REQBUF_HIT_REPLAY_ALL] = pmcounters.reqbuf_hit_replay_all;
      tmp[counter::DTLB_REPLAY_LOAD] = pmcounters.dtlb_replay_load;
      tmp[counter::DTLB_REPLAY_STORE] = pmcounters.dtlb_replay_store;
      tmp[counter::DTLB_REPLAY_PREFETCH] = pmcounters.dtlb_replay_prefetch;
      tmp[counter::DTLB_REPLAY_MMU] = pmcounters.dtlb_replay_mmu;
      tmp[counter::DTLB_REPLAY_ALL] = pmcounters.dtlb_replay_all;
      tmp[counter::RAR_CANNOT_ALLOC] = pmcounters.rar_cannot_alloc;
      tmp[counter::RAW_CANNOT_ALLOC] = pmcounters.raw_cannot_alloc;
      tmp[counter::LDQ_CANNOT_ALLOC] = pmcounters.ldq_cannot_alloc;
      tmp[counter::SMB_CANNOT_ALLOC] = pmcounters.smb_cannot_alloc;
      tmp[counter::REQBUF_CANNOT_ALLOC_LOAD] = pmcounters.reqbuf_cannot_alloc_load;
      tmp[counter::REQBUF_CANNOT_ALLOC_STORE] = pmcounters.reqbuf_cannot_alloc_store;
      tmp[counter::REQBUF_CANNOT_ALLOC_PREFETCH] = pmcounters.reqbuf_cannot_alloc_prefetch;
      tmp[counter::REQBUF_CANNOT_ALLOC_MMU] = pmcounters.reqbuf_cannot_alloc_mmu;
      tmp[counter::REQBUF_CANNOT_ALLOC_ALL] = pmcounters.reqbuf_cannot_alloc_all;
      tmp[counter::FILLBUF_CANNOT_ALLOC] = pmcounters.fillbuf_cannot_alloc;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_LOAD] = pmcounters.transbuf_cannot_alloc_load;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_STORE] = pmcounters.transbuf_cannot_alloc_store;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_PREFETCH] = pmcounters.transbuf_cannot_alloc_prefetch;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_MMU] = pmcounters.transbuf_cannot_alloc_mmu;
      tmp[counter::TRANSBUF_CANNOT_ALLOC_ALL] = pmcounters.transbuf_cannot_alloc_all;
      tmp[counter::PCB_CANNOT_ALLOC_LOAD] = pmcounters.pcb_cannot_alloc_load;
      tmp[counter::PCB_CANNOT_ALLOC_STORE] = pmcounters.pcb_cannot_alloc_store;
      tmp[counter::PCB_CANNOT_ALLOC_ALL] = pmcounters.pcb_cannot_alloc_all;
      tmp[counter::UDB_CANNOT_ALLOC] = pmcounters.udb_cannot_alloc;
      tmp[counter::UDB_DATA_RETURN] = pmcounters.udb_data_return;
      tmp[counter::UDB_LOST] = pmcounters.udb_lost;
      tmp[counter::UWP_ACCESS] = pmcounters.uwp_access;
      tmp[counter::UWP_MISS] = pmcounters.uwp_miss;
      tmp[counter::UWP_TRUE_HIT] = pmcounters.uwp_true_hit;
      tmp[counter::WP_ACCESS] = pmcounters.wp_access;
      tmp[counter::WP_MISS] = pmcounters.wp_miss;
      tmp[counter::WP_TRUE_HIT] = pmcounters.wp_true_hit;
      tmp[counter::MDP_CORRECT_PREDICTION] = pmcounters.mdp_correct_prediction;
      tmp[counter::MDP_FALSE_HIT] = pmcounters.mdp_false_hit;
      tmp[counter::MDP_FALSE_MISS] = pmcounters.mdp_false_miss;
      tmp[counter::MDP_TOTAL_PREDICTION] = pmcounters.mdp_total_prediction;
      tmp[counter::ATOMICS_RETIRED] = pmcounters.atomics_retired;
      tmp[counter::LDST_MASKED_NANO] = pmcounters.ldst_masked_nano;
      tmp[counter::LD_EXECUTED_NANO] = pmcounters.ld_executed_nano;
      tmp[counter::ST_EXECUTED_NANO] = pmcounters.st_executed_nano;
      tmp[counter::PFC_AGT_CANNOT_ALLOC] = pmcounters.pfc_agt_cannot_alloc;
      tmp[counter::PFC_AGT_EVICT] = pmcounters.pfc_agt_evict;
      tmp[counter::PFC_PHT_CANNOT_ALLOC] = pmcounters.pfc_pht_cannot_alloc;
      tmp[counter::PFC_PHT_LOOKUP] = pmcounters.pfc_pht_lookup;
      tmp[counter::PFC_PHT_HIT] = pmcounters.pfc_pht_hit;
      tmp[counter::PFC_PRT_CANNOT_ALLOC] = pmcounters.pfc_prt_cannot_alloc;
      tmp[counter::PFC_NO_TLB_CREDIT_STALLS] = pmcounters.pfc_no_tlb_credit_stalls;
      tmp[counter::PFC_NO_TAG_CREDIT_STALLS] = pmcounters.pfc_no_tag_credit_stalls;
      tmp[counter::PFC_PREFETCHES_SENT] = pmcounters.pfc_prefetches_sent;
      tmp[counter::PFC_PREFETCHES_HIT] = pmcounters.pfc_prefetches_hit;
      tmp[counter::PFC_PREFETCHES_LATE] = pmcounters.pfc_prefetches_late;
      tmp[counter::PFC_USELESS_PREFETCHES] = pmcounters.pfc_useless_prefetches;
      tmp[counter::SC_CACHE_ACCESS] = pmcounters.sc_cache_access;
      tmp[counter::SC_CACHE_RD] = pmcounters.sc_cache_rd;
      tmp[counter::SC_CACHE_MISS] = pmcounters.sc_cache_miss;
      tmp[counter::SC_CACHE_MISS_RD] = pmcounters.sc_cache_miss_rd;
      tmp[counter::SC_CACHE_REFILL] = pmcounters.sc_cache_refill;
      tmp[counter::SC_CACHE_ALLOCATE] = pmcounters.sc_cache_allocate;
      tmp[counter::SC_CACHE_WB_DIRTY] = pmcounters.sc_cache_wb_dirty;
      tmp[counter::SC_CACHE_WB_CLEAN] = pmcounters.sc_cache_wb_clean;
      tmp[counter::SC_CACHE_INVAL] = pmcounters.sc_cache_inval;
      tmp[counter::SC_SNOOP] = pmcounters.sc_snoop;
      tmp[counter::SC_SCRATCHPAD_RD] = pmcounters.sc_scratchpad_rd;
      tmp[counter::SC_SCRATCHPAD_WR] = pmcounters.sc_scratchpad_wr;
      tmp[counter::F2SC_RD] = pmcounters.f2sc_rd;
      tmp[counter::F2SC_WR] = pmcounters.f2sc_wr;
      tmp[counter::MSHR_LIFETIME] = pmcounters.mshr_lifetime;
      tmp[counter::MSHR_ALLOCATIONS] = pmcounters.mshr_allocations;
      tmp[counter::SC2F_RD_U] = pmcounters.sc2f_rd_u;
      tmp[counter::SC2F_RD_C] = pmcounters.sc2f_rd_c;
      tmp[counter::SC2F_RD_O] = pmcounters.sc2f_rd_o;
      tmp[counter::SC2F_WR] = pmcounters.sc2f_wr;
      tmp[counter::C2SC_RD_I] = pmcounters.c2sc_rd_i;
      tmp[counter::C2SC_RD_D] = pmcounters.c2sc_rd_d;
      tmp[counter::C2SC_WB_FULL] = pmcounters.c2sc_wb_full;
      tmp[counter::C2SC_EVICT] = pmcounters.c2sc_evict;
      tmp[counter::C2SC_SNP_WB_FULL] = pmcounters.c2sc_snp_wb_full;
      tmp[counter::C2SC_WRNOSNPPTL] = pmcounters.c2sc_wrnosnpptl;
      tmp[counter::C2SC_SNP] = pmcounters.c2sc_snp;
      tmp[counter::C2SC_REQ_STALL] = pmcounters.c2sc_req_stall;
      tmp[counter::C2SC_WDAT_STALL] = pmcounters.c2sc_wdat_stall;
      tmp[counter::C2SC_SRSP_STALL] = pmcounters.c2sc_srsp_stall;
      tmp[counter::C2SC_RDAT_STALL] = pmcounters.c2sc_rdat_stall;
      tmp[counter::C2SC_SNP_STALL] = pmcounters.c2sc_snp_stall;
      tmp[counter::C2SC_CRSP_STALL] = pmcounters.c2sc_crsp_stall;
      tmp[counter::SC2F_EVICT] = pmcounters.sc2f_evict;
      tmp[counter::SC2F_WRBACKFULL] = pmcounters.sc2f_wrbackfull;
      tmp[counter::SC2F_WDAT] = pmcounters.sc2f_wdat;
      tmp[counter::SC2F_SNOOP] = pmcounters.sc2f_snoop;
      tmp[counter::SC2F_RDAT] = pmcounters.sc2f_rdat;
      tmp[counter::SC2F_REQ_STALL] = pmcounters.sc2f_req_stall;
      tmp[counter::SC2F_WDAT_STALL] = pmcounters.sc2f_wdat_stall;
      tmp[counter::SC2F_SRSP_STALL] = pmcounters.sc2f_srsp_stall;
      tmp[counter::SC2F_RDAT_STALL] = pmcounters.sc2f_rdat_stall;
      tmp[counter::SC2F_SNOOP_STALL] = pmcounters.sc2f_snoop_stall;
      tmp[counter::SC2F_CRSP_STALL] = pmcounters.sc2f_crsp_stall;
      tmp[counter::F2SC_WDAT] = pmcounters.f2sc_wdat;
      tmp[counter::F2SC_RDAT] = pmcounters.f2sc_rdat;
      tmp[counter::F2SC_WRNOSNPPTL] = pmcounters.f2sc_wrnosnpptl;
      tmp[counter::F2SC_REQ_STALL] = pmcounters.f2sc_req_stall;
      tmp[counter::F2SC_WDAT_STALL] = pmcounters.f2sc_wdat_stall;
      tmp[counter::F2SC_RDAT_STALL] = pmcounters.f2sc_rdat_stall;
      tmp[counter::F2SC_CRSP_STALL] = pmcounters.f2sc_crsp_stall;
      tmp[counter::SC_TAG_LOOKUP] = pmcounters.sc_tag_lookup;
      tmp[counter::SC_TAG_WRITE] = pmcounters.sc_tag_write;
      tmp[counter::SC_STATE_WRITE] = pmcounters.sc_state_write;
      tmp[counter::SC_REPL_WRITE] = pmcounters.sc_repl_write;
      tmp[counter::SC_TAG_HIT] = pmcounters.sc_tag_hit;
      tmp[counter::SC_DATA_READ] = pmcounters.sc_data_read;
      tmp[counter::SC_DATA_WRITE] = pmcounters.sc_data_write;
      tmp[counter::SC_STATE_I2E] = pmcounters.sc_state_i2e;
      tmp[counter::SC_STATE_I2M] = pmcounters.sc_state_i2m;
      tmp[counter::SC_STATE_I2S] = pmcounters.sc_state_i2s;
      tmp[counter::SC_STATE_S2I] = pmcounters.sc_state_s2i;
      tmp[counter::SC_STATE_S2M] = pmcounters.sc_state_s2m;
      tmp[counter::SC_STATE_S2E] = pmcounters.sc_state_s2e;
      tmp[counter::SC_STATE_M2I] = pmcounters.sc_state_m2i;
      tmp[counter::SC_STATE_M2S] = pmcounters.sc_state_m2s;
      tmp[counter::SC_STATE_M2E] = pmcounters.sc_state_m2e;
      tmp[counter::SC_STATE_E2I] = pmcounters.sc_state_e2i;
      tmp[counter::SC_STATE_E2S] = pmcounters.sc_state_e2s;
      tmp[counter::SC_STATE_E2M] = pmcounters.sc_state_e2m;
      tmp[counter::SFT_LOOKUP] = pmcounters.sft_lookup;
      tmp[counter::SFT_HIT] = pmcounters.sft_hit;
      tmp[counter::SFT_WRITE] = pmcounters.sft_write;
      tmp[counter::SFT_EVICTION] = pmcounters.sft_eviction;
      tmp[counter::SFT_SNP_SINGLE_ICACHE] = pmcounters.sft_snp_single_icache;
      tmp[counter::SFT_SNP_SINGLE_DCACHE] = pmcounters.sft_snp_single_dcache;
      tmp[counter::SFT_SNP_MULTI_CORES] = pmcounters.sft_snp_multi_cores;
      tmp[counter::SFT_EVICTION_REPLAY] = pmcounters.sft_eviction_replay;
      tmp[counter::MSHR_OCCUPANCY] = pmcounters.mshr_occupancy;
      tmp[counter::MSHR_FULL] = pmcounters.mshr_full;
      tmp[counter::MSHR_SAQ_ALLOC] = pmcounters.mshr_saq_alloc;
      tmp[counter::MSHR_SAQ_FULL] = pmcounters.mshr_saq_full;
      tmp[counter::NO_ALLOC_NO_MSHR] = pmcounters.no_alloc_no_mshr;
      tmp[counter::NO_ALLOC_HINT_NOT_SET] = pmcounters.no_alloc_hint_not_set;
      tmp[counter::SC_REPLAY_ECC] = pmcounters.sc_replay_ecc;

      return tmp;
    }

    
    const std::unordered_map<counter, std::string_view> to_string =
    {
      {CPU_CYCLES,"cpu_cycles"},
      {INSTRUCTIONS,"instructions"},
      {BRANCH_INSTRUCTION,"branch_instruction"},
      {M_MODE_CYCLES,"m_mode_cycles"},
      {M_MODE_INSTRET,"m_mode_instret"},
      {S_MODE_CYCLES,"s_mode_cycles"},
      {S_MODE_INSTRET,"s_mode_instret"},
      {U_MODE_CYCLES,"u_mode_cycles"},
      {U_MODE_INSTRET,"u_mode_instret"},
      {REF_CPU_CYCLES,"ref_cpu_cycles"},
      {STALLS_BST_FULL,"stalls_bst_full"},
      {STALLS_PFX_FULL,"stalls_pfx_full"},
      {STALLS_INDIRECT_MISS,"stalls_indirect_miss"},
      {STALLS_ICACHE_MISS,"stalls_icache_miss"},
      {STALLS_ITLB_MISS,"stalls_itlb_miss"},
      {STALLS_IRB_FULL,"stalls_irb_full"},
      {STALLS_IFBUF_FULL,"stalls_ifbuf_full"},
      {STALLS_EXCEPTION,"stalls_exception"},
      {PAGE_CROSSING_FETCHBLOCKS,"page_crossing_fetchblocks"},
      {NFP_EARLY_REDIRECT,"nfp_early_redirect"},
      {NFP_LATE_REDIRECT,"nfp_late_redirect"},
      {IFBUF_FULL_REDIRECT,"ifbuf_full_redirect"},
      {NONSPEC_RESYNC,"nonspec_resync"},
      {FAULT_RESYNC,"fault_resync"},
      {FAULT_REFETCH,"fault_refetch"},
      {CMODE_ENTRY,"cmode_entry"},
      {BRANCH_MISSES,"branch_misses"},
      {BR_RET_MISSES,"br_ret_misses"},
      {IND_BR_MISSES,"ind_br_misses"},
      {REL_BR_MISSES,"rel_br_misses"},
      {SPEC_BRANCH_REDIRECT,"spec_branch_redirect"},
      {SPEC_LSU_RESYNCS,"spec_lsu_resyncs"},
      {TOTAL_FLUSHES,"total_flushes"},
      {UOPS_DECODED,"uops_decoded"},
      {L1I_READ_ACCESS,"l1i_read_access"},
      {L1I_READ_MISS,"l1i_read_miss"},
      {L1I_PREFETCH_ACCESS,"l1i_prefetch_access"},
      {L1I_PREFETCH_MISS,"l1i_prefetch_miss"},
      {ITLB_READ_ACCESS,"itlb_read_access"},
      {ITLB_READ_MISS,"itlb_read_miss"},
      {ITLB_PREFETCH_ACCESS,"itlb_prefetch_access"},
      {ITLB_PREFETCH_MISS,"itlb_prefetch_miss"},
      {IC_WAY_MISPRED,"ic_way_mispred"},
      {RAS_UNDERFLOW,"ras_underflow"},
      {RAS_OVERFLOW,"ras_overflow"},
      {NUM_FETCHGROUPS,"num_fetchgroups"},
      {BDP_BANK_CONFLICTS,"bdp_bank_conflicts"},
      {BTP_BANK_CONFLICTS,"btp_bank_conflicts"},
      {BPU_WRITES,"bpu_writes"},
      {STALLED_CYCLES_FRONTEND,"stalled_cycles_frontend"},
      {STALLED_CYCLES_BACKEND,"stalled_cycles_backend"},
      {CYCLES_NO_INT_PRN,"cycles_no_int_prn"},
      {CYCLES_NO_FP_PRN,"cycles_no_fp_prn"},
      {CYCLES_NO_VEC_PRN,"cycles_no_vec_prn"},
      {CYCLES_NO_VL_PRN,"cycles_no_vl_prn"},
      {CYCLES_NO_VM_PRN,"cycles_no_vm_prn"},
      {CYCLES_NO_ROB,"cycles_no_rob"},
      {OP_RETIRED_DIRECT_BRANCH,"op_retired_direct_branch"},
      {OP_RETIRED_RET_BRANCH,"op_retired_ret_branch"},
      {OP_RETIRED_INDIRECT_BRANCH,"op_retired_indirect_branch"},
      {OP_RETIRED_COND_BRANCH,"op_retired_cond_branch"},
      {OP_RETIRED_LD,"op_retired_ld"},
      {OP_RETIRED_ST,"op_retired_st"},
      {OP_RETIRED_INT,"op_retired_int"},
      {OP_RETIRED_CSR,"op_retired_csr"},
      {OP_RETIRED_FP,"op_retired_fp"},
      {OP_RETIRED_VEC,"op_retired_vec"},
      {OP_COMPLETE_LD,"op_complete_ld"},
      {OP_COMPLETE_ST,"op_complete_st"},
      {OP_COMPLETE_INT,"op_complete_int"},
      {OP_COMPLETE_FP,"op_complete_fp"},
      {OP_COMPLETE_VEC,"op_complete_vec"},
      {OP_ISSUED_PIPE0,"op_issued_pipe0"},
      {OP_ISSUED_PIPE1,"op_issued_pipe1"},
      {OP_ISSUED_PIPE2,"op_issued_pipe2"},
      {OP_ISSUED_PIPE3,"op_issued_pipe3"},
      {OP_ISSUED_PIPE4,"op_issued_pipe4"},
      {OP_ISSUED_PIPE5,"op_issued_pipe5"},
      {OP_ISSUED_PIPE6,"op_issued_pipe6"},
      {OP_ISSUED_PIPE7,"op_issued_pipe7"},
      {OP_ISSUED_PIPE8,"op_issued_pipe8"},
      {OP_ISSUED_PIPE9,"op_issued_pipe9"},
      {OP_ISSUED_PIPE10,"op_issued_pipe10"},
      {OP_ISSUED_PIPE11,"op_issued_pipe11"},
      {OP_ISSUED_PIPE12,"op_issued_pipe12"},
      {OP_ISSUED_PIPE13,"op_issued_pipe13"},
      {OP_ISSUED_PIPE14,"op_issued_pipe14"},
      {OP_ISSUED_PIPE15,"op_issued_pipe15"},
      {CACHE_REFERENCES,"cache_references"},
      {CACHE_MISSES,"cache_misses"},
      {TLB_INVALIDATES,"tlb_invalidates"},
      {L1D_READ_ACCESS_ALIGNED,"l1d_read_access_aligned"},
      {L1D_READ_ACCESS_CLC,"l1d_read_access_clc"},
      {L1D_READ_ACCESS_4KX,"l1d_read_access_4kx"},
      {L1D_READ_ACCESS_ALL,"l1d_read_access_all"},
      {L1D_WRITE_ACCESS_ALIGNED,"l1d_write_access_aligned"},
      {L1D_WRITE_ACCESS_CLC,"l1d_write_access_clc"},
      {L1D_WRITE_ACCESS_4KX,"l1d_write_access_4kx"},
      {L1D_WRITE_ACCESS_ALL,"l1d_write_access_all"},
      {L1D_PREFETCH_ACCESS_ALIGNED,"l1d_prefetch_access_aligned"},
      {L1D_PREFETCH_ACCESS_CLC,"l1d_prefetch_access_clc"},
      {L1D_PREFETCH_ACCESS_4KX,"l1d_prefetch_access_4kx"},
      {L1D_PREFETCH_ACCESS_ALL,"l1d_prefetch_access_all"},
      {L1D_MMU_ACCESS,"l1d_mmu_access"},
      {L1D_SNOOP_ACCESS,"l1d_snoop_access"},
      {L1D_ACCESS_ALL,"l1d_access_all"},
      {L1D_READ_MISS,"l1d_read_miss"},
      {L1D_WRITE_MISS,"l1d_write_miss"},
      {L1D_PREFETCH_MISS,"l1d_prefetch_miss"},
      {L1D_MMU_MISS,"l1d_mmu_miss"},
      {L1D_SNOOP_MISS,"l1d_snoop_miss"},
      {L1D_MISS_ALL,"l1d_miss_all"},
      {L1D_CACHE_INVALIDATE_SNOOP,"l1d_cache_invalidate_snoop"},
      {L1D_CACHE_INVALIDATE_CMO,"l1d_cache_invalidate_cmo"},
      {L1D_CACHE_INVALIDATE_LOAD_EVICTION,"l1d_cache_invalidate_load_eviction"},
      {L1D_CACHE_INVALIDATE_STORE_EVICTION,"l1d_cache_invalidate_store_eviction"},
      {L1D_CACHE_INVALIDATE_PREFETCH_EVICTION,"l1d_cache_invalidate_prefetch_eviction"},
      {L1D_CACHE_INVALIDATE_ALL,"l1d_cache_invalidate_all"},
      {UTLB_MISS,"utlb_miss"},
      {DTLB_READ_ACCESS,"dtlb_read_access"},
      {DTLB_WRITE_ACCESS,"dtlb_write_access"},
      {DTLB_PREFETCH_ACCESS,"dtlb_prefetch_access"},
      {DTLB_ACCESS_4K,"dtlb_access_4k"},
      {DTLB_ACCESS_HUGEPAGE,"dtlb_access_hugepage"},
      {DTLB_ACCESS_CACHEABLE,"dtlb_access_cacheable"},
      {DTLB_ACCESS_NONCACHEABLE,"dtlb_access_noncacheable"},
      {DTLB_ACCESS_ALL,"dtlb_access_all"},
      {DTLB_READ_MISS,"dtlb_read_miss"},
      {DTLB_WRITE_MISS,"dtlb_write_miss"},
      {DTLB_PREFETCH_MISS,"dtlb_prefetch_miss"},
      {DTLB_MISS_4K,"dtlb_miss_4k"},
      {DTLB_MISS_HUGEPAGE,"dtlb_miss_hugepage"},
      {DTLB_MISS_ALL,"dtlb_miss_all"},
      {LEAF_TLB_ACCESS_LS,"leaf_tlb_access_ls"},
      {LEAF_TLB_ACCESS_FE,"leaf_tlb_access_fe"},
      {LEAF_TLB_ACCESS_PREFETCH,"leaf_tlb_access_prefetch"},
      {LEAF_TLB_ACCESS_ALL,"leaf_tlb_access_all"},
      {LEAF_TLB_MISS_LS,"leaf_tlb_miss_ls"},
      {LEAF_TLB_MISS_FE,"leaf_tlb_miss_fe"},
      {LEAF_TLB_MISS_PREFETCH,"leaf_tlb_miss_prefetch"},
      {LEAF_TLB_MISS_ALL,"leaf_tlb_miss_all"},
      {NONLEAF_TLB_ACCESS_LS,"nonleaf_tlb_access_ls"},
      {NONLEAF_TLB_ACCESS_FE,"nonleaf_tlb_access_fe"},
      {NONLEAF_TLB_ACCESS_PREFETCH,"nonleaf_tlb_access_prefetch"},
      {NONLEAF_TLB_ACCESS_ALL,"nonleaf_tlb_access_all"},
      {NONLEAF_TLB_MISS_LS,"nonleaf_tlb_miss_ls"},
      {NONLEAF_TLB_MISS_FE,"nonleaf_tlb_miss_fe"},
      {NONLEAF_TLB_MISS_PREFETCH,"nonleaf_tlb_miss_prefetch"},
      {NONLEAF_TLB_MISS_ALL,"nonleaf_tlb_miss_all"},
      {PAGE_WALKS,"page_walks"},
      {STALLS_MEM_L1D_MISS,"stalls_mem_l1d_miss"},
      {STALLS_MEM_STORES,"stalls_mem_stores"},
      {STALLS_MEM_L1DTLB_MISS,"stalls_mem_l1dtlb_miss"},
      {LSU_RESYNCS_RAW,"lsu_resyncs_raw"},
      {LSU_RESYNCS_RAR,"lsu_resyncs_rar"},
      {STLF_HITS,"stlf_hits"},
      {LS_REPLAY_LOAD,"ls_replay_load"},
      {LS_REPLAY_STORE,"ls_replay_store"},
      {LS_REPLAY_PREFETCH,"ls_replay_prefetch"},
      {LS_REPLAY_MMU,"ls_replay_mmu"},
      {LS_REPLAY_ALL,"ls_replay_all"},
      {LS_WAY_PREDICTOR_REPLAY_LOAD,"ls_way_predictor_replay_load"},
      {LS_WAY_PREDICTOR_REPLAY_STORE,"ls_way_predictor_replay_store"},
      {LS_WAY_PREDICTOR_REPLAY_PREFETCH,"ls_way_predictor_replay_prefetch"},
      {LS_WAY_PREDICTOR_REPLAY_MMU,"ls_way_predictor_replay_mmu"},
      {LS_WAY_PREDICTOR_REPLAY_ALL,"ls_way_predictor_replay_all"},
      {SIPT_REPLAY_LOAD,"sipt_replay_load"},
      {SIPT_REPLAY_STORE,"sipt_replay_store"},
      {SIPT_REPLAY_PREFETCH,"sipt_replay_prefetch"},
      {SIPT_REPLAY_MMU,"sipt_replay_mmu"},
      {SIPT_REPLAY_ALL,"sipt_replay_all"},
      {STLF_REPLAY_LOAD,"stlf_replay_load"},
      {STLF_REPLAY_MMU,"stlf_replay_mmu"},
      {STLF_REPLAY_ALL,"stlf_replay_all"},
      {TAG_BANK_CONFLICT_REPLAY_LOAD,"tag_bank_conflict_replay_load"},
      {TAG_BANK_CONFLICT_REPLAY_STORE,"tag_bank_conflict_replay_store"},
      {TAG_BANK_CONFLICT_REPLAY_PREFETCH,"tag_bank_conflict_replay_prefetch"},
      {TAG_BANK_CONFLICT_REPLAY_MMU,"tag_bank_conflict_replay_mmu"},
      {TAG_BANK_CONFLICT_REPLAY_ALL,"tag_bank_conflict_replay_all"},
      {DATA_BANK_CONFLICT_REPLAY_LOAD,"data_bank_conflict_replay_load"},
      {DATA_BANK_CONFLICT_REPLAY_STORE,"data_bank_conflict_replay_store"},
      {DATA_BANK_CONFLICT_REPLAY_PREFETCH,"data_bank_conflict_replay_prefetch"},
      {DATA_BANK_CONFLICT_REPLAY_MMU,"data_bank_conflict_replay_mmu"},
      {DATA_BANK_CONFLICT_REPLAY_ALL,"data_bank_conflict_replay_all"},
      {FILLBUF_HIT_REPLAY_LOAD,"fillbuf_hit_replay_load"},
      {FILLBUF_HIT_REPLAY_STORE,"fillbuf_hit_replay_store"},
      {FILLBUF_HIT_REPLAY_MMU,"fillbuf_hit_replay_mmu"},
      {FILLBUF_HIT_REPLAY_ALL,"fillbuf_hit_replay_all"},
      {TRANSBUF_HIT_REPLAY_LOAD,"transbuf_hit_replay_load"},
      {TRANSBUF_HIT_REPLAY_STORE,"transbuf_hit_replay_store"},
      {TRANSBUF_HIT_REPLAY_PREFETCH,"transbuf_hit_replay_prefetch"},
      {TRANSBUF_HIT_REPLAY_MMU,"transbuf_hit_replay_mmu"},
      {TRANSBUF_HIT_REPLAY_ALL,"transbuf_hit_replay_all"},
      {REQBUF_HIT_REPLAY_LOAD,"reqbuf_hit_replay_load"},
      {REQBUF_HIT_REPLAY_STORE,"reqbuf_hit_replay_store"},
      {REQBUF_HIT_REPLAY_MMU,"reqbuf_hit_replay_mmu"},
      {REQBUF_HIT_REPLAY_ALL,"reqbuf_hit_replay_all"},
      {DTLB_REPLAY_LOAD,"dtlb_replay_load"},
      {DTLB_REPLAY_STORE,"dtlb_replay_store"},
      {DTLB_REPLAY_PREFETCH,"dtlb_replay_prefetch"},
      {DTLB_REPLAY_MMU,"dtlb_replay_mmu"},
      {DTLB_REPLAY_ALL,"dtlb_replay_all"},
      {RAR_CANNOT_ALLOC,"rar_cannot_alloc"},
      {RAW_CANNOT_ALLOC,"raw_cannot_alloc"},
      {LDQ_CANNOT_ALLOC,"ldq_cannot_alloc"},
      {SMB_CANNOT_ALLOC,"smb_cannot_alloc"},
      {REQBUF_CANNOT_ALLOC_LOAD,"reqbuf_cannot_alloc_load"},
      {REQBUF_CANNOT_ALLOC_STORE,"reqbuf_cannot_alloc_store"},
      {REQBUF_CANNOT_ALLOC_PREFETCH,"reqbuf_cannot_alloc_prefetch"},
      {REQBUF_CANNOT_ALLOC_MMU,"reqbuf_cannot_alloc_mmu"},
      {REQBUF_CANNOT_ALLOC_ALL,"reqbuf_cannot_alloc_all"},
      {FILLBUF_CANNOT_ALLOC,"fillbuf_cannot_alloc"},
      {TRANSBUF_CANNOT_ALLOC_LOAD,"transbuf_cannot_alloc_load"},
      {TRANSBUF_CANNOT_ALLOC_STORE,"transbuf_cannot_alloc_store"},
      {TRANSBUF_CANNOT_ALLOC_PREFETCH,"transbuf_cannot_alloc_prefetch"},
      {TRANSBUF_CANNOT_ALLOC_MMU,"transbuf_cannot_alloc_mmu"},
      {TRANSBUF_CANNOT_ALLOC_ALL,"transbuf_cannot_alloc_all"},
      {PCB_CANNOT_ALLOC_LOAD,"pcb_cannot_alloc_load"},
      {PCB_CANNOT_ALLOC_STORE,"pcb_cannot_alloc_store"},
      {PCB_CANNOT_ALLOC_ALL,"pcb_cannot_alloc_all"},
      {UDB_CANNOT_ALLOC,"udb_cannot_alloc"},
      {UDB_DATA_RETURN,"udb_data_return"},
      {UDB_LOST,"udb_lost"},
      {UWP_ACCESS,"uwp_access"},
      {UWP_MISS,"uwp_miss"},
      {UWP_TRUE_HIT,"uwp_true_hit"},
      {WP_ACCESS,"wp_access"},
      {WP_MISS,"wp_miss"},
      {WP_TRUE_HIT,"wp_true_hit"},
      {MDP_CORRECT_PREDICTION,"mdp_correct_prediction"},
      {MDP_FALSE_HIT,"mdp_false_hit"},
      {MDP_FALSE_MISS,"mdp_false_miss"},
      {MDP_TOTAL_PREDICTION,"mdp_total_prediction"},
      {ATOMICS_RETIRED,"atomics_retired"},
      {LDST_MASKED_NANO,"ldst_masked_nano"},
      {LD_EXECUTED_NANO,"ld_executed_nano"},
      {ST_EXECUTED_NANO,"st_executed_nano"},
      {PFC_AGT_CANNOT_ALLOC,"pfc_agt_cannot_alloc"},
      {PFC_AGT_EVICT,"pfc_agt_evict"},
      {PFC_PHT_CANNOT_ALLOC,"pfc_pht_cannot_alloc"},
      {PFC_PHT_LOOKUP,"pfc_pht_lookup"},
      {PFC_PHT_HIT,"pfc_pht_hit"},
      {PFC_PRT_CANNOT_ALLOC,"pfc_prt_cannot_alloc"},
      {PFC_NO_TLB_CREDIT_STALLS,"pfc_no_tlb_credit_stalls"},
      {PFC_NO_TAG_CREDIT_STALLS,"pfc_no_tag_credit_stalls"},
      {PFC_PREFETCHES_SENT,"pfc_prefetches_sent"},
      {PFC_PREFETCHES_HIT,"pfc_prefetches_hit"},
      {PFC_PREFETCHES_LATE,"pfc_prefetches_late"},
      {PFC_USELESS_PREFETCHES,"pfc_useless_prefetches"},
      {SC_CACHE_ACCESS,"sc_cache_access"},
      {SC_CACHE_RD,"sc_cache_rd"},
      {SC_CACHE_MISS,"sc_cache_miss"},
      {SC_CACHE_MISS_RD,"sc_cache_miss_rd"},
      {SC_CACHE_REFILL,"sc_cache_refill"},
      {SC_CACHE_ALLOCATE,"sc_cache_allocate"},
      {SC_CACHE_WB_DIRTY,"sc_cache_wb_dirty"},
      {SC_CACHE_WB_CLEAN,"sc_cache_wb_clean"},
      {SC_CACHE_INVAL,"sc_cache_inval"},
      {SC_SNOOP,"sc_snoop"},
      {SC_SCRATCHPAD_RD,"sc_scratchpad_rd"},
      {SC_SCRATCHPAD_WR,"sc_scratchpad_wr"},
      {F2SC_RD,"f2sc_rd"},
      {F2SC_WR,"f2sc_wr"},
      {MSHR_LIFETIME,"mshr_lifetime"},
      {MSHR_ALLOCATIONS,"mshr_allocations"},
      {SC2F_RD_U,"sc2f_rd_u"},
      {SC2F_RD_C,"sc2f_rd_c"},
      {SC2F_RD_O,"sc2f_rd_o"},
      {SC2F_WR,"sc2f_wr"},
      {C2SC_RD_I,"c2sc_rd_i"},
      {C2SC_RD_D,"c2sc_rd_d"},
      {C2SC_WB_FULL,"c2sc_wb_full"},
      {C2SC_EVICT,"c2sc_evict"},
      {C2SC_SNP_WB_FULL,"c2sc_snp_wb_full"},
      {C2SC_WRNOSNPPTL,"c2sc_wrnosnpptl"},
      {C2SC_SNP,"c2sc_snp"},
      {C2SC_REQ_STALL,"c2sc_req_stall"},
      {C2SC_WDAT_STALL,"c2sc_wdat_stall"},
      {C2SC_SRSP_STALL,"c2sc_srsp_stall"},
      {C2SC_RDAT_STALL,"c2sc_rdat_stall"},
      {C2SC_SNP_STALL,"c2sc_snp_stall"},
      {C2SC_CRSP_STALL,"c2sc_crsp_stall"},
      {SC2F_EVICT,"sc2f_evict"},
      {SC2F_WRBACKFULL,"sc2f_wrbackfull"},
      {SC2F_WDAT,"sc2f_wdat"},
      {SC2F_SNOOP,"sc2f_snoop"},
      {SC2F_RDAT,"sc2f_rdat"},
      {SC2F_REQ_STALL,"sc2f_req_stall"},
      {SC2F_WDAT_STALL,"sc2f_wdat_stall"},
      {SC2F_SRSP_STALL,"sc2f_srsp_stall"},
      {SC2F_RDAT_STALL,"sc2f_rdat_stall"},
      {SC2F_SNOOP_STALL,"sc2f_snoop_stall"},
      {SC2F_CRSP_STALL,"sc2f_crsp_stall"},
      {F2SC_WDAT,"f2sc_wdat"},
      {F2SC_RDAT,"f2sc_rdat"},
      {F2SC_WRNOSNPPTL,"f2sc_wrnosnpptl"},
      {F2SC_REQ_STALL,"f2sc_req_stall"},
      {F2SC_WDAT_STALL,"f2sc_wdat_stall"},
      {F2SC_RDAT_STALL,"f2sc_rdat_stall"},
      {F2SC_CRSP_STALL,"f2sc_crsp_stall"},
      {SC_TAG_LOOKUP,"sc_tag_lookup"},
      {SC_TAG_WRITE,"sc_tag_write"},
      {SC_STATE_WRITE,"sc_state_write"},
      {SC_REPL_WRITE,"sc_repl_write"},
      {SC_TAG_HIT,"sc_tag_hit"},
      {SC_DATA_READ,"sc_data_read"},
      {SC_DATA_WRITE,"sc_data_write"},
      {SC_STATE_I2E,"sc_state_i2e"},
      {SC_STATE_I2M,"sc_state_i2m"},
      {SC_STATE_I2S,"sc_state_i2s"},
      {SC_STATE_S2I,"sc_state_s2i"},
      {SC_STATE_S2M,"sc_state_s2m"},
      {SC_STATE_S2E,"sc_state_s2e"},
      {SC_STATE_M2I,"sc_state_m2i"},
      {SC_STATE_M2S,"sc_state_m2s"},
      {SC_STATE_M2E,"sc_state_m2e"},
      {SC_STATE_E2I,"sc_state_e2i"},
      {SC_STATE_E2S,"sc_state_e2s"},
      {SC_STATE_E2M,"sc_state_e2m"},
      {SFT_LOOKUP,"sft_lookup"},
      {SFT_HIT,"sft_hit"},
      {SFT_WRITE,"sft_write"},
      {SFT_EVICTION,"sft_eviction"},
      {SFT_SNP_SINGLE_ICACHE,"sft_snp_single_icache"},
      {SFT_SNP_SINGLE_DCACHE,"sft_snp_single_dcache"},
      {SFT_SNP_MULTI_CORES,"sft_snp_multi_cores"},
      {SFT_EVICTION_REPLAY,"sft_eviction_replay"},
      {MSHR_OCCUPANCY,"mshr_occupancy"},
      {MSHR_FULL,"mshr_full"},
      {MSHR_SAQ_ALLOC,"mshr_saq_alloc"},
      {MSHR_SAQ_FULL,"mshr_saq_full"},
      {NO_ALLOC_NO_MSHR,"no_alloc_no_mshr"},
      {NO_ALLOC_HINT_NOT_SET,"no_alloc_hint_not_set"},
      {SC_REPLAY_ECC,"sc_replay_ecc"},
    };

  pmu(cvm::topology::loc_t, unsigned);
  ~pmu();

  void report();
  void ipc_check();

  // snapshot current counter values, to be used in perf region
  void perf_region_start() {
    assert(perf_region.size() == counters.size());

    for (size_t i = 0; i < perf_region.size(); i++)
      perf_region[i] = counters[i];

    perf_start_cycle = counters[CPU_CYCLES];
  }

  void perf_region_end() {
    assert(perf_region.size() == counters.size());

    for (size_t i = 0; i < perf_region.size(); i++) {
      perf_region[i] = counters[i] - perf_region[i];
    }

    perf_end_cycle = counters[CPU_CYCLES];
  }

  bool is_within_range(double, double, int);
  void process(const rv_tester_transactions::pmu::pmcounters<> &pmcounters);
  void process(const rv_tester::terminate_called_fast &);
  std::string trigger_str(const rv_tester_transactions::pmu::pmcounters<> &pmcounters);

  bool shutdown_ready();

private:
  cvm::file_logger log;
  cvm::topology::loc_t loc_;
  unsigned id_;

  std::vector<uint64_t> counters;

  uint64_t perf_start_cycle = 0;
  uint64_t perf_end_cycle = 0;
  std::vector<uint64_t> perf_region;

  std::atomic<bool> terminated_ = false;
  std::atomic<bool> sync_terminate_ = false;
};
