from typing import List, Dict, Any
import argparse

pmcounter_dpi_width = 24

def parse_core_csv(data_str: str) -> List[Dict[Any, Any]]:
    """Parse core PMC CSV data into a list of event dictionaries."""
    core_data_dict = []
    core_events = data_str.split('\n')
    
    skip_header = True
    for event in core_events:
        if skip_header:
            skip_header = False
            continue
        if event:
            desc = event.split(',')
            core_data_dict.append({
                "name": desc[1], 
                "description": desc[2], 
                "event_id": desc[0], 
                "unit": desc[4], 
                "multi_hot_encoding": desc[11], 
                "multi_D_filter": desc[12]
            })
    
    # Add synthetic events
    core_data_dict.append({
        "name": "branch_instructions", 
        "description": "Sum of retired branches", 
        "event_id": -1, 
        "unit": "FE", 
        "multi_hot_encoding": "No", 
        "multi_D_filter": "No"
    })
    core_data_dict.append({
        "name": "tb_cycles", 
        "description": "Event for each TB cycle", 
        "event_id": -1, 
        "unit": "FE", 
        "multi_hot_encoding": "No", 
        "multi_D_filter": "No"
    })
    
    return core_data_dict

def parse_sc_csv(data_str: str) -> List[Dict[Any, Any]]:
    """Parse shared cache PMC CSV data into a list of event dictionaries."""
    sc_data_dict = []
    sc_events = data_str.split('\n')
    
    sc_skip_header = True
    for event in sc_events:
        if sc_skip_header:
            sc_skip_header = False
            continue
        if event:
            desc = event.split(',')
            sc_data_dict.append({
                "name": desc[1], 
                "description": desc[2], 
                "event_id": desc[0]
            })
    
    # Add synthetic event
    sc_data_dict.append({
        "name": "sc_tb_cycles", 
        "description": "Event for each TB cycle", 
        "event_id": -1
    })
    
    return sc_data_dict

# Functions
def create_cpp_frag(core_events: List[Dict[Any, Any]], sc_events: List[Dict[Any, Any]], path_core="gen_events_core.hpp", path_sc="gen_events_sc.hpp"):
    pmevents = [core_events, sc_events]
    tab = "      "
    paths = [path_core, path_sc]

    enum_post_core = """    COUNT_CORE
    } counter_core;"""
    enum_post_sc = """    COUNT_SC
    } counter_sc;"""
    enum_posts = [enum_post_core, enum_post_sc]

    to_vec_pre_core = f"""
    void core_to_vector(const rv_tester_transactions::pmu_core::pmcounters_core<>& pmcounters){{

      const uint64_t casting_size_term = uint64_t(1) << {pmcounter_dpi_width};

"""
    to_vec_pre_sc = f"""
    void sc_to_vector(const rv_tester_transactions::pmu_sc::pmcounters_sc<>& pmcounters){{

      const uint64_t casting_size_term = uint64_t(1) << {pmcounter_dpi_width};

"""
    to_vec_pres = [to_vec_pre_core, to_vec_pre_sc]

    counter_configs = ["counters_core", "counters_sc"]
    rv_tester_transaction_configs = ["counter_core","counter_sc"]

    to_strings = ["core_to_string", "sc_to_string"]

    for events, path, enum_post, to_vec_pre, counter_config, rv_tester_transaction_config, to_string in zip(pmevents, paths, enum_posts, to_vec_pres, counter_configs, rv_tester_transaction_configs, to_strings):
      f = open(path, "w")
      
      # Add header guard
      guard = path.upper().replace('.', '_').replace('/', '_').replace('-', '_')
      f.write(f"#ifndef {guard}\n")
      f.write(f"#define {guard}\n\n")
      f.write("// AUTOGENERATED -- DO NOT EDIT\n\n")
      
      enum_pre = """typedef enum : size_t {"""
      f.write(enum_pre)
      f.write("\n")
      for event in events:
          name = event["name"]
          description = event["description"]
          f.write(f"      //{description}")
          f.write("\n")
          f.write(f"      {name.upper()},")
          f.write("\n")
      f.write(enum_post)

      to_vec_post = """
    }

    """
      f.write('\n\n')
      f.write(to_vec_pre)
      for event in events:
          name = event["name"]
          f.write(f"{tab}{counter_config}[{rv_tester_transaction_config}::{name.upper()}] = {counter_config}[{rv_tester_transaction_config}::{name.upper()}] + ((pmcounters.{name} - ({counter_config}[{rv_tester_transaction_config}::{name.upper()}] % casting_size_term)) % casting_size_term);")
          f.write("\n")
      f.write(to_vec_post)

      reflection_pre = f"""
    const std::map<{rv_tester_transaction_config}, std::string_view> {to_string} = {{
"""
      f.write(reflection_pre)
      for event in events:
          name = event["name"]
          f.write(f'{tab}{{{name.upper()},"{name}"}},')
          f.write('\n')
      f.write('    };')
      if path == path_core:
        event_map_pre = """

    const std::unordered_map<uint64_t, size_t> event_map = {
"""
        f.write(event_map_pre)
        for event in core_events:
            name = event["name"]
            event_id = event["event_id"]
            f.write(f'{tab}{{{event_id},counter_core::{name.upper()}}},')
            f.write('\n')
        f.write('    };')

        filtered_event_map_pre = """

    const std::unordered_map<uint64_t, std::unordered_map<uint16_t, size_t>> filtered_event_map = {
"""
        f.write(filtered_event_map_pre)
        filtered_csv = []
        filter_event_dict = {}
        for event in core_events:
            if (event["multi_hot_encoding"] == "Yes" and event["multi_D_filter"] == "No"):
                filtered_csv.append({
                    'event_31_16': event["event_id"][0:6],
                    'event_15_0': event["event_id"][6:10],
                    'name': event['name'],
                })
        for row in filtered_csv:
            parent = row['event_31_16']
            if parent not in filter_event_dict:
                filter_event_dict[parent] = {}
            filter_event_dict[parent][row['event_15_0']] = row['name']
        if '0x1462' in filter_event_dict: filter_event_dict['0x1862'] = filter_event_dict.pop('0x1462') #op_complete filtered event granularity should be 16
        if '0x1440' in filter_event_dict: filter_event_dict['0x1840'] = filter_event_dict.pop('0x1440') #op_issued filtered event granularity should be 16
        for parent, child_dict in filter_event_dict.items():
            filter_map_str = f"{tab}{{{parent}," + "{"
            for child, event_name in child_dict.items():
                bit_position = "0x"+child if child != '0' else None
                filter_map_str += f'\n{tab}{tab}{{{bit_position},counter_core::{event_name.upper()}}},'
            filter_map_str += "\n"+ f'{tab}{tab}'+"}\n"+f'{tab}'+"},\n"
            f.write(filter_map_str)
        f.write(f'    '+"};")
      
      # Close header guard
      f.write(f"\n\n#endif // {guard}\n")
      f.close()


def create_sv_frag(events: List[Dict[Any, Any]], path="gen_events.sv", prefix="", skip_pre = False):
    tab = "      "
    ignore_names = ["cpu_cycles", "instructions", "branch_instructions", "tb_cycles"]
    tab = "    "
    f = open(path, 'w')
    f.write("// AUTOGENERATED -- DO NOT EDIT\n")
    pre_core = f"""
localparam MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE = 32;
parameter OVERFLOW_BIT = {pmcounter_dpi_width} - 1;
parameter OVERFLOW_BIT_EXTRA = 2;
logic overflow;
logic [EVENT_COUNT + SC_EVENT_COUNT + OVERFLOW_BIT_EXTRA -1 : 0] pmcounter_overflow_bit;

if (OVERFLOW_BIT < ($clog2(MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE) + 1))
    $fatal(1, "The selected overflow bit cannot cover the maximum value change of a counter within a single clock cycle.");


assign pmcounters_cores[0].valid = !reset && perf_enabled && (overflow || (|mhpm_write) || terminate || cycle_sync_condition || instruction_sync_condition || perf_start || perf_end);
assign pmcounters_cores[0].data.location = location;
    assign pmcounters_cores[0].data.tb_cycles = 24'(clocks - tb_cycles_offset);
    assign pmcounters_cores[0].data.cpu_cycles = {pmcounter_dpi_width}'(cpu_cycles);
    assign pmcounters_cores[0].data.instructions = {pmcounter_dpi_width}'(pmcounter[INSTRUCTIONS]);
    assign pmcounters_cores[0].data.branch_instructions = {pmcounter_dpi_width}'(branch_instructions);
    assign pmcounters_cores[0].data.perf_start = perf_start;
    assign pmcounters_cores[0].data.perf_end = perf_end;
    assign pmcounters_cores[0].data.terminate = terminate;
    assign pmcounters_cores[0].data.overflow = overflow;
    assign pmcounters_cores[0].data.sync = cycle_sync_condition || instruction_sync_condition;
"""
    pre_sc = f"""
    generate
        if (SC_PMCI_ENABLED == 1) begin
             assign  pmcounters_scs[0].valid = pmcounters_cores[0].valid;
             assign pmcounters_scs[0].data.location = pmcounters_cores[0].data.location;
             assign pmcounters_scs[0].data.sc_tb_cycles = 24'(clocks - tb_cycles_offset);
             assign pmcounters_scs[0].data.perf_start_sc = pmcounters_cores[0].data.perf_start;
             assign pmcounters_scs[0].data.perf_end_sc = pmcounters_cores[0].data.perf_end;
             assign pmcounters_scs[0].data.terminate_sc = terminate;
             assign pmcounters_scs[0].data.overflow_sc = pmcounters_cores[0].data.overflow;
             assign pmcounters_scs[0].data.sync_sc = pmcounters_cores[0].data.sync;
"""
    post_sc = f"""
        end
    endgenerate

    // AUTOGENERATED -- off
"""
    if not skip_pre:
        f.write(pre_core)
    else:
        f.write(pre_sc)

    for event in events:
        name = event["name"]
        if name in ignore_names:
            continue
        if prefix == "":
            f.write(
                f"{tab * 1}assign pmcounters_cores[0].data.{name} = {pmcounter_dpi_width}'({prefix}pmcounter[{name.upper()}]);")
        elif prefix == "sc_":
            f.write(
                f"{tab * 3}assign pmcounters_scs[0].data.{name} = {pmcounter_dpi_width}'({prefix}pmci[{name.upper()}]);")
        f.write('\n')
    if skip_pre:
        f.write(post_sc)


def create_defines_frag(events: List[Dict[Any, Any]], prefix="", path="gen_defines.sv"):
    f = open(path, 'w')
    f.write("// AUTOGENERATED -- DO NOT EDIT\n")
    prelude = "typedef enum {\n"
    poslude = f"""    {prefix.upper()}EVENT_COUNT
}} {prefix}pmc_event_t;"""

    f.write(prelude)
    for event in events:
        name = event["name"]
        f.write(f"    {name.upper()},\n")
    f.write(poslude)
    f.close()


def create_yaml_frag_core(events: List[Dict[Any, Any]], path="gen_core_events.yaml"):
    """Generate complete pmu_core YAML port section for packet_gen file merging.

    The generated fragment is a complete port section that gets concatenated
    into the merged YAML file by packet_gen's merge_definitions().
    """
    tab = "    "
    f = open(path, 'w')
    f.write(f"# AUTOGENERATED -- DO NOT EDIT\n")
    f.write(f"pmu_core:\n")
    f.write(f"{tab}num: ${{TOP.PLATFORM.NHARTS}}\n")
    f.write(f"{tab}pmcounters_core:\n")
    f.write(f"{tab * 2}domain: 1\n")
    f.write(f"{tab * 2}num: 1\n")
    f.write(f"{tab * 2}fields:\n")

    for event in events:
        name = event["name"]
        f.write(f"{tab * 3}{name}:\n")
        f.write(f"{tab * 4}width: {pmcounter_dpi_width}\n")

    # Add control signals
    f.write(f"{tab * 3}perf_start:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}perf_end:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}terminate:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}overflow:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}sync:\n")
    f.write(f"{tab * 4}width: 1\n")

    # Add hpmcounters_core packet
    f.write(f"{tab}hpmcounters_core:\n")
    f.write(f"{tab * 2}domain: 1\n")
    f.write(f"{tab * 2}num: 1\n")
    f.write(f"{tab * 2}fields:\n")
    for i in range(3, 11):
        f.write(f"{tab * 3}hpmcounter{i}:\n")
        f.write(f"{tab * 4}width: 64\n")

    # Add pmc_checker packet
    f.write(f"{tab}pmc_checker:\n")
    f.write(f"{tab * 2}domain: 1\n")
    f.write(f"{tab * 2}num: ${{max(TOP.PLATFORM.COSIM.RVFI.NRETS)}}\n")
    f.write(f"{tab * 2}fields:\n")
    f.write(f"{tab * 3}terminate:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}event_csr:\n")
    f.write(f"{tab * 4}width: 4\n")
    f.write(f"{tab * 3}event_id:\n")
    f.write(f"{tab * 4}width: 56\n")

    f.close()


def create_yaml_frag_sc(events: List[Dict[Any, Any]], path="gen_sc_events.yaml"):
    """Generate complete pmu_sc YAML port section for packet_gen file merging.

    The generated fragment is a complete port section that gets concatenated
    into the merged YAML file by packet_gen's merge_definitions().
    """
    tab = "    "
    f = open(path, 'w')
    f.write(f"# AUTOGENERATED -- DO NOT EDIT\n")
    f.write(f"pmu_sc:\n")
    f.write(f"{tab}num: 1\n")
    f.write(f"{tab}pmcounters_sc:\n")
    f.write(f"{tab * 2}domain: 1\n")
    f.write(f"{tab * 2}num: 1\n")
    f.write(f"{tab * 2}fields:\n")

    for event in events:
        name = event["name"]
        f.write(f"{tab * 3}{name}:\n")
        f.write(f"{tab * 4}width: {pmcounter_dpi_width}\n")

    # Add control signals with _sc suffix
    f.write(f"{tab * 3}perf_start_sc:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}perf_end_sc:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}terminate_sc:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}overflow_sc:\n")
    f.write(f"{tab * 4}width: 1\n")
    f.write(f"{tab * 3}sync_sc:\n")
    f.write(f"{tab * 4}width: 1\n")

    f.close()

def create_monitor_frag(events: List[Dict[Any, Any]], prefix="", path="gen_monitor.sv"):
    f = open(path, 'w')
    f.write("// AUTOGENERATED -- DO NOT EDIT\n")
    prelude = """always_comb begin
"""
    poslude = """end
"""
    f.write(prelude)
    for event in events:
        name = event["name"]
        f.write(f"    {prefix}pmci[{name.upper()}] = {name};\n")
    f.write(poslude)
    f.close()

def generate_pmu_sv_content(core_events: List[Dict[Any, Any]], sc_events: List[Dict[Any, Any]], pmu_template: str) -> str:
    """Generate complete pmu.sv content by replacing the include placeholder with generated code."""
    tab = "    "
    ignore_names = ["cpu_cycles", "instructions", "branch_instructions", "tb_cycles", "sc_tb_cycles"]

    # NOTE: Do NOT generate typedef enums here - they are already defined in rv_tester_defines.sv
    # The gen_core_defines.sv and gen_sc_defines.sv includes should be removed, not replaced
    core_defines = "// NOTE: pmc_event_t enum is defined in rv_tester_defines.sv"
    sc_defines = "// NOTE: sc_pmc_event_t enum is defined in rv_tester_defines.sv"

    # Generate core events
    core_events_code = f"""// AUTOGENERATED -- DO NOT EDIT

localparam MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE = 32;
parameter OVERFLOW_BIT = {pmcounter_dpi_width} - 1;
parameter OVERFLOW_BIT_EXTRA = 2;
logic overflow;
logic [EVENT_COUNT + SC_EVENT_COUNT + OVERFLOW_BIT_EXTRA -1 : 0] pmcounter_overflow_bit;

if (OVERFLOW_BIT < ($clog2(MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE) + 1))
    $fatal(1, "The selected overflow bit cannot cover the maximum value change of a counter within a single clock cycle.");

assign pmcounters_cores[0].valid = !reset && perf_enabled && (overflow || (|mhpm_write) || terminate || cycle_sync_condition || instruction_sync_condition || perf_start || perf_end);
assign pmcounters_cores[0].data.location = location;
    assign pmcounters_cores[0].data.tb_cycles = 24'(clocks - tb_cycles_offset);
    assign pmcounters_cores[0].data.cpu_cycles = {pmcounter_dpi_width}'(cpu_cycles);
    assign pmcounters_cores[0].data.instructions = {pmcounter_dpi_width}'(pmcounter[INSTRUCTIONS]);
    assign pmcounters_cores[0].data.branch_instructions = {pmcounter_dpi_width}'(branch_instructions);
    assign pmcounters_cores[0].data.perf_start = perf_start;
    assign pmcounters_cores[0].data.perf_end = perf_end;
    assign pmcounters_cores[0].data.terminate = terminate;
    assign pmcounters_cores[0].data.overflow = overflow;
    assign pmcounters_cores[0].data.sync = cycle_sync_condition || instruction_sync_condition;
"""
    for event in core_events:
        name = event["name"]
        if name in ignore_names:
            continue
        core_events_code += f"{tab}assign pmcounters_cores[0].data.{name} = {pmcounter_dpi_width}'(pmcounter[{name.upper()}]);\n"

    # Generate SC events
    sc_events_code = f"""// AUTOGENERATED -- DO NOT EDIT

    generate
        if (SC_PMCI_ENABLED == 1) begin
             assign  pmcounters_scs[0].valid = pmcounters_cores[0].valid;
             assign pmcounters_scs[0].data.location = pmcounters_cores[0].data.location;
             assign pmcounters_scs[0].data.sc_tb_cycles = 24'(clocks - tb_cycles_offset);
             assign pmcounters_scs[0].data.perf_start_sc = pmcounters_cores[0].data.perf_start;
             assign pmcounters_scs[0].data.perf_end_sc = pmcounters_cores[0].data.perf_end;
             assign pmcounters_scs[0].data.terminate_sc = terminate;
             assign pmcounters_scs[0].data.overflow_sc = pmcounters_cores[0].data.overflow;
             assign pmcounters_scs[0].data.sync_sc = pmcounters_cores[0].data.sync;
"""
    for event in sc_events:
        name = event["name"]
        if name in ignore_names:
            continue
        sc_events_code += f"{tab * 3}assign pmcounters_scs[0].data.{name} = {pmcounter_dpi_width}'(sc_pmci[{name.upper()}]);\n"
    sc_events_code += """
        end
    endgenerate

    // AUTOGENERATED -- off
"""

    # Replace placeholders in template
    result = pmu_template
    result = result.replace('`include "gen_core_defines.sv"', core_defines)
    result = result.replace('`include "gen_sc_defines.sv"', sc_defines)
    result = result.replace('`include "gen_core_events.sv"', core_events_code)
    result = result.replace('`include "gen_sc_events.sv"', sc_events_code)

    return result


def main():
    parser = argparse.ArgumentParser(description='Generate PMU parameter files from CSV specifications')
    parser.add_argument('--core_pmc_csv', required=True, help='Path to core PMC CSV file')
    parser.add_argument('--sc_pmc_csv', required=True, help='Path to shared cache PMC CSV file')
    parser.add_argument('--gen_events_core_hpp', required=True, help='Output path for core events C++ header')
    parser.add_argument('--gen_events_sc_hpp', required=True, help='Output path for SC events C++ header')
    parser.add_argument('--gen_core_events_sv', required=True, help='Output path for core events SystemVerilog')
    parser.add_argument('--gen_sc_events_sv', required=True, help='Output path for SC events SystemVerilog')
    parser.add_argument('--gen_core_defines_sv', required=True, help='Output path for core defines SystemVerilog')
    parser.add_argument('--gen_sc_defines_sv', required=True, help='Output path for SC defines SystemVerilog')
    parser.add_argument('--gen_core_monitor_sv', required=True, help='Output path for core monitor SystemVerilog')
    parser.add_argument('--gen_sc_monitor_sv', required=True, help='Output path for SC monitor SystemVerilog')
    parser.add_argument('--gen_core_events_yaml', required=True, help='Output path for core events YAML')
    parser.add_argument('--gen_sc_events_yaml', required=True, help='Output path for SC events YAML')
    parser.add_argument('--pmu_template_sv', required=False, help='Path to pmu.sv template file')
    parser.add_argument('--gen_pmu_sv', required=False, help='Output path for generated pmu.sv')
    args = parser.parse_args()

    # Read CSV files
    with open(args.core_pmc_csv, 'r') as f:
        core_data_str = f.read()
    with open(args.sc_pmc_csv, 'r') as f:
        sc_data_str = f.read()

    # Parse CSVs
    core_data_dict = parse_core_csv(core_data_str)
    sc_data_dict = parse_sc_csv(sc_data_str)

    # Generate files with explicit paths
    create_cpp_frag(core_data_dict, sc_data_dict,
                    path_core=args.gen_events_core_hpp,
                    path_sc=args.gen_events_sc_hpp)
    create_sv_frag(core_data_dict, args.gen_core_events_sv, "", False)
    create_sv_frag(sc_data_dict, args.gen_sc_events_sv, "sc_", True)
    create_defines_frag(core_data_dict, "", args.gen_core_defines_sv)
    create_defines_frag(sc_data_dict, "sc_", args.gen_sc_defines_sv)
    create_monitor_frag(core_data_dict, "", args.gen_core_monitor_sv)
    create_monitor_frag(sc_data_dict, "sc_", args.gen_sc_monitor_sv)
    create_yaml_frag_core(core_data_dict, args.gen_core_events_yaml)
    create_yaml_frag_sc(sc_data_dict, args.gen_sc_events_yaml)

    # Generate complete pmu.sv if template provided
    if args.pmu_template_sv and args.gen_pmu_sv:
        with open(args.pmu_template_sv, 'r') as f:
            pmu_template = f.read()
        pmu_sv_content = generate_pmu_sv_content(core_data_dict, sc_data_dict, pmu_template)
        with open(args.gen_pmu_sv, 'w') as f:
            f.write(pmu_sv_content)

if __name__ == "__main__":
    main()
