

import requests
from typing import List, Dict, Any
import datetime

import yaml
def download_yaml(url):
    response = requests.get(url)
    response.raise_for_status()  # Check for any HTTP errors
    yaml_data = response.text
    data_dict = yaml.safe_load(yaml_data)
    return data_dict


# Example usage
url = "https://aus-gitlab.local.tenstorrent.com/arch/perf.yaml/-/raw/main/counters.yaml"
data_dict = download_yaml(url)
# print(data_dict)


def create_cpp_frag(events: List[Dict[Any, Any]], path="gen_events.cpp"):
    tab = "      "
    f = open(path, "w")
    enum_pre = """
    //AUTOGENERATED -- NO TOUCH

    typedef enum : size_t {"""
    f.write(enum_pre)
    f.write("\n")
    enum_post = """    COUNT
    } counter;"""
    for event in events:
        name = event["name"]
        description = event["description"]
        f.write(f"      //{description}")
        f.write("\n")
        f.write(f"      {name.upper()},")
        f.write("\n")
    f.write(enum_post)
    to_vec_pre = """
    //AUTOGENERATED -- NO TOUCH

std::vector<uint64_t> to_vector(const rv_tester_transactions::pmu::pmcounters& pmcounters)
    {
      std::vector<uint64_t> tmp(counter::COUNT);
    
      """
    to_vec_post = """
      return tmp;
    }

    """
    f.write('\n\n')
    f.write(to_vec_pre)
    for event in events:
        name = event["name"]
        f.write(f"{tab}tmp[counter::{name.upper()}] = pmcounters.{name};")
        f.write("\n")
    f.write(to_vec_post)

    reflection_pre = """
    const std::unordered_map<counter, std::string_view> to_string =
      {
"""
    f.write(reflection_pre)
    for event in events:
        name = event["name"]
        f.write(f'{tab}{{{name.upper()},"{name}"}},')
        f.write('\n')
    f.write('    };')

def create_sv_frag(events: List[Dict[Any, Any]], path="gen_events.sv"):
    tab = "      "
    ignore_names = ["cpu_cycles", "instructions"]

    pre = """
    //AUTOGENERATED -- NO TOUCH
    assign pmcounterss[0].valid = !reset && perf_enabled && (terminate || (sync & (cpu_cycles % period) == 0));
    assign pmcounterss[0].data.location = location;
    assign pmcounterss[0].data.cpu_cycles = cpu_cycles;
    assign pmcounterss[0].data.instructions = instructions;
"""
    f = open(path, 'w')
    f.write(pre)
    for event in events:
        name = event["name"]
        if name in ignore_names:
            continue
        f.write(f"    assign pmcounterss[0].data.{name} = pmcounter[{name.upper()}];")
        f.write('\n')

def create_defines_frag(events: List[Dict[Any, Any]], path="defines.sv"):
    prelude = "    //AUTOGENERATED -- NOTOUCH \n    typedef enum {\n"
    poslude = """        EVENT_COUNT
    } pmc_event_t;"""
    f = open(path, 'w')
    f.write(prelude)
    for event in events:
        name = event["name"]
        f.write(f"        {name.upper()},\n")
    f.write(poslude)

def create_yaml_frag(events: List[Dict[Any, Any]], path="events.yaml"):
    tab = "    "
    prelude = f"{tab *2}#AUTOGENERATED -- NOTOUCH \n{tab*2}fields:\n"
    f = open(path, 'w')
    f.write(prelude)

    for event in events:
        name = event["name"]
        f.write(f"{tab * 3}{name}:\n")
        f.write(f"{tab * 4}width: 64\n")


create_cpp_frag(data_dict)
create_sv_frag(data_dict)
create_defines_frag(data_dict)
create_yaml_frag(data_dict)
