import requests
from typing import List, Dict, Any
import datetime

import yaml
import os
import base64
from pathlib import Path

pmcounter_dpi_width = 24

def download_csv(url):
    with open(Path.home() / ".gitlab_key", "r") as key:
        headers = {
            'PRIVATE-TOKEN': key.read().strip()
        }

        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Check for any HTTP errors
        yaml_data = response.text
        data_dict = yaml.safe_load(yaml_data)
        content = data_dict['content']
        base64_bytes = content.encode("ascii")

        sample_string_bytes = base64.b64decode(base64_bytes)
        rv_str = sample_string_bytes.decode("utf-8")
        return rv_str


# Core pmc events
spec_id = 595
url = f"https://aus-gitlab.local.tenstorrent.com/api/v4//projects/{spec_id}/repository/files/uarch%2Fascalon_uarch%2Fsrc%2Fcore_pmc%2Ecsv?ref=main"
data_str = download_csv(url)
core_data_dict = []
core_events = data_str.split('\n')

# Sharedcache pmc events
sc_url = f"https://aus-gitlab.local.tenstorrent.com/api/v4//projects/{spec_id}/repository/files/uarch%2Fascalon_uarch%2Fsrc%2Fsharedcache_pmc%2Ecsv?ref=main"
sc_data_str = download_csv(sc_url)
sc_data_dict = []
sc_events = sc_data_str.split('\n')

# could use pandas here
skip_header = True
for event in core_events:
    if skip_header:
        skip_header = False
        continue
    if event:
        desc = event.split(',')
        core_data_dict.append({"name": desc[1], "description": desc[2], "event_id": desc[0], "unit": desc[4], "multi_hot_encoding":desc[11], "multi_D_filter":desc[12]})
core_data_dict.append({"name": "branch_instructions", "description": "Sum of retired branches", "event_id": -1, "unit": "FE", "multi_hot_encoding":"No", "multi_D_filter":"No"})
core_data_dict.append({"name": "tb_cycles", "description": "Event for each TB cycle", "event_id": -1, "unit": "FE", "multi_hot_encoding":"No", "multi_D_filter":"No"})

sc_skip_header = True
for event in sc_events:
    if sc_skip_header:
        sc_skip_header = False
        continue
    if event:
        desc = event.split(',')
        sc_data_dict.append({"name": desc[1], "description": desc[2], "event_id": desc[0]})

data_dict = core_data_dict + sc_data_dict

# Functions
def create_cpp_frag(core_events: List[Dict[Any, Any]],sc_events: List[Dict[Any, Any]], path_core="gen_events_core.hpp", path_sc="gen_events_sc.hpp"):
    pmevents = [core_events, sc_events]
    tab = "      "
    paths = [path_core, path_sc]

    enum_post_core = """    COUNT_CORE
    } counter_core;"""
    enum_post_sc = """    COUNT_SC
    } counter_sc;"""
    enum_posts = [enum_post_core, enum_post_sc]

    to_vec_pre_core = f"""
    void core_to_vector(const rv_tester_transactions::pmu_core::pmcounters_core<>& pmcounters){{
    
      const uint64_t casting_size_term = uint64_t(1) << {pmcounter_dpi_width};

"""
    to_vec_pre_sc = f"""
    void sc_to_vector(const rv_tester_transactions::pmu_sc::pmcounters_sc<>& pmcounters){{
    
      const uint64_t casting_size_term = uint64_t(1) << {pmcounter_dpi_width};

"""
    to_vec_pres = [to_vec_pre_core, to_vec_pre_sc]

    counter_configs = ["counters_core", "counters_sc"]
    rv_tester_transaction_configs = ["counter_core","counter_sc"]

    to_strings = ["core_to_string", "sc_to_string"]

    for events, path, enum_post, to_vec_pre, counter_config, rv_tester_transaction_config, to_string in zip(pmevents, paths, enum_posts, to_vec_pres, counter_configs, rv_tester_transaction_configs, to_strings):
      f = open(path, "w")
      enum_pre = """//AUTOGENERATED -- NO TOUCH

    typedef enum : size_t {"""
      f.write(enum_pre)
      f.write("\n")
      for event in events:
          name = event["name"]
          description = event["description"]
          f.write(f"      //{description}")
          f.write("\n")
          f.write(f"      {name.upper()},")
          f.write("\n")
      f.write(enum_post)
  
      to_vec_post = """
    }

    """
      f.write('\n\n')
      f.write(to_vec_pre)
      for event in events:
          name = event["name"]
          f.write(f"{tab}{counter_config}[{rv_tester_transaction_config}::{name.upper()}] = {counter_config}[{rv_tester_transaction_config}::{name.upper()}] + ((pmcounters.{name} - ({counter_config}[{rv_tester_transaction_config}::{name.upper()}] % casting_size_term)) % casting_size_term);")
          f.write("\n")
      f.write(to_vec_post)
      
      reflection_pre = f"""
    const std::unordered_map<{rv_tester_transaction_config}, std::string_view> {to_string} = {{
"""
      f.write(reflection_pre)
      for event in events:
          name = event["name"]
          f.write(f'{tab}{{{name.upper()},"{name}"}},')
          f.write('\n')
      f.write('    };')
      if path == path_core:
        event_map_pre = """

    const std::unordered_map<uint64_t, size_t> event_map = {
"""
        f.write(event_map_pre)
        for event in core_events:
            name = event["name"]
            event_id = event["event_id"]
            f.write(f'{tab}{{{event_id},counter_core::{name.upper()}}},')
            f.write('\n')
        f.write('    };')
      
        filtered_event_map_pre = """

    const std::unordered_map<uint64_t, std::unordered_map<uint16_t, size_t>> filtered_event_map = {
"""
        f.write(filtered_event_map_pre)
        filtered_csv = []
        filter_event_dict = {}
        for event in core_events:
            if (event["multi_hot_encoding"] == "Yes" and event["multi_D_filter"] == "No"):
                filtered_csv.append({
                    'event_31_16': event["event_id"][0:6],
                    'event_15_0': event["event_id"][6:10],
                    'name': event['name'],
                })
        for row in filtered_csv:
            parent = row['event_31_16']
            if parent not in filter_event_dict:
                filter_event_dict[parent] = {}
            filter_event_dict[parent][row['event_15_0']] = row['name']
        if '0x1462' in filter_event_dict: filter_event_dict['0x1862'] = filter_event_dict.pop('0x1462') #op_complete filtered event granularity should be 16 
        if '0x1440' in filter_event_dict: filter_event_dict['0x1840'] = filter_event_dict.pop('0x1440') #op_issued filtered event granularity should be 16 
        for parent, child_dict in filter_event_dict.items():
            filter_map_str = f"{tab}{{{parent}," + "{"
            for child, event_name in child_dict.items():
                bit_position = "0x"+child if child != '0' else None
                filter_map_str += f'\n{tab}{tab}{{{bit_position},counter_core::{event_name.upper()}}},'
            filter_map_str += "\n"+ f'{tab}{tab}'+"}\n"+f'{tab}'+"},\n"
            f.write(filter_map_str)
        f.write(f'    '+"};")
        filtered_event_map_post="""

//AUTOGENERATED -- END
"""
        f.write(filtered_event_map_post)


def create_sv_frag(events: List[Dict[Any, Any]], path="gen_events.sv", prefix="", skip_pre = False):
    tab = "      "
    ignore_names = ["cpu_cycles", "instructions", "branch_instructions", "tb_cycles"]
    tab = "    "
    f = open(path, 'w')
    pre_core = f"""
    //AUTOGENERATED -- NO TOUCH
    localparam MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE = 32;
    parameter OVERFLOW_BIT = {pmcounter_dpi_width} - 1;
    if (OVERFLOW_BIT < ($clog2(MAX_COUNTER_VALUE_CHANGE_IN_ONE_CYCLE) + 1)) $error("The selected overflow bit cannot cover the maximum value change of a counter within a single clock cycle.");
    parameter OVERFLOW_BIT_EXTRA = 2;
    logic overflow;
    logic [EVENT_COUNT + SC_EVENT_COUNT + OVERFLOW_BIT_EXTRA -1 : 0] pmcounter_overflow_bit;
    assign pmcounters_cores[0].valid = !reset && perf_enabled && (overflow || (|mhpm_write) || terminate || (cycle_sync_en && (sync_cycles % period) == 0) || (instruction_sync_en && (((prev_sync_instructions % instructions) > nret) && ((sync_instructions % instructions) < nret))) || perf_start || perf_end);
    assign pmcounters_cores[0].data.location = location;
    assign pmcounters_cores[0].data.tb_cycles = 24'(clocks - tb_cycles_offset);
    assign pmcounters_cores[0].data.cpu_cycles = {pmcounter_dpi_width}'(cpu_cycles);
    assign pmcounters_cores[0].data.instructions = {pmcounter_dpi_width}'(pmcounter[INSTRUCTIONS]);
    assign pmcounters_cores[0].data.branch_instructions = {pmcounter_dpi_width}'(branch_instructions);
    assign pmcounters_cores[0].data.perf_start = perf_start;
    assign pmcounters_cores[0].data.perf_end = perf_end;
    assign pmcounters_cores[0].data.terminate = terminate;
    assign pmcounters_cores[0].data.overflow = overflow;
    assign pmcounters_cores[0].data.sync = (cycle_sync_en && (sync_cycles % period) == 0) || (instruction_sync_en && (((prev_sync_instructions % instructions) > nret) && ((sync_instructions % instructions) < nret)));
"""
    pre_sc = f"""
    generate
        if (SC_PMCI_ENABLED == 1) begin
             assign  pmcounters_scs[0].valid = pmcounters_cores[0].valid;
             assign pmcounters_scs[0].data.location = pmcounters_cores[0].data.location;
             assign pmcounters_scs[0].data.perf_start_sc = pmcounters_cores[0].data.perf_start;
             assign pmcounters_scs[0].data.perf_end_sc = pmcounters_cores[0].data.perf_end;
             assign pmcounters_scs[0].data.terminate_sc = terminate;
             assign pmcounters_scs[0].data.overflow_sc = pmcounters_cores[0].data.overflow;
             assign pmcounters_scs[0].data.sync_sc = pmcounters_cores[0].data.sync;
"""
    post_sc = f"""
        end
    endgenerate

    // AUTOGENERATED -- off
"""
    if not skip_pre:
        f.write(pre_core)
    else:
        f.write(pre_sc)

    for event in events:
        name = event["name"]
        if name in ignore_names:
            continue
        if prefix == "":
            f.write(
                f"{tab * 1}assign pmcounters_cores[0].data.{name} = {pmcounter_dpi_width}'({prefix}pmcounter[{name.upper()}]);")
        elif prefix == "sc_":
            f.write(
                f"{tab * 3}assign pmcounters_scs[0].data.{name} = {pmcounter_dpi_width}'({prefix}pmci[{name.upper()}]);")
        f.write('\n')
    if skip_pre:
        f.write(post_sc)


def create_defines_frag(events: List[Dict[Any, Any]], prefix="", path="gen_defines.sv"):
    prelude = "    //AUTOGENERATED -- NOTOUCH \n    typedef enum {\n"
    poslude = f"""        {prefix.upper()}EVENT_COUNT
    }} {prefix}pmc_event_t;"""

    f = open(path, 'w')
    f.write(prelude)
    for event in events:
        name = event["name"]
        f.write(f"        {name.upper()},\n")
    f.write(poslude)


def create_yaml_frag(events: List[Dict[Any, Any]], path="gen_events.yaml", prefix=""):
    tab = "    "
    f = open(path, 'w')
    prelude = f"  #AUTOGENERATED -- NOTOUCH \n{tab*2}fields:\n"
    f.write(prelude)

    for event in events:
        name = event["name"]
        f.write(f"{tab * 3}{name}:\n")
        f.write(f"{tab * 4}width: {pmcounter_dpi_width}\n")

    poslude =f"""            perf_start{prefix}:
                width: 1
            perf_end{prefix}:
                width: 1
            terminate{prefix}:
                width: 1
            overflow{prefix}:
                width: 1
            sync{prefix}:
                width: 1
  #AUTOGENERATED -- off"""
    f.write(poslude)

def create_monitor_frag(events: List[Dict[Any, Any]], prefix="", path="gen_monitor.sv"):
    prelude = """
    always_comb begin
    """
    poslude = """
    end
    """
    f = open(path, 'w')
    f.write(prelude)
    for event in events:
        name = event["name"]
        f.write(f"        {prefix}pmci[{name.upper()}] = {name};\n")
    f.write(poslude)

create_cpp_frag(core_data_dict, sc_data_dict)
create_sv_frag(core_data_dict, "gen_core_events.sv", "",)
create_sv_frag(sc_data_dict, "gen_sc_events.sv", "sc_", True)
create_defines_frag(core_data_dict, "", "gen_core_defines.sv")
create_defines_frag(sc_data_dict, "sc_", "gen_sc_defines.sv")
create_monitor_frag(core_data_dict, "", "gen_core_monitor.sv")
create_monitor_frag(sc_data_dict, "sc_", "gen_sc_monitor.sv")
create_yaml_frag(core_data_dict, "gen_core_events.yaml", "")
create_yaml_frag(sc_data_dict, "gen_sc_events.yaml", "_sc")
