#include "axi_sw_mst.h"

DEFINE_bool(axi_allow_slverr_resp, false, "Allow Slave error responses on axi_mst transactions");
DEFINE_bool(axi_allow_decerr_resp, false, "Allow Decode error responses on axi_mst transactions");
DEFINE_bool(axi_rand_id_alloc, true, "Allow random ID allocation for axi_mst transactions");
DEFINE_bool(axi_disable_seqid_alloc, false, "Disable Cluster AXI sequence based ID allocation");
DEFINE_bool(axi_sw_mst_greedy_queue, false, "Enables greedy behavior for transaction queue. This prevents HOL blocking on C++ side.");
DEFINE_bool(axi_sw_rsp_toggle_en, false, "Allow axi_sw_rsp_toggle_en responses on axi_mst transactions");
DEFINE_int32(axi_mst_brdy_high, 4, "Maximum cycles of axi bready assertion");
DEFINE_int32(axi_mst_brdy_low, 4, "Maximum  cycles of axi bready de-assertion");
DEFINE_int32(axi_mst_rrdy_high, 4, "Maximum  cycles of axi rready assertion");
DEFINE_int32(axi_mst_rrdy_low, 4, "Maximum  cycles of axi rready de-assertion");
DEFINE_int64(axi_sw_rsp_toggle_start, 1000, "cycles of axi clock for axi_sw_rsp_toggle_start ");
DEFINE_uint32(axi_resp_timeout, 10000, "Cycles to wait after Transactor-id pool overflow condition before raising no free ids error");

extern "C" {

  // SV DPI exports generated by the AXI_SW_DPI_FIFO macro (axi_sw_mst_ar/aw/w).
  void axi_sw_mst_ar_reset();
  void axi_sw_mst_aw_reset();
  void axi_sw_mst_w_reset();

  std::uint8_t axi_sw_mst_set_scope(cvm::topology::loc_t loc) {
    svScope scope = svGetScope();

    axi_sw_mst_ar_reset();
    axi_sw_mst_aw_reset();
    axi_sw_mst_w_reset();

    cvm::registry::messenger.signal<svScope>(
        loc,
        scope);

    return 0;
  }

}
