#pragma once
// Generated by csr_param_gen.py — CSRAL tables (docs/csral_plan.md).
// Pure data derived from the CSR spec and the csral policy YAML.
#include <array>
#include <cstdint>
#include <string_view>

namespace CSRAL {

enum class on_mismatch_t : std::uint8_t { error = 0, skip = 1, resynch_rd = 2 };
enum class compare_mask_source_t : std::uint8_t { whisper = 0, spec = 1, both_warn = 2 };
enum class reset_check_t : std::uint8_t { error = 0, warn = 1, off = 2 };

inline constexpr compare_mask_source_t kCompareMaskSource = compare_mask_source_t::spec;
inline constexpr reset_check_t kResetCheck = reset_check_t::error;

struct policy_t {
  bool check;
  on_mismatch_t on_mismatch;
  bool volatile_csr;
  bool interrupt_class;
  bool may_not_exist;
  bool check_reset;
};

struct field_t {
  std::string_view name;
  std::uint8_t msb;
  std::uint8_t lsb;
  std::uint64_t mask;
  std::uint64_t reset;  // field-value, unshifted
  std::uint16_t legal_first;
  std::uint16_t legal_count;
  std::string_view sw_type;
};

struct csr_t {
  std::string_view name;
  std::uint16_t address;
  std::uint16_t size;
  std::uint64_t reset;  // concatenated CSR reset
  std::uint64_t spec_write_mask;
  std::int16_t alias_of;   // index into kCsrs, -1 = none
  std::int16_t exists_if;  // index into kConditions gating this CSR's existence, -1 = always
  policy_t policy;
  std::uint16_t field_first;
  std::uint16_t field_count;
};

struct field_alias_t {
  std::uint16_t csr;
  std::uint8_t msb;
  std::uint8_t lsb;
  std::uint16_t alias_csr;
  std::uint8_t alias_msb;
  std::uint8_t alias_lsb;
};

struct masked_target_t {
  std::uint16_t csr;
  std::uint64_t mask;
};

struct condition_t {
  std::string_view name;  // "<gate_csr>.<gate_field>", the +csral_save_restore token
  std::uint16_t gate_csr;  // index into kCsrs
  std::uint64_t gate_mask;
  bool view_only;  // every target is an alias view: mask-only, never save/restore
  std::uint16_t target_first;
  std::uint16_t target_count;
};

inline constexpr std::size_t kNumCsrs = 9;
inline constexpr std::size_t kNumFields = 16;

inline constexpr std::array<std::uint64_t, 6> kLegalValues = {{
    0x00000000000000ABULL,
    0x0000000000000000ULL,
    0x0000000000000001ULL,
    0x0000000000000003ULL,
    0x0000000000000141ULL,
    0x0000000000001104ULL,
}};

inline constexpr std::array<field_t, 16> kFields = {{
    {"COUNT", 63, 0, 0xFFFFFFFFFFFFFFFFULL, 0x0000000000000000ULL, 0, 0, "WARL"},
    {"COUNT", 63, 0, 0xFFFFFFFFFFFFFFFFULL, 0x0000000000000000ULL, 0, 0, "WARL"},
    {"CFG_SEL", 11, 4, 0x0000000000000FF0ULL, 0x00000000000000ABULL, 0, 1, "RW"},
    {"MODE", 1, 0, 0x0000000000000003ULL, 0x0000000000000000ULL, 1, 3, "WARL"},
    {"EN", 0, 0, 0x0000000000000001ULL, 0x0000000000000001ULL, 4, 0, "WARL"},
    {"_2ND_EN", 5, 5, 0x0000000000000020ULL, 0x0000000000000001ULL, 4, 0, "WARL"},
    {"SEL_MODE", 3, 1, 0x000000000000000EULL, 0x0000000000000003ULL, 4, 0, "WARL"},
    {"MXL", 63, 60, 0xF000000000000000ULL, 0x0000000000000008ULL, 4, 0, "WARL"},
    {"EXTENSIONS", 25, 0, 0x0000000003FFFFFFULL, 0x0000000000000141ULL, 4, 2, "WARL"},
    {"DATA", 31, 0, 0x00000000FFFFFFFFULL, 0x0000000000000000ULL, 6, 0, "RW"},
    {"TAG", 35, 32, 0x0000000F00000000ULL, 0x000000000000000FULL, 6, 0, "WARL"},
    {"EN", 0, 0, 0x0000000000000001ULL, 0x0000000000000001ULL, 6, 0, "WARL"},
    {"VEN", 1, 1, 0x0000000000000002ULL, 0x0000000000000000ULL, 6, 0, "WARL"},
    {"DATA", 63, 0, 0xFFFFFFFFFFFFFFFFULL, 0x0000000000000000ULL, 6, 0, "WARL"},
    {"FLAGS", 31, 28, 0x00000000F0000000ULL, 0x0000000000000005ULL, 6, 0, "WARL"},
    {"IO_MODE", 1, 0, 0x0000000000000003ULL, 0x0000000000000002ULL, 6, 0, "WARL"},
}};

inline constexpr std::array<csr_t, 9> kCsrs = {{
    {"time", 0xC01, 64, 0x0000000000000000ULL, 0xFFFFFFFFFFFFFFFFULL, -1, -1, {true, on_mismatch_t::error, false, false, false, true}, 0, 1},
    {"utime", 0xD01, 64, 0x0000000000000000ULL, 0xFFFFFFFFFFFFFFFFULL, 0, -1, {true, on_mismatch_t::skip, false, false, false, true}, 1, 1},
    {"my_ctl", 0x7C0, 64, 0x0000000000000AB0ULL, 0x0000000000000FF3ULL, -1, -1, {true, on_mismatch_t::skip, true, false, false, true}, 2, 2},
    {"c_dbg_ctl", 0xBC0, 64, 0x0000000000000027ULL, 0x000000000000002FULL, -1, -1, {true, on_mismatch_t::error, false, false, false, true}, 4, 3},
    {"misa", 0x301, 64, 0x8000000000000141ULL, 0xF000000003FFFFFFULL, -1, -1, {false, on_mismatch_t::skip, false, false, false, true}, 7, 2},
    {"c_scratch", 0x5C0, 64, 0x0000000F00000000ULL, 0x0000000FFFFFFFFFULL, -1, -1, {false, on_mismatch_t::error, false, false, false, true}, 9, 2},
    {"xen", 0x7C1, 64, 0x0000000000000001ULL, 0x0000000000000003ULL, -1, -1, {true, on_mismatch_t::error, false, false, false, true}, 11, 2},
    {"c_indirect", 0xFFFF, 64, 0x0000000000000000ULL, 0xFFFFFFFFFFFFFFFFULL, -1, -1, {false, on_mismatch_t::error, false, false, false, true}, 13, 1},
    {"addon_status", 0xFC0, 32, 0x0000000050000002ULL, 0x00000000F0000003ULL, -1, -1, {true, on_mismatch_t::error, false, false, false, true}, 14, 2},
}};

inline constexpr std::array<field_alias_t, 1> kFieldAliases = {{
    {2, 3, 2, 5, 1, 0},
}};
inline constexpr std::size_t kNumFieldAliases = 1;

inline constexpr std::array<masked_target_t, 2> kMaskedTargets = {{
    {2, 0x0000000000000FF0ULL},
    {1, 0xFFFFFFFFFFFFFFFFULL},
}};

inline constexpr std::array<condition_t, 2> kConditions = {{
    {"xen.EN", 6, 0x0000000000000001ULL, false, 0, 1},
    {"xen.VEN", 6, 0x0000000000000002ULL, true, 1, 1},
}};
inline constexpr std::size_t kNumConditions = 2;

// Address of a CSR with no direct CSR-bus address (indirect-only,
// e.g. behind miselect/mireg selectors).
inline constexpr std::uint16_t kNoDirectAddress = 0xFFFF;

inline constexpr std::array<std::int16_t, 4096> kAddrIndex = []() {
  std::array<std::int16_t, 4096> a{};
  for (auto& e : a)
    e = -1;
  a[0xC01] = 0;
  a[0xD01] = 1;
  a[0x7C0] = 2;
  a[0xBC0] = 3;
  a[0x301] = 4;
  a[0x5C0] = 5;
  a[0x7C1] = 6;
  a[0xFC0] = 8;
  return a;
}();

constexpr const csr_t* find_by_address(std::uint64_t addr) {
  if ((addr & ~0xFFFULL) != 0)
    return nullptr;
  auto i = kAddrIndex[addr];
  return i < 0 ? nullptr : &kCsrs[static_cast<std::size_t>(i)];
}

inline const csr_t* find_by_name(std::string_view name) {
  for (const auto& c : kCsrs) {
    if (c.name == name)
      return &c;
  }
  return nullptr;
}

constexpr std::size_t index_of(const csr_t& c) {
  return static_cast<std::size_t>(&c - kCsrs.data());
}

constexpr std::uint64_t field_extract(const field_t& f, std::uint64_t csr_val) {
  return (csr_val & f.mask) >> f.lsb;
}

constexpr std::uint64_t field_insert(const field_t& f, std::uint64_t csr_val, std::uint64_t field_val) {
  return (csr_val & ~f.mask) | ((field_val << f.lsb) & f.mask);
}

} // namespace CSRAL
